### PR TITLE
KOGITO-2299 - Add namespace for GraphQL types

### PR DESCRIPTION
**Pull request by cristianonicolai**
Many thanks for submitting your Pull Request :heart:! 

Please make sure that your PR meets the following requirements:

- [ ] You have read the [contributors guide](https://github.com/kiegroup/kogito-runtimes#contributing-to-kogito)
- [ ] Pull Request title is properly formatted: `KOGITO-XYZ Subject`
- [ ] Pull Request title contains the target branch if not targeting master: `[0.9.x] KOGITO-XYZ Subject`
- [ ] Pull Request contains link to the JIRA issue
- [ ] Pull Request contains link to any dependent or related Pull Request
- [ ] Pull Request contains description of the issue
- [ ] Pull Request does not include fixes for issues other than the main ticket

### CODE REVIEW

**Comment by cristianonicolai** [comment]
@jstastny-cz this is what I could come up for adding some sort of namespace for the graphql types. Will let others comment if they like it or not, or maybe some other alternative.

**Review by jstastny-cz — APPROVED** [review]

**Review by nmirasch — APPROVED** [review]

**Comment by Sara4994** [comment]
@cristianonicolai i tried running app with these changes and i get this error "TS2305: Module '"../../../../../../node_modules/@kogito-apps/common"' has no exported member 'GraphQL'."on all the files. Am i missing something to do? 

Also a small suggestion, Can we export something like below from common/index.ts itself, which makes more clear that queries and types can be exported as "GraphQL". because right now i see "export * from './src/graphql/types';" on index.ts which doesnt say about namespace(I see that namespace on codegen.yml). wdyt?

import * as GraphQL from './src/graphql/types';
export { GraphQL }

**Comment by cristianonicolai** [comment]
@Sara4994 try running `yarn run build:prod` first

your suggestion is a lot cleaner, the only downside I see is that in the common package the import would be different. Because in there we should have access to the raw types and not the wrapped namespace. I think is a bit weird to have two different ways to import these types, wdyt?

**Review by AjayJagan — APPROVED** [review]

**Comment by Sara4994** [comment]
> @Sara4994 try running `yarn run build:prod` first
> 
> your suggestion is a lot cleaner, the only downside I see is that in the common package the import would be different. Because in there we should have access to the raw types and not the wrapped namespace. I think is a bit weird to have two different ways to import these types, wdyt?

@cristianonicolai yep that makes sense :+1:

**Review by Sara4994 — APPROVED** [review]

**Pull request merged**
