### PR TITLE
KOGITO-6016 JIT executor to support multiple DMN resources

### PR DESCRIPTION
**Pull request by tarilabs**
https://issues.redhat.com/browse/KOGITO-6016

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>Pull Request</b>  
  Please add comment: <b>Jenkins retest this</b>
 
* <b>Quarkus LTS checks</b>  
  Please add comment: <b>Jenkins run LTS</b>

* <b>Native checks</b>  
  Please add comment: <b>Jenkins run native</b>

</details>

### CODE REVIEW

**Comment by tarilabs** [comment]
Jenkins run native

**Review by danielezonca — APPROVED** [review]
LGTM 👍

**Comment by danielezonca** [comment]
Jenkins run native

**Review by hellowdan — APPROVED** [review]
LGTM!

**Pull request merged**
