### PR TITLE
 KOGITO-4248: Handled SVG Api

### PR DESCRIPTION
**Pull request by Sara4994**
Hello,

Please review this PR intended to handle the api to get process diagram,

First:
<Management console>/svg​/processes​/{processId}​/instances​/{processInstanceId}

If it fails and it's configured the svg folder at MC try:
​<Runtime_Endpoint>/svg​/processes​/{processId}​/instances​/{processInstanceId} 

JIRA issue: https://issues.redhat.com/browse/KOGITO-4248

### CODE REVIEW

**Comment by Sara4994** [comment]
Jenkins retest this

**Comment by Sara4994** [comment]
Jenkins retest this

**Comment by Sara4994** [comment]
Jenkins retest this

**Review by nmirasch — APPROVED** [review]
LGTM, Thanks @Sara4994

**Review by jstastny-cz — APPROVED** [review]

**Pull request merged**
