### PR TITLE
KOGITO-1405 - Manual acknowledge of Kafka messages

### PR DESCRIPTION
**Pull request by cristianonicolai**
Assembly:
- https://github.com/kiegroup/kogito-apps/pull/154
- https://github.com/kiegroup/kogito-runtimes/pull/420

### CODE REVIEW

**Comment by cristianonicolai** [comment]
What to expect:
- With this new approach, failed messages won't be committed to Kafka
- Once Data Index is restarted, failed messages ( non-acked ) are re-delivered
- Handling exception as much as possible to avoid https://github.com/quarkusio/quarkus/issues/8177
- If messages are not acked, that doesnt stop the services from receiving other messages.
- Added kafka metrics into /metrics
- Still no retry or DLQ in place, this will be needed moving forward.

@radtriste I'm hoping that this fixes the main issue scenario, at least.
@tiagodolphine if these changes are accepted, I think it should be propagated to Job Service as well.

**Comment by radtriste** [comment]
first tests locally are good.
I will also test tomorrow on OCP

**Comment by radtriste** [comment]
but for that, I will need a built jar file to build the images. Seems that for now the pipeline is having problems. Can you have a look ?

**Comment by cristianonicolai** [comment]
@radtriste build fixed.

**Review by radtriste — APPROVED** [review]
tested in Openshift and data-index does read old messages.
will love to test the overall once https://github.com/kiegroup/kogito-runtimes/pull/422 is backported on 0.9.x branch :)

@cristianonicolai you plan to backport to master right ?

**Comment by cristianonicolai** [comment]
@radtriste sure, will merge into master as well.

**Review by tiagodolphine — APPROVED** [review]
@cristianonicolai great work! looks good to me.

**Pull request merged**
