### PR TITLE
KOGITO-5023 JIT DMN Runner fix Response marshalling

### PR DESCRIPTION
**Pull request by tarilabs**
https://issues.redhat.com/browse/KOGITO-5023

Please make sure that your PR meets the following requirements:

- [x] You have read the [contributors guide](https://github.com/kiegroup/kogito-runtimes#contributing-to-kogito)
- [x] Pull Request title is properly formatted: `KOGITO-XYZ Subject`
- [x] Pull Request title contains the target branch if not targeting master: `[0.9.x] KOGITO-XYZ Subject`
- [x] Pull Request contains link to the JIRA issue
- [x] Pull Request contains link to any dependent or related Pull Request
- [x] Pull Request contains description of the issue
- [x] Pull Request does not include fixes for issues other than the main ticket

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>Pull Request</b>  
  Please add comment: <b>Jenkins retest this</b>
 
* <b>Quarkus LTS checks</b>  
  Please add comment: <b>Jenkins run LTS</b>

* <b>Native checks</b>  
  Please add comment: <b>Jenkins run native</b>

</details>

### CODE REVIEW

**Review by danielezonca — APPROVED** [review]
Just to double check, have you tested locally in native mode? Do you prefer to run native CI?

**Comment by tarilabs** [comment]
Jenkins run native

**Comment by tarilabs** [comment]
Native failure 🤷‍♂️ 

```
[Pipeline] echo
16:11:59  [INFO] Resolving Repository https://github.com/tarilabs/optaplanner:tarilabs-20210429. CredentialsID: kie-ci
[Pipeline] sh
16:11:59  + mktemp -d
[Pipeline] dir
16:11:59  Running in /tmp/tmp.i9A2bgvmJM
[Pipeline] {
[Pipeline] checkout
16:11:59  using credential kie-ci
16:11:59  Cloning the remote Git repository
16:11:59  ERROR: Error cloning remote repo 'origin'
16:11:59  hudson.plugins.git.GitException: Command "git fetch --tags --force --progress -- https://github.com/tarilabs/optaplanner.git +refs/heads/*:refs/remotes/origin/*" returned status code 128:
16:11:59  stdout: 
16:11:59  stderr: remote: Repository not found.
16:11:59  fatal: repository 'https://github.com/tarilabs/optaplanner.git/' not found
16:11:59  
16:11:59  	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:2372)
16:11:59  	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandWithCredentials(CliGitAPIImpl.java:1985)
16:11:59  	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.access$500(CliGitAPIImpl.java:80)
16:11:59  	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$1.execute(CliGitAPIImpl.java:563)
16:11:59  	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$2.execute(CliGitAPIImpl.java:787)
16:11:59  	at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler$GitCommandMasterToSlaveCallable.call(RemoteGitImpl.java:161)
16:11:59  	at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler$GitCommandMasterToSlaveCallable.call(RemoteGitImpl.java:154)
16:11:59  	at hudson.remoting.UserRequest.perform(UserRequest.java:212)
16:11:59  	at hudson.remoting.UserRequest.perform(UserRequest.java:54)
16:11:59  	at hudson.remoting.Request$2.run(Request.java:369)
16:11:59  	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:72)
16:11:59  	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
16:11:59  	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
16:11:59  	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
16:11:59  	at java.lang.Thread.run(Thread.java:748)
16:11:59  	Suppressed: hudson.remoting.Channel$CallSiteStackTrace: Remote call to kie-psi-rhel7-xlarge-15747
16:11:59  		at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1741)
16:11:59  		at hudson.remoting.UserRequest$ExceptionResponse.retrieve(UserRequest.java:357)
16:11:59  		at hudson.remoting.Channel.call(Channel.java:955)
16:11:59  		at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler.execute(RemoteGitImpl.java:146)
16:11:59  		at sun.reflect.GeneratedMethodAccessor927.invoke(Unknown Source)
16:11:59  		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
16:11:59  		at java.lang.reflect.Method.invoke(Method.java:498)
16:11:59  		at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler.invoke(RemoteGitImpl.java:132)
16:11:59  		at com.sun.proxy.$Proxy111.execute(Unknown Source)
16:11:59  		at hudson.plugins.git.GitSCM.retrieveChanges(GitSCM.java:1152)
16:11:59  		at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1192)
16:11:59  		at org.jenkinsci.plugins.workflow.steps.scm.SCMStep.checkout(SCMStep.java:124)
16:11:59  		at org.jenkinsci.plugins.workflow.steps.scm.SCMStep$StepExecutionImpl.run(SCMStep.java:93)
16:11:59  		at org.jenkinsci.plugins.workflow.steps.scm.SCMStep$StepExecutionImpl.run(SCMStep.java:80)
16:11:59  		at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)
16:11:59  		at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
16:11:59  		... 4 more
[Pipeline] echo
16:11:59  [WARNING] Branches [tarilabs-20210429] from repository optaplanner not found in tarilabs organisation.
```

**Comment by tarilabs** [comment]
@danielezonca not sure what's the problem with Jenkins, so tested it locally for Native:
image

**Review by hellowdan — APPROVED** [review]

**Comment by danielezonca** [comment]
Thanks for verifying it locally, merging

**Pull request merged**
