### PR TITLE
Fix test execution on Trusty service

### PR DESCRIPTION
**Pull request by cristianonicolai**
Assembly:
- https://github.com/kiegroup/kogito-runtimes/pull/1253
- https://github.com/kiegroup/kogito-apps/pull/788

### CODE REVIEW

**Comment by cristianonicolai** [comment]
@r00ta it seems that InfinispanTraceEventConsumerIT and RedisTraceEventConsumerIT were ignore due to the missing dependency. I added it back but tests now fail due to different content in the resulting JSON, could you help to take a look at what needs to be changed to fix it? 

This is related/blocking https://github.com/kiegroup/kogito-runtimes/pull/1253

**Comment by r00ta** [comment]
Hi @cristianonicolai , I'll look at it tomorrow morning EU time

**Comment by r00ta** [comment]
Hi @cristianonicolai , I think I found the issue. I will send a PR to your branch tomorrow morning

**Comment by r00ta** [comment]
Hi @cristianonicolai , apparently the tests were never executed in these months. In addition to that, at the very beginning they were not checking that the entire objects were identical. When we did a refactoring some time ago we figured out that using jsonassert the objects were not identical. 
I linked the same ticket we added so far: we will fix them in another PR, I'm very busy in these days. See https://github.com/cristianonicolai/kogito-apps/pull/4

**Review by radtriste — APPROVED** [review]

**Review by r00ta — APPROVED** [review]

**Pull request merged**
