### PR TITLE
KOGITO-1841: Added serviceUrl on Domain Explorer

### PR DESCRIPTION
**Pull request by Sara4994**
JIRA issue: https://issues.redhat.com/browse/KOGITO-1841?filter=-1

description: Added serviceUrl to display below process name on Domain Explorer.

### CODE REVIEW

**Review by cristianonicolai — APPROVED** [review]

**Review by nmirasch — APPROVED** [review]

**Review by AjayJagan — APPROVED** [review]

**Comment by srambach** [comment]
I've put in an issue on Patternfly because the link button is taking the default font size for a button, which is bigger than the font size for the compact table.
https://github.com/patternfly/patternfly-design/issues/854

Here we can override the font size manually (likely by redefining `--pf-c-button-FontSize` within the compact list), or leave as is for now and see what the PF guidance is.

**Comment by Sara4994** [comment]
> I've put in an issue on Patternfly because the link button is taking the default font size for a button, which is bigger than the font size for the compact table.
> [patternfly/patternfly-design#854](https://github.com/patternfly/patternfly-design/issues/854)
> 
> Here we can override the font size manually (likely by redefining `--pf-c-button-FontSize` within the compact list), or leave as is for now and see what the PF guidance is.

@srambach sure, lets wait for PF's guidance.

**Comment by cristianonicolai** [comment]
@Sara4994 @srambach seems like PF is fixing it, should we go ahead and merge as is?

**Review by jstastny-cz — CHANGES_REQUESTED** [review]
Please update snapshots in DomainExplorerTable.test.tsx -> with the added EndpointLink

**Comment by Sara4994** [comment]
Opened a new PR for the same https://github.com/kiegroup/kogito-apps/pull/278. hence closing this

**Comment by srambach** [comment]
> @Sara4994 @srambach seems like PF is fixing it, should we go ahead and merge as is?

FYI, I just saw the PF PR for inheriting the font size of the inline button merged.

**Pull request closed without merging**
