### PR TITLE
KOGITO-4596 Process instance details breaks when runtime kogito.service.url is undefined

### PR DESCRIPTION
**Pull request by AjayJagan**
Description : Added service url null check to show/hide the node trigger card.

JIRA : https://issues.redhat.com/browse/KOGITO-4596

### CODE REVIEW

**Comment by nmirasch** [comment]
@AjayJagan we need to add some control on the process diagram panel. When the app don't find it it goes to the runtime endpoint to look for it here: https://github.com/kiegroup/kogito-apps/blob/0b95239a79b105f903da672abc06a7d9e2e5cce6/ui-packages/packages/management-console/src/utils/Utils.tsx#L453
Even the details page is not breaking it shows an empty diagram, could you take a look? Thanks!

**Review by jstastny-cz — APPROVED** [review]

**Comment by AjayJagan** [comment]
> @AjayJagan we need to add some control on the process diagram panel. When the app don't find it it goes to the runtime endpoint to look for it here:
> 
> https://github.com/kiegroup/kogito-apps/blob/0b95239a79b105f903da672abc06a7d9e2e5cce6/ui-packages/packages/management-console/src/utils/Utils.tsx#L453
> 
> 
> Even the details page is not breaking it shows an empty diagram, could you take a look? Thanks!

@nmirasch  - I have added  service url check now :+1:

**Comment by nmirasch** [comment]
@AjayJagan Please sync with @Sara4994 about when show the error.
When the kogito.service.url is empty, the process diagram is just hidden. We will display the error when the call to the endpoint can be done and the error is something different from NOT_FOUND.

**Comment by AjayJagan** [comment]
> @AjayJagan Please sync with @Sara4994 about when show the error.
> When the kogito.service.url is empty, the process diagram is just hidden. We will display the error when the call to the endpoint can be done and the error is something different from NOT_FOUND.

@nmirasch  removed the `else` part which triggers the pop-up, thanks :)

**Review by nmirasch — APPROVED** [review]
thanks @AjayJagan

**Review by Sara4994 — APPROVED** [review]

**Pull request merged**
