### PR TITLE
KOGITO-1652 Kogito-jobs-service 0.9.0 is not starting due to a missin…

### PR DESCRIPTION
**Pull request by tiagodolphine**
Missing the configuration to disable authentication by default.

### CODE REVIEW

**Review by radtriste — APPROVED** [review]
change made the application starts correctly

**Comment by radtriste** [comment]
@tiagodolphine please also cherry-pick to `0.9.x` branch so we can release a fix after testing

**Review by cristianonicolai — APPROVED** [review]

**Review by nmirasch — APPROVED** [review]

**Review by ricardozanini — APPROVED** [review]

**Comment by radtriste** [comment]
@cristianonicolai can you merge that one ?

**Comment by radtriste** [comment]
@tiagodolphine can you cherry-pick to 0.9.0 ? :)

**Pull request merged**
