### PR TITLE
[Fix_1960] Always setting enter date

### LINKED ISSUE #1960: Enter field is null for node when event type is error
### Describe the bug

Issue https://github.com/apache/incubator-kie-issues/issues/576 added a small change related with Node event types (a new state` EVENT_TYPE_ERROR`. 
https://github.com/elguardian/kogito-apps/blob/d157e3a7595db61963c45d97173b22b02cbf335e/data-index/data-index-common/src/main/java/org/kie/kogito/index/event/mapper/ProcessInstanceNodeDataEventMerger.java#L72C13-L74C23
When the event is of this type, the enter field might be left empty, but according to graphql definition, enter is not nullable, causing this exception
```
Full Error as JSON
{
  "error": {
    "name": "CombinedError",
    "message": "[GraphQL] The field at path '/ProcessInstances[0]/nodes[7]/enter' was declared as a non null type, but the code involved in retrieving data has wrongly returned a null value.  The graphql specification requires that the parent field be set to null, or if that is non nullable that it bubble up null to its parent and so on. The non-nullable type is 'DateTime' within parent type 'NodeInstance'\n[GraphQL] The field at path '/ProcessInstances[0]/nodes[8]/enter' was declared as a non null type, but the code involved in retrieving data has wrongly returned a null value.  The graphql specification requires that the parent field be set to null, or if that is non nullable that it bubble up null to its parent and so on. The non-nullable type is 'DateTime' within parent type 'NodeInstance'",
    "graphQLErrors": [
      {
        "message": "The field at path '/ProcessInstances[0]/nodes[7]/enter' was declared as a non null type, but the code involved in retrieving data has wrongly returned a null value.  The graphql specification requires that the parent field be set to null, or if that is non nullable that it bubble up null to its parent and so on. The non-nullable type is 'DateTime' within parent type 'NodeInstance'",
        "path": [
          "ProcessInstances",
          0,
          "nodes",
          7,
          "enter"
        ],
        "extensions": {
          "classification": "NullValueInNonNullableField"
        }
      },
      {
        "message": "The field at path '/ProcessInstances[0]/nodes[8]/enter' was declared as a non null type, but the code involved in retrieving data has wrongly returned a null value.  The graphql specification requires that the parent field be set to null, or if that is non nullable that it bubble up null to its parent and so on. The non-nullable type is 'DateTime' within parent type 'NodeInstance'",
        "path": [
          "ProcessInstances",
          0,
          "nodes",
          8,
          "enter"
        ],
        "extensions": {
          "classification": "NullValueInNonNullableField"
        }
      }
    ],
    "response": {}
  },
  "request": {
    "method": "GET",
    "url": "/instances/b9af370f-b873-4191-a43a-2b50bfd9d0e3"
  },
  "response": {
    "statusCode": 500
  }
}
```

### Expected behavior

Enter should be always filled

### Actual behavior

Enter is null when even type is error

### How to Reproduce?

_No response_

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### GraalVM version (if different from Java)

_No response_

### Kogito version or git rev (or at least Quarkus version if you are using Kogito via Quarkus platform BOM)

_No response_

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by fjtirado**
Fixes https://github.com/apache/incubator-kie-kogito-apps/issues/1960

### CODE REVIEW

**Review by tiagodolphine — APPROVED** [review]

**Review by caponetto — APPROVED** [review]

**Review by porcelli — APPROVED** [review]
it looks good to me

**Comment by pefernan** [comment]
@fjtirado please don't merge this! I'd like to test it tomorrow morning.

**Comment by ederign** [comment]
@pefernan @porcelli , thank you so much for reviewing this on short notice. Are you ok if we merge it as soon as we have a green build ?

**Review by pefernan — APPROVED** [review]
Let's go for it. I'll give it a test tomorrow and will let you know if there's a side effect.

**Comment by porcelli** [comment]
@ederign  yeah - I'm good with merging as soon as green

**Comment by ederign** [comment]
Thank you so much guys!

**Review by ederign — APPROVED** [review]

**Pull request merged**
