### PR TITLE
KOGITO-2298 - Remove Component string from React component names

### PR DESCRIPTION
**Pull request by cristianonicolai**
Many thanks for submitting your Pull Request :heart:! 

Please make sure that your PR meets the following requirements:

- [ ] You have read the [contributors guide](https://github.com/kiegroup/kogito-runtimes#contributing-to-kogito)
- [ ] Pull Request title is properly formatted: `KOGITO-XYZ Subject`
- [ ] Pull Request title contains the target branch if not targeting master: `[0.9.x] KOGITO-XYZ Subject`
- [ ] Pull Request contains link to the JIRA issue
- [ ] Pull Request contains link to any dependent or related Pull Request
- [ ] Pull Request contains description of the issue
- [ ] Pull Request does not include fixes for issues other than the main ticket

### CODE REVIEW

**Review by AjayJagan — APPROVED** [review]
:+1:

**Review by nmirasch — APPROVED** [review]

**Review by jstastny-cz — COMMENTED** [review]
I can see two things conflicting here, the Jira says 'Rename components to a relevant name on management console' now we're renaming some of the components to remove 'Component' suffix from the names.
1. Is this just a subset of the changes planned for KOGITO-2298?
2. Second question would be if the PR aspires at removing all the naming issues? (Cause I see a few components keeping the 'Component' suffix in the name still.)

**Comment by cristianonicolai** [comment]
@jstastny-cz correct, this is a subset of KOGITO-2298, remaining changes are tackled in https://github.com/kiegroup/kogito-apps/pull/257

**Comment by cristianonicolai** [comment]
@jstastny-cz can you take another look, this should have all components with proper renames.

**Review by Sara4994 — APPROVED** [review]

**Review by jstastny-cz — APPROVED** [review]

**Review by pefernan — APPROVED** [review]

**Pull request merged**
