### PR TITLE
[KOGITO-5299] - Update Apps following new Addons structure

### PR DESCRIPTION
**Pull request by ricardozanini**
Signed-off-by: Ricardo Zanini <zanini@redhat.com>

See: https://github.com/kiegroup/kogito-runtimes/pull/1367

Many thanks for submitting your Pull Request :heart:! 

Please make sure that your PR meets the following requirements:

- [x] You have read the [contributors guide](https://github.com/kiegroup/kogito-runtimes#contributing-to-kogito)
- [x] Pull Request title is properly formatted: `KOGITO-XYZ Subject`
- [x] Pull Request title contains the target branch if not targeting master: `[0.9.x] KOGITO-XYZ Subject`
- [x] Pull Request contains link to the JIRA issue
- [x] Pull Request contains link to any dependent or related Pull Request
- [x] Pull Request contains description of the issue
- [x] Pull Request does not include fixes for issues other than the main ticket

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>Pull Request</b>  
  Please add comment: <b>Jenkins retest this</b>
 
* <b>Quarkus LTS checks</b>  
  Please add comment: <b>Jenkins run LTS</b>

* <b>Native checks</b>  
  Please add comment: <b>Jenkins run native</b>

</details>

### CODE REVIEW

**Comment by ricardozanini** [comment]
I believe the Jenkins CI is using a wrong `kogito-bom` snapshot (not on my branch):

```
[ERROR]   The project org.kie.kogito:persistence-commons-infinispan:2.0.0-SNAPSHOT (/home/jenkins/workspace/KIE/kogito/pullrequest/kogito-apps.tests.apps/kogito-apps/persistence-commons/persistence-commons-infinispan/pom.xml) has 1 error

[ERROR]     'dependencies.dependency.version' for org.kie.kogito:kogito-addons-quarkus-persistence-infinispan-health:jar is missing. @ line 26, column 17
```

**Comment by radtriste** [comment]
jenkins rerun apps tests

**Comment by radtriste** [comment]
@ricardozanini do you prefer it now ?
somehow in the first check, it could not find the runtimes branch on your repository ...

**Review by cristianonicolai — APPROVED** [review]

**Review by MarianMacik — APPROVED** [review]

**Review by r00ta — APPROVED** [review]

**Comment by ricardozanini** [comment]
The CI went fine, but failed to post it back here:

```
Using context: (build) Apps
Could not update commit status of the Pull Request on GitHub.
org.kohsuke.github.GHIOException: connect timed out
```

Merging

**Pull request merged**
