### PR TITLE
[incubator-kie-issues-1273] Add validate formatting to kogito runtimes and kogito-apps

### LINKED ISSUE #1273: Add validate formatting to kogito runtimes and kogito-apps

### PR DESCRIPTION
**Pull request by elguardian**
Closes https://github.com/apache/incubator-kie-issues/issues/1273

### CODE REVIEW

**Comment by jstastny-cz** [comment]
This [PR check](https://github.com/apache/incubator-kie-kogito-apps/actions/runs/9266448722/job/25490703158?pr=2066) has run with 
```
/home/runner/.local/mvn/bin/mvn dependency:tree clean install -nsu -ntp -fae -e -Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false -Dmaven.wagon.httpconnectionManager.ttlSeconds=120 -Dmaven.wagon.http.retryHandler.count=3 -Dvalidate-formatting -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn -B
```
Seems from logs that formatter plugin is triggered.

**Comment by kie-ci3** [comment]
**PR job** `#1` was: **UNSTABLE**
Possible explanation: This should be test failures


<details>
<summary><b>Reproducer</b></summary>



build-chain build full_downstream  -f 'https://raw.githubusercontent.com/${AUTHOR:apache}/incubator-kie-kogito-pipelines/${BRANCH:main}/.ci/buildchain-config-pr-cdb.yaml' -o 'bc' -p apache/incubator-kie-kogito-apps -u https://github.com/apache/incubator-kie-kogito-apps/pull/2066 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://ci-builds.apache.org/job/KIE/job/test/job/mcimbalek/job/kogito/job/main/job/pullrequest_jobs/job/kogito-apps-pr/job/PR-2066/1/display/redirect

**Test results:**
- PASSED: 1662
- FAILED: 4

Those are the test failures: 
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/test/job/mcimbalek/job/kogito/job/main/job/pullrequest_jobs/job/kogito-apps-pr/job/PR-2066/1/testReport/org.kie.kogito.index.mongodb/ProcessDataIndexMongoDBHttpIT/testProcessInstanceEvents/">org.kie.kogito.index.mongodb.ProcessDataIndexMongoDBHttpIT.testProcessInstanceEvents</a></summary>
1 expectation failed.<br/>JSON path data.UserTaskInstances[0].potentialGroups[0] doesn't match.<br/>Expected: managers<br/>  Actual: null<br/>
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/test/job/mcimbalek/job/kogito/job/main/job/pullrequest_jobs/job/kogito-apps-pr/job/PR-2066/1/testReport/org.kie.kogito.index.mongodb/ProcessDataIndexMongoDBKafkaIT/testProcessInstanceEvents/">org.kie.kogito.index.mongodb.ProcessDataIndexMongoDBKafkaIT.testProcessInstanceEvents</a></summary>
1 expectation failed.<br/>JSON path errors doesn't match.<br/>Expected: null<br/>  Actual: <[{message=Exception while fetching data (/UserTaskInstances[0]/schema) : Runtime service URL not defined, please review the kogito.service.url system property to point the public URL for this runtime., locations=[{line=1, column=85}], path=[UserTaskInstances, 0, schema], extensions={classification=DataFetchingException}}]><br/>
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/test/job/mcimbalek/job/kogito/job/main/job/pullrequest_jobs/job/kogito-apps-pr/job/PR-2066/1/testReport/org.kie.kogito.index/ProcessDataIndexMongoDBIT/testProcessInstanceEvents/">org.kie.kogito.index.ProcessDataIndexMongoDBIT.testProcessInstanceEvents</a></summary>
Cannot invoke method size() on null object
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/test/job/mcimbalek/job/kogito/job/main/job/pullrequest_jobs/job/kogito-apps-pr/job/PR-2066/1/testReport/org.kie.kogito.jobs.embedded/EmbeddedJobsServiceTest/testJobService/">org.kie.kogito.jobs.embedded.EmbeddedJobsServiceTest.testJobService</a></summary>
java.util.ConcurrentModificationException<br/>	at java.base/java.util.ArrayList.forEach(ArrayList.java:1513)<br/>	at org.kie.kogito.jobs.embedded.EmbeddedJobsServiceTest.testJobService(EmbeddedJobsServiceTest.java:99)<br/>	at java.base/java.lang.reflect.Method.invoke(Method.java:568)<br/>	at io.quarkus.test.junit.QuarkusTestExtension.runExtensionMethod(QuarkusTestExtension.java:1013)<br/>	at io.quarkus.test.junit.QuarkusTestExtension.interceptTestMethod(QuarkusTestExtension.java:827)<br/>	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)<br/>	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)<br/>
</details>

**Review by baldimir — APPROVED** [review]

**Review by jstastny-cz — APPROVED** [review]
LGTM.

**Comment by kie-ci3** [comment]
**PR job** `#2` was: **UNSTABLE**
Possible explanation: This should be test failures


<details>
<summary><b>Reproducer</b></summary>



build-chain build full_downstream  -f 'https://raw.githubusercontent.com/${AUTHOR:apache}/incubator-kie-kogito-pipelines/${BRANCH:main}/.ci/buildchain-config-pr-cdb.yaml' -o 'bc' -p apache/incubator-kie-kogito-apps -u https://github.com/apache/incubator-kie-kogito-apps/pull/2066 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://ci-builds.apache.org/job/KIE/job/kogito/job/apache_migration/job/pullrequest_jobs/job/kogito-apps-pr/job/PR-2066/2/display/redirect

**Test results:**
- PASSED: 1660
- FAILED: 5

Those are the test failures: 
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/apache_migration/job/pullrequest_jobs/job/kogito-apps-pr/job/PR-2066/2/testReport/org.kie.kogito.index.mongodb/ProcessDataIndexMongoDBHttpIT/testProcessInstanceEvents/">org.kie.kogito.index.mongodb.ProcessDataIndexMongoDBHttpIT.testProcessInstanceEvents</a></summary>
1 expectation failed.<br/>JSON path data.UserTaskInstances[0].potentialGroups[0] doesn't match.<br/>Expected: managers<br/>  Actual: null<br/>
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/apache_migration/job/pullrequest_jobs/job/kogito-apps-pr/job/PR-2066/2/testReport/org.kie.kogito.index.mongodb/ProcessDataIndexMongoDBKafkaIT/testProcessInstanceEvents/">org.kie.kogito.index.mongodb.ProcessDataIndexMongoDBKafkaIT.testProcessInstanceEvents</a></summary>
1 expectation failed.<br/>JSON path data.UserTaskInstances[0].potentialGroups[0] doesn't match.<br/>Expected: managers<br/>  Actual: null<br/>
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/apache_migration/job/pullrequest_jobs/job/kogito-apps-pr/job/PR-2066/2/testReport/org.kie.kogito.index/ProcessDataIndexInfinispanIT/testProcessInstanceEvents/">org.kie.kogito.index.ProcessDataIndexInfinispanIT.testProcessInstanceEvents</a></summary>
1 expectation failed.<br/>JSON path errors doesn't match.<br/>Expected: null<br/>  Actual: <[{message=Exception while fetching data (/UserTaskInstanceAttachmentUpdate) : Index 0 out of bounds for length 0, locations=[{line=1, column=12}], path=[UserTaskInstanceAttachmentUpdate], extensions={classification=DataFetchingException}}]><br/>
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/apache_migration/job/pullrequest_jobs/job/kogito-apps-pr/job/PR-2066/2/testReport/org.kie.kogito.index/ProcessDataIndexMongoDBIT/testProcessInstanceEvents/">org.kie.kogito.index.ProcessDataIndexMongoDBIT.testProcessInstanceEvents</a></summary>
1 expectation failed.<br/>JSON path data.UserTaskInstances[0].potentialGroups[0] doesn't match.<br/>Expected: managers<br/>  Actual: null<br/>
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/apache_migration/job/pullrequest_jobs/job/kogito-apps-pr/job/PR-2066/2/testReport/org.kie.kogito.jobs.service.scheduler.impl/VertxTimerServiceSchedulerTest/testScheduleJob/">org.kie.kogito.jobs.service.scheduler.impl.VertxTimerServiceSchedulerTest.testScheduleJob</a></summary>
<br/>Unnecessary stubbings detected.<br/>Clean & maintainable test code requires zero unnecessary code.<br/>Following stubbings are unnecessary (click to navigate to relevant line of code):<br/>  1. -> at org.kie.kogito.jobs.service.scheduler.impl.VertxTimerServiceSchedulerTest.testScheduleJob(VertxTimerServiceSchedulerTest.java:98)<br/>  2. -> at org.kie.kogito.jobs.service.scheduler.impl.VertxTimerServiceSchedulerTest.testScheduleJob(VertxTimerServiceSchedulerTest.java:99)<br/>Please remove unnecessary stubbings or use 'lenient' strictness. More info: javadoc for UnnecessaryStubbingException class.
</details>

**Pull request merged**
