### PR TITLE
KOGITO-593 Add pagination controls to datalist

### PR DESCRIPTION
**Pull request by AjayJagan**
- added pagination to data list.

### CODE REVIEW

**Comment by cristianonicolai** [comment]
@AjayJagan this PR needs rebase now.

**Comment by AjayJagan** [comment]
> @AjayJagan this PR needs rebase now.

done :)

**Comment by cristianonicolai** [comment]
@AjayJagan @srambach does the pagination component supports not having a total count? We had similar issue for v7 and we want to avoid having to do extra query just for the sake of having a count number. If this is something that isn't really supported by the component we might need to check an alternative way of doing the pagination.

**Comment by srambach** [comment]
@cristianonicolai One of our designers suggested something along the lines of "1 to 20 of 300ish" Would something like that help here? Would you be querying often enough to be close, if not exact? Also I'm not sure how well that internationalizes ;-P

**Comment by cristianonicolai** [comment]
@srambach I don't think there is much point on showing some data that will be inaccurate anyway ( how would that help users?), not to mention the internationalization issue :P

**Comment by srambach** [comment]
I think the Pagination controls should show up in the toolbar, whether we use the Patternfly component or our own.
Like you see here: https://www.patternfly.org/v4/design-guidelines/usage-and-behavior/pagination#main-content

It looks really good... @cristianonicolai how about making it say "1 - 10 of **about** 13" 🥺😁

**Comment by cristianonicolai** [comment]
@srambach it looks nice indeed. 
Well, how do we come up with the **13** ?? :P The point is to remove any need for doing another query, simply to do a count :/

**Pull request closed without merging**
