### PR TITLE
KOGITO-5610: Monorepo migration: Import monorepo setup - Part 1

### PR DESCRIPTION
**Pull request by paulovmr**
Updated dependency versions;
Updated ESLint configuration;
Used TypeScript Compiler instead of Webpack in non-webapp packages;

### CODE REVIEW

**Comment by manstis** [comment]
It'd be nice to be kept advised of the progress of this move...

@kelvah @sjamboro FYI.. since we have open PRs for trusty at the moment.

**Comment by paulovmr** [comment]
Jenkins retest this

**Review by pefernan — APPROVED** [review]
@paulovmr this is huge!

I gave it a try and seems to work fine, I'd say +1 to merge but I may request others to review just in case I'm missing some cases

**Comment by Sara4994** [comment]
This looks good to me. Thanks @paulovmr

**Review by Sara4994 — APPROVED** [review]

**Review by AjayJagan — APPROVED** [review]
Thanks @paulovmr LGTM

**Comment by paulovmr** [comment]
Jenkins retest this

**Comment by AjayJagan** [comment]
Jenkins retest this

**Comment by paulovmr** [comment]
Jenkins retest this

**Comment by manstis** [comment]
Hey @paulovmr can you please also align Trusty?

See https://github.com/kiegroup/kogito-apps/blob/main/ui-packages/packages/trusty/package.json

@pefernan @kelvah this could explain why I'm getting the weird errors.. as I build both locally.

**Comment by manstis** [comment]
IDK if you want to upgrade the Maven configuration too? 

See https://github.com/kiegroup/kogito-apps/blob/main/kogito-apps-build-parent/pom.xml#L24-L26?

It seems most of us have much newer versions of Node installed which highlights an issue with error messages:-

> [Michael Anstis]: 16.13.1 has the error message I see: https://github.com/nodejs/node/blob/v16.13.1/deps/v8/src/common/message-template.h
> [Michael Anstis]: 16.8.0 has the message you see: https://github.com/nodejs/node/blob/v16.8.0/deps/v8/src/common/message-template.h
> [Michael Anstis]: ok, and our pom.xml uses node 16.2: https://github.com/kiegroup/kogito-apps/blob/main/kogito-apps-build-parent/pom.xml#L24

**Pull request merged**
