### PR TITLE
KOGITO-1511: Bug fixes

### PR DESCRIPTION
**Pull request by Sara4994**

### CODE REVIEW

**Review by AjayJagan — APPROVED** [review]
looks good

**Comment by cristianonicolai** [comment]
@Sara4994 can you add the same delay in the backend to fetch the data, as we do for process instances, so we can see the loading state?

**Comment by cristianonicolai** [comment]
@Sara4994 needs rebase

**Comment by Sara4994** [comment]
> @Sara4994 needs rebase

@cristianonicolai rebase done

**Review by cristianonicolai — APPROVED** [review]

**Pull request merged**
