### PR TITLE
KOGITO-3620: UI changes on Task Console

### PR DESCRIPTION
**Pull request by pefernan**
Some UI changes for Task Console

Many thanks for submitting your Pull Request :heart:! 

Please make sure that your PR meets the following requirements:

- [ ] You have read the [contributors guide](https://github.com/kiegroup/kogito-runtimes#contributing-to-kogito)
- [ ] Pull Request title is properly formatted: `KOGITO-XYZ Subject`
- [ ] Pull Request title contains the target branch if not targeting master: `[0.9.x] KOGITO-XYZ Subject`
- [ ] Pull Request contains link to the JIRA issue
- [ ] Pull Request contains link to any dependent or related Pull Request
- [ ] Pull Request contains description of the issue
- [ ] Pull Request does not include fixes for issues other than the main ticket

### CODE REVIEW

**Comment by pefernan** [comment]
@AjayJagan @jstastny-cz would you mind take a look??

**Review by AjayJagan — APPROVED** [review]
LGTM, +1

**Review by jstastny-cz — APPROVED** [review]

**Comment by pefernan** [comment]
jenkins retest this please

**Comment by pefernan** [comment]
jenkins retest this please

**Review by AjayJagan — APPROVED** [review]
LGTM :+1:

**Comment by pefernan** [comment]
jenkins retest this

**Pull request merged**
