### PR TITLE
KOGITO-4089 Task console package OUIA compliance for organisms

### PR DESCRIPTION
**Pull request by jstastny-cz**
Depends on #593 and #594 .

[KOGITO-4089](https://issues.redhat.com/browse/KOGITO-4089)

### CODE REVIEW

**Review by AjayJagan — APPROVED** [review]
:+1:

**Comment by jstastny-cz** [comment]
rebased after #593 and #594 were merged.

**Comment by jstastny-cz** [comment]
Sonar complaining about coverage - I am not affecting functionality in this PR, yet I've apparently changed a non-tested branch of code.
Should I add a test?

**Review by pefernan — APPROVED** [review]

**Comment by pefernan** [comment]
@jstastny-cz I'm ok with that, we can enhance tests later

**Pull request merged**
