### PR TITLE
[kie-issues#628] Change JBoss Nexus to Apache Nexus.

### PR DESCRIPTION
**Pull request by baldimir**
Changes JBoss Nexus repository to Apache Nexus.

### CODE REVIEW

**Review by jstastny-cz — APPROVED** [review]
LGTM.

**Comment by kie-ci3** [comment]
**PR job** `#1` was: **UNSTABLE**
Possible explanation: This should be test failures


<details>
<summary><b>Reproducer</b></summary>



build-chain build full_downstream  -f 'https://raw.githubusercontent.com/${AUTHOR:apache}/incubator-kie-kogito-pipelines/${BRANCH:main}/.ci/buildchain-config-pr-cdb.yaml' -o 'bc' -p apache/incubator-kie-kogito-apps -u https://github.com/apache/incubator-kie-kogito-apps/pull/1896 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-apps-pr/job/PR-1896/1/display/redirect

**Test results:**
- PASSED: 2776
- FAILED: 3

Those are the test failures: 
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-apps-pr/job/PR-1896/1/testReport/org.kie.kogito.jobs.service.messaging/InfinispanMessagingApiTest/cancelJob/">org.kie.kogito.jobs.service.messaging.InfinispanMessagingApiTest.cancelJob</a></summary>
java.lang.RuntimeException: Failed to start quarkus
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-apps-pr/job/PR-1896/1/testReport/org.kie.kogito.jobs.service.repository.infinispan/InfinispanJobRepositoryTest/testFindAll/">org.kie.kogito.jobs.service.repository.infinispan.InfinispanJobRepositoryTest.testFindAll</a></summary>
java.lang.RuntimeException: Failed to start quarkus
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-apps-pr/job/PR-1896/1/testReport/org.kie.kogito.jobs.service.resource/KeycloakInfinispanJobServiceTest/___/">org.kie.kogito.jobs.service.resource.KeycloakInfinispanJobServiceTest.(?)</a></summary>
java.lang.RuntimeException: Failed to start quarkus
</details>

**Comment by jstastny-cz** [comment]
Last test failures are known issues.

**Review by domhanak — APPROVED** [review]

**Comment by jstastny-cz** [comment]
@tiagobento @baldimir can we wrap this one up?

**Pull request merged**
