### PR TITLE
KOGITO-3452: uniform error handling of build/encode/decode in CloudEventUtils

### PR DESCRIPTION
**Pull request by kostola**
- [JIRA task](https://issues.redhat.com/browse/KOGITO-3452)

### CODE REVIEW

**Review by ruromero — APPROVED** [review]

**Review by danielezonca — APPROVED** [review]
LGTM

**Comment by kostola** [comment]
jenkins retest this please

**Review by ricardozanini — COMMENTED** [review]
@ruromero this makes sense in other parts of the code you refactored, like in the knative addon?

**Comment by danielezonca** [comment]
@ricardozanini 
Wdym?
This PR is related to the refactor of [this class](https://github.com/kiegroup/kogito-runtimes/blob/master/addons/tracing/tracing-decision-api/src/main/java/org/kie/kogito/tracing/decision/event/CloudEventUtils.java) (now it returns an `Optional`) that is used here. So I don't expect any impact on knative addon.
Btw that class is quite generic so we can consider it to move it to a shared lib somewhere

**Comment by ruromero** [comment]
I agree with @danielezonca I don't think it affects the addon.

**Comment by ricardozanini** [comment]
> Btw that class is quite generic so we can consider it to move it to a shared lib somewhere


That's why I asked 😀

Looked like something we already had, I'm sorry if I caused any mess.

Thanks for the clarification guys!

**Pull request merged**
