### PR TITLE
[KOGITO-3566] Improve Task Inbox Query

### PR DESCRIPTION
**Pull request by bxf12315**
Many thanks for submitting your Pull Request :heart:! 
Improve Task Inbox Query
Jira: https://issues.redhat.com/browse/KOGITO-3566

Please make sure that your PR meets the following requirements:

- [ ] You have read the [contributors guide](https://github.com/kiegroup/kogito-runtimes#contributing-to-kogito)
- [ ] Pull Request title is properly formatted: `KOGITO-XYZ Subject`
- [ ] Pull Request title contains the target branch if not targeting master: `[0.9.x] KOGITO-XYZ Subject`
- [ ] Pull Request contains link to the JIRA issue
- [ ] Pull Request contains link to any dependent or related Pull Request
- [ ] Pull Request contains description of the issue
- [ ] Pull Request does not include fixes for issues other than the main ticket

### CODE REVIEW

**Comment by pefernan** [comment]
jenkins retest this please

**Review by cristianonicolai — CHANGES_REQUESTED** [review]
@bxf12315 please look into enhancing AbstractIndexingServiceIT.testUserTaskInstanceIndex test so a query with null actual owner is covered in there.

**Comment by bxf12315** [comment]
@pefernan @cristianonicolai @jstastny-cz @prashuts the PR can not run our CI, so I open another PR, I will close it. Thanks

**Comment by pefernan** [comment]
Closed, duplicated https://github.com/kiegroup/kogito-apps/pull/509

**Pull request closed without merging**
