### PR TITLE
FAI-679: CF UI - Changed inputs inside CF solutions are not highlighted correctly

### PR DESCRIPTION
**Pull request by kelvah**
JIRA: https://issues.redhat.com/browse/FAI-679

Fixing highlighting of changed inputs inside counterfactual solutions.
After running a CF analysis and getting some solutions, only inputs that differ from the original inputs should have the light blue background. Currently they are all highlighted.

(Also took the chance to improve mocked CF results to alter only non fixed search inputs. It was necessary to test the fix with mocked data.)

Screenshots of the CF table when an analysis is complete:

Before
cf-before

After
cd-after

Please make sure that your PR meets the following requirements:

- [x] You have read the [contributors guide](https://github.com/kiegroup/kogito-runtimes#contributing-to-kogito)
- [x] Pull Request title is properly formatted: `KOGITO-XYZ Subject`
- [x] Pull Request title contains the target branch if not targeting main: `[0.9.x] KOGITO-XYZ Subject`
- [x] Pull Request contains link to the JIRA issue
- [x] Pull Request contains link to any dependent or related Pull Request
- [x] Pull Request contains description of the issue
- [x] Pull Request does not include fixes for issues other than the main ticket

<details>
<summary>
How to replicate CI configuration locally?
</summary>

Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use latest version of the code for each repository.
 
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you need to change multiple repositories and send multiple dependent pull requests related with a change you can easily reproduce the same build by executing it on Github hosted environment or locally in your development environment. See [local execution](https://github.com/kiegroup/github-action-build-chain#local-execution) details to get more information about it.
</details>

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>Pull Request</b>  
  Please add comment: <b>Jenkins retest this</b>
 
* <b>Quarkus LTS checks</b>  
  Please add comment: <b>Jenkins run LTS</b>

* <b>Native checks</b>  
  Please add comment: <b>Jenkins run native</b>

</details>

### CODE REVIEW

**Comment by manstis** [comment]
Any chance you can increase the contrast? It was difficult to see what was being highlighted:

FAI-679

**Comment by kelvah** [comment]
> Any chance you can increase the contrast? It was difficult to see what was being highlighted:
> 
> FAI-679

uhm I think you have found a different bug on the highlighting of new columns. I'll investigate.

**Comment by kelvah** [comment]
Jenkins retest this please

**Comment by kelvah** [comment]
> uhm I think you have found a different bug on the highlighting of new columns. I'll investigate.

So this is not a bug. When new solutions columns are added they have a quick background color animation to highlight their addition. 

After the animation ends the changed inputs still keep a different background color. This PR is only affecting the permanent color of those input cells.

**Review by manstis — APPROVED** [review]
LGTM :+1:

**Review by sjamboro — APPROVED** [review]

**Pull request merged**
