### PR TITLE
KOGITO-2811 Remove node_modules as part of mvn clean

### PR DESCRIPTION
**Pull request by cristianonicolai**
Many thanks for submitting your Pull Request :heart:! 

Please make sure that your PR meets the following requirements:

- [ ] You have read the [contributors guide](https://github.com/kiegroup/kogito-runtimes#contributing-to-kogito)
- [ ] Pull Request title is properly formatted: `KOGITO-XYZ Subject`
- [ ] Pull Request title contains the target branch if not targeting master: `[0.9.x] KOGITO-XYZ Subject`
- [ ] Pull Request contains link to the JIRA issue
- [ ] Pull Request contains link to any dependent or related Pull Request
- [ ] Pull Request contains description of the issue
- [ ] Pull Request does not include fixes for issues other than the main ticket

### CODE REVIEW

**Review by jstastny-cz — APPROVED** [review]

**Review by radtriste — APPROVED** [review]
tried locally by executing twice `mvn clean install -DskipTests` and seems to solve the `rimraf not found` problem

**Comment by porcelli** [comment]
based on the call yesterday I understand the issue of the build is annoying and I expect this is just a short term solution, before a major overall revisiting of the structure in place.

as this is like the maven equivalent of an `rm -rf ~/.m2` on every build :)

**Comment by cristianonicolai** [comment]
@porcelli yes, this is a temporary fix to give us more time to identify a more appropriate fix.

**Comment by kelvah** [comment]
I think also `node_modules` folders inside each package should be wiped, if present.

**Comment by cristianonicolai** [comment]
@kelvah added node_modules for projects inside packages.

**Review by kelvah — APPROVED** [review]

**Pull request merged**
