### PR TITLE
KOGITO-9901: Repair kogito-apps GHA in apache repository

### PR DESCRIPTION
**Pull request by wmedvede**
Many thanks for submitting your Pull Request :heart:! 

Please make sure that your PR meets the following requirements:

- [X] You have read the [contributors guide](https://github.com/apache/incubator-kie-kogito-runtimes#contributing-to-kogito)
- [X] Pull Request title is properly formatted: `KOGITO-XYZ Subject`
- [X] Pull Request title contains the target branch if not targeting main: `[0.9.x] KOGITO-XYZ Subject`
- [X] Pull Request contains link to the JIRA issue
- [X] Pull Request contains link to any dependent or related Pull Request
- [X] Pull Request contains description of the issue
- [X] Pull Request does not include fixes for issues other than the main ticket

<details>
<summary>
How to replicate CI configuration locally?
</summary>

Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use latest version of the code for each repository.
 
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you need to change multiple repositories and send multiple dependent pull requests related with a change you can easily reproduce the same build by executing it on Github hosted environment or locally in your development environment. See [local execution](https://github.com/kiegroup/github-action-build-chain#local-execution) details to get more information about it.
</details>

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

- for <b>pull request checks</b>  
  Please add comment: <b>Jenkins retest this</b>

- for a <b>specific pull request check</b>  
  Please add comment: <b>Jenkins (re)run [kogito-apps|kogito-examples] tests</b>

- for <b>quarkus branch checks</b>  
  Run checks against Quarkus current used branch  
  Please add comment: <b>Jenkins run quarkus-branch</b>

- for a <b>quarkus branch specific check</b>  
  Run checks against Quarkus current used branch  
  Please add comment: <b>Jenkins (re)run [kogito-apps|kogito-examples] quarkus-branch</b>

- for <b>quarkus main checks</b>  
  Run checks against Quarkus main branch  
  Please add comment: <b>Jenkins run quarkus-main</b>

- for a <b>specific quarkus main check</b>  
  Run checks against Quarkus main branch  
  Please add comment: <b>Jenkins (re)run [kogito-apps|kogito-examples] quarkus-main</b>

- for <b>quarkus lts checks</b>  
  Run checks against Quarkus lts branch  
  Please add comment: <b>Jenkins run quarkus-lts</b>

- for a <b>specific quarkus lts check</b>  
  Run checks against Quarkus lts branch  
  Please add comment: <b>Jenkins (re)run [kogito-apps|kogito-examples] quarkus-lts</b>
 
- for <b>native checks</b>  
  Run native checks  
  Please add comment: <b>Jenkins run native</b>

- for a <b>specific native check</b>  
  Run native checks 
  Please add comment: <b>Jenkins (re)run [kogito-apps|kogito-examples] native</b>

- for <b>native lts checks</b>  
  Run native checks against quarkus lts branch
  Please add comment: <b>Jenkins run native-lts</b>

- for a <b>specific native lts check</b>  
  Run native checks against quarkus lts branch
  Please add comment: <b>Jenkins (re)run [kogito-apps|kogito-examples] native-lts</b>
 
</details>

<details>
<summary>
How to backport a pull request to a different branch?
</summary>

In order to automatically create a **backporting pull request** please add one or more labels having the following format `backport-<branch-name>`, where `<branch-name>` is the name of the branch where the pull request must be backported to (e.g., `backport-7.67.x` to backport the original PR to the `7.67.x` branch).

> **NOTE**: **backporting** is an action aiming to move a change (usually a commit) from a branch (usually the main one) to another one, which is generally referring to a still maintained release branch. Keeping it simple: it is about to move a specific change or a set of them from one branch to another.

Once the original pull request is successfully merged, the automated action will create one backporting pull request per each label (with the previous format) that has been added.

If something goes wrong, the author will be notified and at this point a manual backporting is needed.

> **NOTE**: this automated backporting is triggered whenever a pull request on `main` branch is labeled or closed, but both conditions must be satisfied to get the new PR created.
</details>

<details>
<summary>
Quarkus-3 PR check is failing ... what to do ?
</summary>
The Quarkus 3 check is applying patches from the `.ci/environments/quarkus-3/patches`.

The first patch, called `0001_before_sh.patch`, is generated from Openrewrite `.ci/environments/quarkus-3/quarkus3.yml` recipe. The patch is created to speed up the check. But it may be that some changes in the PR broke this patch.  
No panic, there is an easy way to regenerate it. You just need to comment on the PR:
```
jenkins rewrite quarkus-3
```
and it should, after some minutes (~20/30min) apply a commit on the PR with the patch regenerated.

Other patches were generated manually. If any of it fails, you will need to manually update it... and push your changes.
</details>

### CODE REVIEW

**Review by jstastny-cz — APPROVED** [review]
LGTM. let's see how that turns out.

**Review by ricardozanini — APPROVED** [review]

**Comment by ricardozanini** [comment]
Looks like we are getting a green here! 🎉

**Comment by wmedvede** [comment]
@ricardozanini @jstastny-cz 

Regarding the GHA these are the results:

Screenshot from 2023-10-24 09-26-47

So, at least for this run, we have 3 GHA that worked fine, which means they are working.

Then, for the failing one  **Kogito Apps / ubuntu-latest / Java-11 / Maven-3.8.7 (pull_request)** we have that:

- It says, **"Failing after 210m",**  and in fact it has configured timeout:   **timeout-minutes: 210**

- However by downloading the execution logs, I can see that drools, kogito-runtines and kogio-apps has a build success, see below. 

Finally by looking at the build times for each repository, I can see:

- drools -> Total time:  **05:21** min
- kogito-runtimes -> Total time:  **39:54** min
- kogito-apps -> Total time:  **02:34** h


So it looks like the execution was marked as "failure" because the build time of drools exceeded the action timeout of 210 min.

I conclude that the GHA has worked fine, however, we might probably need o increase that timeout. ¿? 
I'll move this timeout to 6 hs and let this run again.


2023-10-23T14:22:10.4285564Z [INFO] Drools :: DRL on YAML :: CLI ....................... SUCCESS [  1.764 s]
2023-10-23T14:22:10.4286634Z [INFO] Drools :: DRL on YAML :: CLI tests ................. SUCCESS [  2.642 s]
2023-10-23T14:22:10.4287816Z [INFO] ------------------------------------------------------------------------
2023-10-23T14:22:10.4288505Z [INFO] **BUILD SUCCESS**
2023-10-23T14:22:10.4289194Z [INFO] ------------------------------------------------------------------------
2023-10-23T14:22:10.4289908Z [INFO] Total time:  05:21 min
2023-10-23T14:22:10.4290504Z [INFO] Finished at: 2023-10-23T14:22:10Z
2023-10-23T14:22:10.4291326Z [INFO] ------------------------------------------------------------------------
2023-10-23T14:22:10.5078547Z [INFO] **Execution summary for apache/incubator-kie-drools**

2023-10-23T15:02:06.1696852Z [INFO] Kogito :: Spring Boot :: Maven Archetype ........... SUCCESS [  5.893 s]
2023-10-23T15:02:06.1774944Z [INFO] Kogito :: Test Utilities :: Spring Boot ............ SUCCESS [  0.855 s]
2023-10-23T15:02:06.1776124Z [INFO] Kogito :: Integration Tests :: Spring Boot ......... SUCCESS [  3.322 s]
2023-10-23T15:02:06.1777319Z [INFO] ------------------------------------------------------------------------
2023-10-23T15:02:06.1778188Z [INFO] **BUILD SUCCESS**
2023-10-23T15:02:06.1778881Z [INFO] ------------------------------------------------------------------------
2023-10-23T15:02:06.1779604Z [INFO] Total time:  39:54 min
2023-10-23T15:02:06.1780199Z [INFO] Finished at: 2023-10-23T15:02:06Z
2023-10-23T15:02:06.1781011Z [INFO] ------------------------------------------------------------------------
2023-10-23T15:02:06.9247605Z [INFO] **Execution summary for apache/incubator-kie-kogito-runtimes**

2023-10-23T17:36:13.0317133Z [INFO] Runtime Tools Quarkus Extension - Runtime .......... SUCCESS [  9.227 s]
2023-10-23T17:36:13.0318366Z [INFO] Runtime Tools Quarkus Extension - Deployment ....... SUCCESS [ 10.448 s]
2023-10-23T17:36:13.0319546Z [INFO] ------------------------------------------------------------------------
2023-10-23T17:36:13.0320242Z [INFO] **BUILD SUCCESS**
2023-10-23T17:36:13.0320992Z [INFO] ------------------------------------------------------------------------
2023-10-23T17:36:13.0321693Z [INFO] Total time:  02:34 h
2023-10-23T17:36:13.0322289Z [INFO] Finished at: 2023-10-23T17:36:13Z
2023-10-23T17:36:13.0323092Z [INFO] ------------------------------------------------------------------------
2023-10-23T17:36:14.4659223Z [INFO] **Execution summary for apache/incubator-kie-kogito-apps**

**Comment by wmedvede** [comment]
I looks that we have all the GHA in green now! I think this can be merged. @krisv 

The CI failure is unrelated from the GHA

[INFO] Generator discovery performed, found [processes]

[INFO] No Java source to compile

[WARNING] [io.quarkus.config] Unrecognized configuration key "kogito.persistence.type" was provided; it will be ignored; verify that the dependency extension for this configuration is set or that you did not make a typo

[WARNING] [io.quarkus.config] Unrecognized configuration key "kogito.apps.persistence.type" was provided; it will be ignored; verify that the dependency extension for this configuration is set or that you did not make a typo

java.io.IOException: No space left on device

	at java.base/sun.nio.ch.FileDispatcherImpl.write0(Native Method)

	at java.base/sun.nio.ch.FileDispatcherImpl.write(FileDispatcherImpl.java:62)

	at java.base/sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:113)

	at java.base/sun.nio.ch.IOUtil.write(IOUtil.java:79)

	at java.base/sun.nio.ch.FileChannelImpl.write(FileChannelImpl.java:280)

	at java.base/java.nio.channels.Channels.writeFullyImpl(Channels.java:74)

	at java.base/java.nio.channels.Channels.writeFully(Channels.java:97)

**Comment by jstastny-cz** [comment]
@wmedvede agreed, env issue, though we're not innocent when a single python example downloads 2,5 GB libraries :-D That's crazy.

**Comment by ricardozanini** [comment]
> @wmedvede agreed, env issue, though we're not innocent when a single python example downloads 2,5 GB libraries :-D That's crazy.

@fjtirado can you shed a light here? I think we might have to remove this example. 2.5GB libraries are too much, might be a problem running it in every PR. Maybe we can add a profile and run only in nightly builds or try another approach?

**Comment by jstastny-cz** [comment]
I think we could preinstall in the docker image and skip libs install then during example run. ... But the size of the image then? Might be still a hit

**Comment by ricardozanini** [comment]
> I think we could preinstall in the docker image and skip libs install then during example run. ... But the size of the image then? Might be still a hit

Yes, I thought about the possibility of having a cache somewhere, but 2.5GB might be too much. Unless we have a strong reason why not.

**Comment by fjtirado** [comment]
@jstastny-cz @ricardozanini 
I never say I liked the way Python works ;)
Normally those libraries are cached in the file system and downloaded only once. 
Since downloading only once is not currently feasible using Jenkins, what I would do is not to delete the example, but to remove the reference from the parent POM. We still keep the example (which was pretty useful for Helber and can be useful for anyone trying to do something not trivial with Sonata and python) but at the same time we skip the CI for it (yes, we might broke it accidentally without noticing, but I think it is a good compromise)

**Comment by ricardozanini** [comment]
+1 to keep the example and remove it from the parent pom. Not sure if my discourse was to delete the example, but to find a way to have it without the hurdle. It's a good compromise. @jstastny-cz wdyt?

**Review by krisv — APPROVED** [review]

**Comment by wmedvede** [comment]
looks like we have the greens now, merging. @ricardozanini @jstastny-cz 

btw, can I ask you @fjtirado to please send a complementary PR to manage the Phyton example? maybe by adding a profile?

**Comment by fjtirado** [comment]
> looks like we have the greens now, merging. @ricardozanini @jstastny-cz
> 
> btw, can I ask you @fjtirado to please send a complementary PR to manage the Phyton example? maybe by adding a profile?

https://github.com/apache/incubator-kie-kogito-examples/pull/1825

**Pull request merged**
