### PR TITLE
FAI-608: CF UI: Toggle all/none checkbox does not work

### PR DESCRIPTION
**Pull request by manstis**
See https://issues.redhat.com/browse/FAI-608

Many thanks for submitting your Pull Request :heart:! 

Please make sure that your PR meets the following requirements:

- [x] You have read the [contributors guide](https://github.com/kiegroup/kogito-runtimes#contributing-to-kogito)
- [x] Pull Request title is properly formatted: `KOGITO-XYZ Subject`
- [x] Pull Request title contains the target branch if not targeting main: `[0.9.x] KOGITO-XYZ Subject`
- [x] Pull Request contains link to the JIRA issue
- [x] Pull Request contains link to any dependent or related Pull Request
- [x] Pull Request contains description of the issue
- [x] Pull Request does not include fixes for issues other than the main ticket

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>Pull Request</b>  
  Please add comment: <b>Jenkins retest this</b>
 
* <b>Quarkus LTS checks</b>  
  Please add comment: <b>Jenkins run LTS</b>

* <b>Native checks</b>  
  Please add comment: <b>Jenkins run native</b>

</details>

### CODE REVIEW

**Review by kelvah — APPROVED** [review]
LGTM :+1:

**Comment by manstis** [comment]
Jenkins retest this

**Comment by manstis** [comment]
Removed @tiagobento since this is not a `kogito-tooling` PR.. Doh!

**Comment by manstis** [comment]
Jenkins retest this

**Comment by manstis** [comment]
@mbiarnes @Ginxo FYI.. IDK if it's cause for concern for anyone.

Persistent error leading to failure of `kogito-apps\ui-packages` is:
```
Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.9.1:install-node-and-npm (install-node-and-npm) on project kogito-apps-ui-packages: Could not download Node.js: Got error code 503 from the server
```

**Comment by manstis** [comment]
@sjamboro I have rebased this PR now #1040 has been merged.

It is ready for review.

**Review by sjamboro — APPROVED** [review]

**Pull request merged**
