### PR TITLE
KOGITO-2678: Configure Kogito Services to enable/disable security at …

### PR DESCRIPTION
**Pull request by nmirasch**
…runtime
https://issues.redhat.com/browse/KOGITO-2678
Change job and data-index services security configuration to be able to enable / disable security at runtime with quarkus.oidc.tenant-enabled property

### CODE REVIEW

**Review by Sgitario — APPROVED** [review]

**Comment by nmirasch** [comment]
Jenkins retest this please

**Comment by nmirasch** [comment]
@cristianonicolai @tiagodolphine this configuration changes have been included to allow to enable/disable security on runtime. Could you take a look? thanks!

**Comment by nmirasch** [comment]
@cristianonicolai @tiagodolphine could you take a look here?? :-)

**Review by cristianonicolai — APPROVED** [review]

**Comment by cristianonicolai** [comment]
@nmirasch probably worth a doc update with instructions?

**Review by tiagodolphine — APPROVED** [review]
LGTM thanks @nmirasch

**Pull request merged**
