### PR TITLE
KOGITO-4156 Fix Jobs service unit test failing

### PR DESCRIPTION
**Pull request by tiagodolphine**
Many thanks for submitting your Pull Request :heart:! 

Please make sure that your PR meets the following requirements:

- [ ] You have read the [contributors guide](https://github.com/kiegroup/kogito-runtimes#contributing-to-kogito)
- [ ] Pull Request title is properly formatted: `KOGITO-XYZ Subject`
- [ ] Pull Request title contains the target branch if not targeting master: `[0.9.x] KOGITO-XYZ Subject`
- [ ] Pull Request contains link to the JIRA issue
- [ ] Pull Request contains link to any dependent or related Pull Request
- [ ] Pull Request contains description of the issue
- [ ] Pull Request does not include fixes for issues other than the main ticket

### CODE REVIEW

**Comment by tiagodolphine** [comment]
jenkins retest this

**Comment by tiagodolphine** [comment]
jenkins retest this

**Review by evacchi — APPROVED** [review]
o_O is this really enough? wow

**Review by MarianMacik — APPROVED** [review]
If it's enough, I am ok with it :+1:

**Comment by tiagodolphine** [comment]
jenkins retest this

**Comment by tiagodolphine** [comment]
triggering the build again, to see if it gets green again... 
so far it seems to be fixed...

**Comment by evacchi** [comment]
all green, merging @tiagodolphine

**Pull request merged**
