### PR TITLE
KOGITO 5092 - Tooltip bug fix

### PR DESCRIPTION
**Pull request by AjayJagan**
bug fix for tooltip in item descriptor

### CODE REVIEW

**Comment by AjayJagan** [comment]
jenkins retest this please

**Comment by AjayJagan** [comment]
jenkins retest this please

**Comment by AjayJagan** [comment]
jenkins retest this please

**Review by pefernan — APPROVED** [review]
+1 when green

**Comment by pefernan** [comment]
jenkins retest this please

**Comment by AjayJagan** [comment]
jenkins retest this please

**Comment by pefernan** [comment]
jenkins retest this

**Pull request merged**
