### PR TITLE
KOGITO-3787: New columns on Jobs management section

### PR DESCRIPTION
**Pull request by Sara4994**
Many thanks for submitting your Pull Request :heart:! 

Please make sure that your PR meets the following requirements:

- [ ] You have read the [contributors guide](https://github.com/kiegroup/kogito-runtimes#contributing-to-kogito)
- [ ] Pull Request title is properly formatted: `KOGITO-XYZ Subject`
- [ ] Pull Request title contains the target branch if not targeting master: `[0.9.x] KOGITO-XYZ Subject`
- [ ] Pull Request contains link to the JIRA issue
- [ ] Pull Request contains link to any dependent or related Pull Request
- [ ] Pull Request contains description of the issue
- [ ] Pull Request does not include fixes for issues other than the main ticket

### CODE REVIEW

**Comment by Sara4994** [comment]
jenkins please retest this

**Comment by Sara4994** [comment]
jenkins please retest this

**Review by AjayJagan — APPROVED** [review]
LGTM :+1:

**Comment by Sara4994** [comment]
jenkins please retest this

**Review by jstastny-cz — APPROVED** [review]
LGTM, the snapshot changes seems just.

**Comment by nmirasch** [comment]
@Sara4994  could be possible add the column counter to Job Details modal too? Is a bit weird to see the info at columns and not in details.

**Comment by Sara4994** [comment]
> @Sara4994 could be possible add the column counter to Job Details modal too? Is a bit weird to see the info at columns and not in details.

@nmirasch done

**Review by nmirasch — APPROVED** [review]

**Pull request merged**
