### PR TITLE
KOGITO-5099: Patternfly version upgrade

### PR DESCRIPTION
**Pull request by Sara4994**
Many thanks for submitting your Pull Request :heart:! 

Please make sure that your PR meets the following requirements:

- [ ] You have read the [contributors guide](https://github.com/kiegroup/kogito-runtimes#contributing-to-kogito)
- [ ] Pull Request title is properly formatted: `KOGITO-XYZ Subject`
- [ ] Pull Request title contains the target branch if not targeting main: `[0.9.x] KOGITO-XYZ Subject`
- [ ] Pull Request contains link to the JIRA issue
- [ ] Pull Request contains link to any dependent or related Pull Request
- [ ] Pull Request contains description of the issue
- [ ] Pull Request does not include fixes for issues other than the main ticket

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>Pull Request</b>  
  Please add comment: <b>Jenkins retest this</b>
 
* <b>Quarkus LTS checks</b>  
  Please add comment: <b>Jenkins run LTS</b>

* <b>Native checks</b>  
  Please add comment: <b>Jenkins run native</b>

</details>

### CODE REVIEW

**Review by AjayJagan — APPROVED** [review]
LGTM ... thanks

**Review by pefernan — APPROVED** [review]
+1

**Comment by pefernan** [comment]
@kelvah we are upgrading pf version, do you want to take a look?

**Review by paulovmr — APPROVED** [review]

**Comment by Sara4994** [comment]
Jenkins retest this

**Comment by Sara4994** [comment]
There is a test failure on TaskDetailsPage.test.tsx component, test suit: 'Task details Drawer'. This failure happens due to latest on the PF changes on drawer component. To remove the blocker and to proceed with the PR, I have removed the check for now. Will investigate this issue with PF team and fix that check in a future PR.

**Comment by pefernan** [comment]
Thanks @Sara4994, we'll try to add the check back later.

**Comment by Sara4994** [comment]
Jenkins retest this

**Comment by kelvah** [comment]
Thanks @pefernan for the heads up.

Everything seems fine for Trusty. I only noticed a minor aesthetic issue on Toolbars. There is now some extra space below them.



I was trying to find the cause and I realized it's a specific behavior (maybe a bug?) of PatternFly 2021.08. You can see it in its docs examples. The issue seems gone in later releases.

It isn't a big deal of course, I could produce a PR with some fix around it.
Just wondering, why are we updating to 2021.08 instead of the latest PF version? Are there other issues targeting 2021.12?

**Comment by pefernan** [comment]
@kelvah the main reason was becasue we needed to use CodeEditor component and in that version there were some improvements that were working ok for us. We can try to update to latest and check if that works for everyone

**Comment by Sara4994** [comment]
@kelvah Also, didn't want to have a big jump on PF versions since there could be some breaking changes and I noticed tests/snapshots failures on many components. These are failures are caused by dom level changes on various PF components. The PF versions used here in this PR are minimal required versions for the code editor to work.

**Comment by Sara4994** [comment]
Jenkins retest this

**Pull request closed without merging**
