### PR TITLE
KOGITO-5258 Share OUIA tools across kogito-apps ui-packages

### PR DESCRIPTION
**Pull request by jstastny-cz**
[KOGITO-5258](https://issues.redhat.com/browse/KOGITO-5258)

Goals:
* extract OUIA related utils to reusable packages

Solution:
* introduce ouia-tools with utility methods to set OUIA attributes
* introduce cypress-ouia package with reusable cypress commands

Other changes
* Removed getWrapper and getWrapperAsync - due to library conflicts after refactoring into a separate package, during investigation it became obvious these are not much useful anymore and all can be achieved using enzyme, act and wait.
* Fixed Cypress tests for management-console - changes in management-console components regarding OUIA attributes resulted in updated snapshots.
* Attempted at fixing Cypress tests for management-console-webapp - configured properly, but tests themselves fail due to endless loading of process instance list - will be investigated and fixed later on.

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>Pull Request</b>  
  Please add comment: <b>Jenkins retest this</b>
 
* <b>Quarkus LTS checks</b>  
  Please add comment: <b>Jenkins run LTS</b>

* <b>Native checks</b>  
  Please add comment: <b>Jenkins run native</b>

</details>

### CODE REVIEW

**Review by pefernan — APPROVED** [review]

**Comment by jstastny-cz** [comment]
@pefernan I've adapted the sonar config now (as discussed async) in a separate commit.

**Comment by jstastny-cz** [comment]
Sonar configuration fixed as can be seen in the related PR check.

**Comment by jstastny-cz** [comment]
@paulovmr could you please focus on the newly added ouia-tools and cypress-ouia modules - if the configuration is ok. I don't want to put you through complete review here.

**Review by AjayJagan — APPROVED** [review]
great!!

**Comment by jstastny-cz** [comment]
@Sara4994 @paulovmr  just a friendly reminder, do you want to review this one? I mean, Pere and Ajay reviewed already, PR check does guard any possible omission, so I think it would be safe to reduce number of reviewers. Though I'll leave to you to decide this.
Once approved, I would rebase and let the checks run.

**Review by Sara4994 — APPROVED** [review]

**Comment by Sara4994** [comment]
@jstastny-cz looks good to me. Thanks :+1:

**Comment by jstastny-cz** [comment]
Just rebased to latest master. Any omission would show as failed test in the check.

**Review by paulovmr — APPROVED** [review]

**Comment by jstastny-cz** [comment]
jenkins retest this
the previous build got stuck in trusty tests.

**Pull request merged**
