### PR TITLE
KOGITO-2296 check code coverage for management-console

### PR DESCRIPTION
**Pull request by jstastny-cz**
Including Management Console for inclusion in code coverage statistics by invoking the `test:coverage` check from the management-console maven module (not to be mistaken with packages/management-console package).

### CODE REVIEW

**Comment by cristianonicolai** [comment]
@jstastny-cz would we be running the tests again when _test:coverage_ is executed? Or perhaps the _build:prod_ should already take care of producing that?  Also, I wonder if we need to consolidate the settings from https://github.com/kiegroup/kogito-apps/blob/master/packages/management-console/package.json#L17 into https://github.com/kiegroup/kogito-apps/blob/master/packages/management-console/package.json#L19

**Comment by jstastny-cz** [comment]
@cristianonicolai agreed, now the tests run twice.
I am not sure if `build:prod` should do this already. Maybe it can since we want this to be vital part of the prod process and it has only small influence on the build. If I exaggerate - it just shows a nice table.
And to the test script arguments, if we're doing the above, I will just redefine the `test:coverage` script as `yarn test --coverage` to have things in sync.

**Comment by MarianMacik** [comment]
@jstastny-cz Please rebase your PR so you have the newest pipeline on your branch (the one for webhooks) By default, with your code also the pipeline definition is taken into the PR check.

**Comment by cristianonicolai** [comment]
@jstastny-cz +1 to include coverage in the _build:prod_.

**Comment by jstastny-cz** [comment]
@cristianonicolai @nmirasch 
With the latest changes we get:
https://sonarcloud.io/component_measures?id=org.kie.kogito%3Akogito-apps&metric=coverage&selected=org.kie.kogito%3Akogito-apps%3Apackages%2Fmanagement-console%2Fsrc

**Review by cristianonicolai — APPROVED** [review]

**Comment by cristianonicolai** [comment]
@jstastny-cz can you add the same changes to all 3 modules, task-console and common as well?

**Comment by jstastny-cz** [comment]
So just to let you know, I am reworking how we actually build the apps in packages.
This will be delivered as part of the reorg, so I might close this PR in favor of the new one.

**Comment by jstastny-cz** [comment]
Closing in favor of #264

**Pull request closed without merging**
