### PR TITLE
Kogito-4088 Task console package OUIA compliance for molecules

### PR DESCRIPTION
**Pull request by jstastny-cz**
[KOGITO-4088](https://issues.redhat.com/browse/KOGITO-4088)

OUIA component compliance for Molecules.

Follows-up on #593

### CODE REVIEW

**Comment by jstastny-cz** [comment]
jenkins retest this

**Review by pefernan — APPROVED** [review]
+1 Thanks @jstastny-cz

**Review by AjayJagan — APPROVED** [review]
:+1:

**Comment by jstastny-cz** [comment]
rebased after merging #593 .

**Pull request merged**
