### PR TITLE
KOGITO-3790 - Fix integration tests artifact id

### PR DESCRIPTION
**Pull request by r00ta**
The current artifactId `integration-tests` is in conflict with `integration-tests` module in kogito-runtimes. 

The proposal is the following

Screenshot from 2020-11-06 09-43-39

Many thanks for submitting your Pull Request :heart:! 

Please make sure that your PR meets the following requirements:

- [ ] You have read the [contributors guide](https://github.com/kiegroup/kogito-runtimes#contributing-to-kogito)
- [ ] Pull Request title is properly formatted: `KOGITO-XYZ Subject`
- [ ] Pull Request title contains the target branch if not targeting master: `[0.9.x] KOGITO-XYZ Subject`
- [ ] Pull Request contains link to the JIRA issue
- [ ] Pull Request contains link to any dependent or related Pull Request
- [ ] Pull Request contains description of the issue
- [ ] Pull Request does not include fixes for issues other than the main ticket

### CODE REVIEW

**Review by radtriste — APPROVED** [review]

**Review by danielezonca — APPROVED** [review]
LGTM :+1:

**Comment by radtriste** [comment]
@r00ta looks like there is a jacoco problem with that move ...

https://rhba-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/blue/organizations/jenkins/KIE%2Fkogito%2Fghprb-webhooks%2Fkogito-apps/detail/kogito-apps/1752/pipeline

can you please check ?

**Comment by r00ta** [comment]
> @r00ta looks like there is a jacoco problem with that move ...
> 
> https://rhba-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/blue/organizations/jenkins/KIE%2Fkogito%2Fghprb-webhooks%2Fkogito-apps/detail/kogito-apps/1752/pipeline
> 
> can you please check ?

Yep I'm checking

**Comment by r00ta** [comment]
Hi @radtriste , I've checked locally and apparently master is broken. Just to be sure that it's not my env that is broken, I've run https://github.com/kiegroup/kogito-apps/pull/525

**Comment by radtriste** [comment]
but https://github.com/kiegroup/kogito-runtimes/pull/869 PR check passed ... or am I missing something ?
Could the change have caused a problem here ?

**Comment by radtriste** [comment]
Jenkins retest this

**Comment by r00ta** [comment]
Hi @radtriste , I'm trying to make some tests also around master to understand what's going on here

**Comment by r00ta** [comment]
I can't reaproduce in any way :/ Let's see if it was a problem on the CI

**Comment by r00ta** [comment]
Hi @radtriste , I found the issue, fixing it

**Comment by r00ta** [comment]
Screenshot from 2020-11-06 13-21-54
The antrun/build-main.xml sonar file that specifies what are the files to be excluded from the analysis is still removing `**/integration-tests/**/target/classes/**/*.class` instead of `**/apps-integration-tests/**/target/classes/**/*.class`

**Comment by r00ta** [comment]
Found the fix, the excluded files are specified here https://github.com/kiegroup/kogito-runtimes/blob/5ed39618bdb47fdcab7c8fa03e3a9167d1a37a60/kogito-build-parent/pom.xml#L1320

**Comment by r00ta** [comment]
jenkins retest this please

**Comment by r00ta** [comment]
See https://github.com/kiegroup/kogito-runtimes/pull/872

**Comment by radtriste** [comment]
@r00ta not sure we need to change the runtimes part. do want to make it specific with `apps` things

**Comment by radtriste** [comment]
I would suggest to rename the module, in this PR, to update the module artifactId to `apps-integration-tests` but the folder stays as `integration-tests`
so it would be excluded

**Comment by r00ta** [comment]
> I would suggest to rename the module, in this PR, to update the module artifactId to `apps-integration-tests` but the folder stays as `integration-tests`
> so it would be excluded

Sure, fixing

**Comment by radtriste** [comment]
Jenkins retest this

**Comment by r00ta** [comment]
Jenkins retest this

**Comment by r00ta** [comment]
Jenkins retest this

**Comment by radtriste** [comment]
Jenkins retest this

**Comment by radtriste** [comment]
Jenkins retest this

**Comment by radtriste** [comment]
Jenkins retest this

**Comment by r00ta** [comment]
Apparently quarkus is trying to resolve the dependency locally, and it is resolving the path as `<repo>/<artifactId>/pom.xml`. Have a look here 
https://github.com/kiegroup/kogito-apps/pull/527
https://rhba-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/blue/rest/organizations/jenkins/pipelines/KIE/pipelines/kogito/pipelines/ghprb-webhooks/pipelines/kogito-apps/runs/1771/log/?start=0
The module is named `my-apps-integration-tests` and the erorr is 
```
[INFO] Running org.kie.kogito.infinispan.health.InfinispanHealthCheckIT
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.341 s <<< FAILURE! - in org.kie.kogito.infinispan.health.InfinispanHealthCheckIT
[ERROR] testCall  Time elapsed: 0.024 s  <<< ERROR!
java.lang.RuntimeException: io.quarkus.bootstrap.BootstrapException: Failed to create the application model for null
Caused by: io.quarkus.bootstrap.BootstrapException: Failed to create the application model for null
Caused by: io.quarkus.bootstrap.resolver.maven.BootstrapMavenException: Failed to load current project at /home/jenkins/workspace/KIE/kogito/ghprb-webhooks/kogito-apps/kogito-runtimes/addons/persistence/infinispan-quarkus-health-addon/pom.xml
Caused by: io.quarkus.bootstrap.resolver.maven.BootstrapMavenException: Failed to read /home/jenkins/workspace/KIE/kogito/ghprb-webhooks/kogito-apps/my-apps-integration-tests/pom.xml
Caused by: java.nio.file.NoSuchFileException: /home/jenkins/workspace/KIE/kogito/ghprb-webhooks/kogito-apps/my-apps-integration-tests/pom.xml
```
Just to share some investigations..

**Comment by radtriste** [comment]
Thx for sharing.
questions would be: why runtimes would need apps ? and how does it know about this change in apps ?

**Comment by r00ta** [comment]
Jenkins retest this

**Comment by cristianonicolai** [comment]
jenkins please retest this

**Comment by cristianonicolai** [comment]
@r00ta could you rename to folder as well in a follow up PR? thanks

**Comment by r00ta** [comment]
@cristianonicolai I've reopened https://github.com/kiegroup/kogito-runtimes/pull/872 so to exclude the .class files from the codecov analysis

**Comment by cristianonicolai** [comment]
@r00ta please cherry pick this into 1.0.x branch.

**Comment by danielezonca** [comment]
@cristianonicolai 
Already green and merged :) 
https://github.com/kiegroup/kogito-apps/pull/531

**Pull request merged**
