### PR TITLE
[1.6.x] FAI-469 - Fix explainability endpoint

### PR DESCRIPTION
**Pull request by r00ta**
Many thanks for submitting your Pull Request :heart:! 

Please make sure that your PR meets the following requirements:

- [ ] You have read the [contributors guide](https://github.com/kiegroup/kogito-runtimes#contributing-to-kogito)
- [ ] Pull Request title is properly formatted: `KOGITO-XYZ Subject`
- [ ] Pull Request title contains the target branch if not targeting master: `[0.9.x] KOGITO-XYZ Subject`
- [ ] Pull Request contains link to the JIRA issue
- [ ] Pull Request contains link to any dependent or related Pull Request
- [ ] Pull Request contains description of the issue
- [ ] Pull Request does not include fixes for issues other than the main ticket

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>Pull Request</b>  
  Please add comment: <b>Jenkins retest this</b>
 
* <b>Quarkus LTS checks</b>  
  Please add comment: <b>Jenkins run LTS</b>

* <b>Native checks</b>  
  Please add comment: <b>Jenkins run native</b>

</details>

### CODE REVIEW

**Comment by manstis** [comment]
@r00ta presumably this is a cherry-pick of https://github.com/kiegroup/kogito-apps/pull/768?

**Review by manstis — APPROVED** [review]
Approving on the basis that this is a cherry-pick from `master`.

**Comment by r00ta** [comment]
Jenkins retest this please

**Comment by r00ta** [comment]
Jenkins retest this please

**Comment by r00ta** [comment]
Jenkins retest this please

**Comment by radtriste** [comment]
@r00ta I think you are targeting the wrong branch on your PR :)

**Comment by r00ta** [comment]
> @r00ta I think you are targeting the wrong branch on your PR :)

Thank you for the catch Tristan : )

**Comment by r00ta** [comment]
Jenkins retest this please

**Comment by mbiarnes** [comment]
Jenkins retest this please

**Comment by r00ta** [comment]
Jenkins retest this please

**Pull request merged**
