### PR TITLE
KOGITO-5667 Split Quarkus and Spring Boot specific test-utils in diff…

### PR DESCRIPTION
**Pull request by cristianonicolai**
…erent modules

Assembly:
- https://github.com/kiegroup/kogito-examples/pull/840
- https://github.com/kiegroup/kogito-apps/pull/976
- https://github.com/kiegroup/kogito-runtimes/pull/1510

### CODE REVIEW

**Review by radtriste — APPROVED** [review]

**Review by ricardozanini — APPROVED** [review]

**Comment by cristianonicolai** [comment]
jenkins please retest this

**Comment by cristianonicolai** [comment]
Jenkins rerun apps tests

**Comment by cristianonicolai** [comment]
Jenkins rerun apps tests

**Comment by cristianonicolai** [comment]
Jenkins rerun apps tests

**Comment by cristianonicolai** [comment]
Jenkins rerun apps tests

**Comment by cristianonicolai** [comment]
Jenkins rerun apps tests

**Comment by cristianonicolai** [comment]
Jenkins rerun apps tests

**Pull request merged**
