### PR TITLE
KOGITO-3894: Anonymous navigation should be allowed when auth is not enabled

### PR DESCRIPTION
**Pull request by pefernan**
Adding back the Anonymous navigation by default.
- Restored Anonymous navigation.
- Added ability to enable the test user system by setting a new env param `TEST_USER_SYSTEM_ENABLED` to true (defaults to false!). 
- Added ability to enable the test user system on the Task/Management Console quarkus apps by adding a new argument  `-Dkogito.test.user-system.enabled=true` when starting the quarkus app. It won't work if the app starts in auth mode (`-Dquarkus.profile=keycloak`)

This is part of an ensemble, please merge with:
https://github.com/kiegroup/kogito-apps/pull/564
https://github.com/kiegroup/kie-docs/pull/3123

Many thanks for submitting your Pull Request :heart:! 

Please make sure that your PR meets the following requirements:

- [ ] You have read the [contributors guide](https://github.com/kiegroup/kogito-runtimes#contributing-to-kogito)
- [ ] Pull Request title is properly formatted: `KOGITO-XYZ Subject`
- [ ] Pull Request title contains the target branch if not targeting master: `[0.9.x] KOGITO-XYZ Subject`
- [ ] Pull Request contains link to the JIRA issue
- [ ] Pull Request contains link to any dependent or related Pull Request
- [ ] Pull Request contains description of the issue
- [ ] Pull Request does not include fixes for issues other than the main ticket

### CODE REVIEW

**Comment by pefernan** [comment]
@nmirasch should this be in the doc? I'd say that the README should be enough WDYT?

**Review by jstastny-cz — APPROVED** [review]

**Comment by pefernan** [comment]
jenkins retest this please

**Review by Sara4994 — APPROVED** [review]

**Comment by pefernan** [comment]
jenkins retest this please

**Comment by pefernan** [comment]
jenkins retest this please

**Comment by pefernan** [comment]
@nmirasch sonarcloud is failing due to code duplication in the VertxRouter... I'd say that we can merge this if you approve but maybe we could change that in the future.

**Comment by nmirasch** [comment]
@pefernan Makes sense to add this property to a README, regarding the development purposes but I would like to centralize all that we have in the main doc, maybe just adding a note when we explain how to 'enable security to consoles', commenting this property allows to define a DEV user system. WDYT?

About the sonarcloud, I agree as we talked we need to unify duplication that we have there, but  that could be part of future enhancements.

**Review by nmirasch — APPROVED** [review]
LGTM, Thanks @pefernan!

**Comment by pefernan** [comment]
jenkins retest this please

**Pull request merged**
