### PR TITLE
KOGITO-1901: Rename DE column picker

### PR DESCRIPTION
**Pull request by Sara4994**
Many thanks for submitting your Pull Request :heart:! 

Please make sure that your PR meets the following requirements:

- [ ] You have read the [contributors guide](https://github.com/kiegroup/kogito-runtimes#contributing-to-kogito)
- [ ] Pull Request title is properly formatted: `KOGITO-XYZ Subject`
- [ ] Pull Request title contains the target branch if not targeting master: `[0.9.x] KOGITO-XYZ Subject`
- [ ] Pull Request contains link to the JIRA issue
- [ ] Pull Request contains link to any dependent or related Pull Request
- [ ] Pull Request contains description of the issue
- [ ] Pull Request does not include fixes for issues other than the main ticket

### CODE REVIEW

**Review by cristianonicolai — APPROVED** [review]

**Comment by cristianonicolai** [comment]
jenkins please retest this

**Review by AjayJagan — APPROVED** [review]

**Comment by jstastny-cz** [comment]
@Sara4994 @cristianonicolai can we fix the bug reported by Sonar [1]? I know it's cause the rename, but still would be helpful to investigate.
Seems like we're using Array.prototype.filter function and not working with the result, I failed at finding any side-effects in call chain, are there any?

[1] https://sonarcloud.io/project/issues?id=org.kie.kogito%3Akogito-apps&open=AXLkQ1ivwr4z7lQF3AAD&pullRequest=292&resolved=false&types=BUG

**Comment by cristianonicolai** [comment]
@jstastny-cz I think is worth fixing but @Sara4994 is working on the actual code changes in a new PR, I would suggest/be fine to be fixed in there, wdyt?

**Comment by jstastny-cz** [comment]
@cristianonicolai fair enough.

**Review by jstastny-cz — CHANGES_REQUESTED** [review]
Please also rename the component returned by the mock defined inside file
`__mocks__/DomainExplorerManageColumns.tsx`.

**Comment by Sara4994** [comment]
> Please also rename the component returned by the mock defined inside file
> `__mocks__/DomainExplorerManageColumns.tsx`.

Well renaming this component, would show that file as deleted+created on git logs. so thought to rename in the next PR.

**Comment by jstastny-cz** [comment]
@Sara4994 even if added as another commit?

**Comment by cristianonicolai** [comment]
> @Sara4994 even if added as another commit?

@jstastny-cz very likely as we at the end of the day, we merge every PR as a single git commit. The file is very small so I think the rename will cause git to consider as a new file, unfortunately.

@Sara4994 perhaps do a small follow up PR on top of this one so we dont loose track of these pending changes? rename and sonar bug

**Comment by Sara4994** [comment]
> > @Sara4994 even if added as another commit?
> 
> @jstastny-cz very likely as we at the end of the day, we merge every PR as a single git commit. The file is very small so I think the rename will cause git to consider as a new file, unfortunately.
> 
> @Sara4994 perhaps do a small follow up PR on top of this one so we dont loose track of these pending changes? rename and sonar bug

@cristianonicolai sure :+1:  will create a new PR once this gets merge

**Review by nmirasch — APPROVED** [review]

**Review by jstastny-cz — APPROVED** [review]

**Pull request merged**
