### PR TITLE
KOGITO-8869 - Use Quarkus Config for default values

### PR DESCRIPTION
**Pull request by cristianonicolai**

### CODE REVIEW

**Comment by cristianonicolai** [comment]
@nmirasch I think we should create a follow-up JIRA to try to unify `kogito.dataindex.*` and `kogito.data-index.*` properties, its confusing right now. I would suggest we keep `kogito.data-index`.

**Review by caponetto — APPROVED** [review]
Thanks a lot, @cristianonicolai!

**Review by nmirasch — APPROVED** [review]

**Comment by cristianonicolai** [comment]
jenkins please retest this

**Comment by cristianonicolai** [comment]
jenkins please retest this

**Pull request merged**
