### PR TITLE
KOGITO-2655 - Add trustyAI ui-package and locktt configuration

### PR DESCRIPTION
**Pull request by kelvah**
Link to jira ticket: [KOGITO-2655](https://issues.redhat.com/browse/KOGITO-2655)

This PR adds the trusty ui-package with basic building configuration and initial import of the app container element. Other PR's will follow with the application content.

With this PR the `yarn.lock` file gets checked to version control and top level dependencies get listed with minor update configuration (`^`). [lock-treatment-tool](https://github.com/Ginxo/lock-treatment-tool) configuration has been added to update the lock file with the internal npm registry url before dependencies installation.

Please make sure that your PR meets the following requirements:

- [x] You have read the [contributors guide](https://github.com/kiegroup/kogito-runtimes#contributing-to-kogito)
- [x] Pull Request title is properly formatted: `KOGITO-XYZ Subject`
- [ ] Pull Request title contains the target branch if not targeting master: `[0.9.x] KOGITO-XYZ Subject`
- [x] Pull Request contains link to the JIRA issue
- [ ] Pull Request contains link to any dependent or related Pull Request
- [x] Pull Request contains description of the issue
- [x] Pull Request does not include fixes for issues other than the main ticket

### CODE REVIEW

**Comment by manstis** [comment]
@kelvah I receive this running `mvn clean install -DskipTests` locally:
```
[INFO] --- frontend-maven-plugin:1.9.1:npm (lock-treatment-tool execution) @ kogito-apps-ui-packages ---
[INFO] Running 'npm run locktt -- --registry=${env.NPM_REGISTRY_URL}' in /home/manstis/workspaces/git/manstis/forks/kogito-apps/ui-packages
[INFO] 
[INFO] > kogito-apps@0.0.0 locktt /home/manstis/workspaces/git/manstis/forks/kogito-apps/ui-packages
[INFO] > locktt "--registry=${env.NPM_REGISTRY_URL}"
[INFO] 
[INFO] sh: 1: Bad substitution
[INFO] npm ERR! code ELIFECYCLE
[INFO] npm ERR! errno 2
[INFO] npm ERR! kogito-apps@0.0.0 locktt: `locktt "--registry=${env.NPM_REGISTRY_URL}"`
[INFO] npm ERR! Exit status 2
[INFO] npm ERR! 
[INFO] npm ERR! Failed at the kogito-apps@0.0.0 locktt script.
[INFO] npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```
Is there additional setup needed?

**Comment by kelvah** [comment]
> Is there additional setup needed?

hi @manstis, no additional setup required. I fixed the `locktt` configuration. It should be ok now locally.

**Review by jstastny-cz — COMMENTED** [review]
Thanks for the changes @kelvah . Seems good, one concern though - shouldn't we cover the usage of locktt in readme?

**Comment by kelvah** [comment]
> Thanks for the changes @kelvah . Seems good, one concern though - shouldn't we cover the usage of locktt in readme?

hi @jstastny-cz, thank you. I've added a section to readme with locktt notes.

**Comment by cristianonicolai** [comment]
jenkins please retest this

**Review by cristianonicolai — APPROVED** [review]

**Comment by Sara4994** [comment]
@kelvah @cristianonicolai This looks good. Just one suggestion can we use Atomic folder structure for components inside src/components, as we have in other two apps(Management-console, Task-console). wdyt? Now i see we have one component TrustyApp, which must be placed inside Templates folder. For more details about Atomic structure https://atomicdesign.bradfrost.com/chapter-2/

**Comment by kelvah** [comment]
Thank you @Sara4994. I noticed the usage of atomic design pattern in all `ui-packages`. My intention is to introduce it with the next PR's, when I'll be dealing with the actual application content. `TrustyApp` is just a placeholder for now, meant to render something and check that everything is working. Is that OK?

I'll share a couple of thoughts while you mentioned it. I am a big fan of the work Brad Frost has done over the years. Atomic design has been a game changer in the way UIs are built, even more in how they're designed. Anyway, the main reason why it was conceived is to build design systems, that are discussed many times in the book and related posts. It's kind of tricky to adapt atomic principles in standalone applications, like `ui-packages`, where we actually make large use of components provided by Patternfly. We probably write very few atoms and molecules because they are already there. We mostly write wrappers and containers instead, which hardly find a precise collocation inside atomic design categories.

Doubts aside, trusty is the last project added to the list. So I think it's reasonable to adapt it to the common file structure already shared by other packages. Perhaps the time is too late to approach this kind of discussion :)

**Comment by Sara4994** [comment]
@kelvah cool that works, atomic structure can be introduced in the next PR's as you mentioned. 

And really a valid point mentioned about atomic structure. Just a thought, We had some cases where we had to override some of the PF components to meet our requirements and we placed such components under Atoms and Molecules. I am not sure of trusty app's requirements but atleast this will help us in grouping components when component count increases, instead of dumping every thing under src/components.

**Review by Sara4994 — APPROVED** [review]

**Review by nmirasch — APPROVED** [review]

**Review by pefernan — APPROVED** [review]

**Pull request merged**
