### PR TITLE
[DROOLS-5688] Adapt to public API

### PR DESCRIPTION
**Pull request by gitgabrio**
@danielezonca @tteofili  @jiripetrlik

See https://issues.redhat.com/browse/DROOLS-5688

Changed PMMLRuntimeFactory to new public API

### CODE REVIEW

**Review by danielezonca — APPROVED** [review]
LGTM

**Review by jiripetrlik — APPROVED** [review]
LGTM

**Review by tteofili — APPROVED** [review]
LGTM

**Comment by mariofusco** [comment]
Included and replaced by https://github.com/kiegroup/kogito-apps/pull/507

**Pull request closed without merging**
