### PR TITLE
FAI-452: CF UI first version

### PR DESCRIPTION
**Pull request by kelvah**
Jira: https://issues.redhat.com/browse/FAI-452

First version of Counterfactual Explanations UI.

This feature is experimental and its UI is disabled by default by the env variable `KOGITO_TRUSTY_COUNTERFACTUAL`.

In order to test for this PR enter `export KOGITO_TRUSTY_COUNTERFACTUAL=enabled` in the CLI.

Then run `yarn run mock-server` and `yarn run start` in `ui-packages/packages/trusty`.
 
<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>Pull Request</b>  
  Please add comment: <b>Jenkins retest this</b>
 
* <b>Quarkus LTS checks</b>  
  Please add comment: <b>Jenkins run LTS</b>

* <b>Native checks</b>  
  Please add comment: <b>Jenkins run native</b>

</details>

### CODE REVIEW

**Review by manstis — APPROVED** [review]
Approving..

SonarCloud reports ~65% test coverage however:-
- This is experimental and is disabled
- We know a lot will be refactored when "Composite feature" support is added.
  See:
  - https://issues.redhat.com/browse/FAI-474
  - https://issues.redhat.com/browse/FAI-473
  - [JIRA TBE for UI changed]

@kelvah Is there already a JIRA for the UI changes for Composite inputs/goals?

**Review by danielezonca — APPROVED** [review]
LGTM, not doing a deep review considering that is the first version 👍

**Comment by kelvah** [comment]
@manstis I've created a JIRA for the support of composite feature in the UI: [FAI-590](https://issues.redhat.com/browse/FAI-590)

I've also improved the test coverage but sonar hasn't been automatically re-triggered :thinking:

**Comment by manstis** [comment]
@kelvah Jenkins seems to be chugging along nicely at the moment. AFAIK SonarCloud should follow completion of that step.

**Pull request merged**
