### PR TITLE
KOGITO-2941: Sonarcloud coverage report is not adding the react part

### PR DESCRIPTION
**Pull request by nmirasch**
Related jira: https://issues.redhat.com/browse/KOGITO-2941
Adds the test coverage when test are executed in ui-packages

### CODE REVIEW

**Comment by cristianonicolai** [comment]
@nmirasch I though` --coverage` would only print in the console the test coverage, if we actually need this, wouldn't be best to add `--coverage` to the default *test* execution?

**Comment by nmirasch** [comment]
@cristianonicolai I changed the default test script calling each package script including --coverage.
@jstastny-cz, Does this work? do we need that extra script to differentiate between 'test' and 'test with coverage' at ui-package level?

**Review by cristianonicolai — APPROVED** [review]

**Comment by jstastny-cz** [comment]
my concerns is that now `yarn test` invoked in top-level will behave differently from `yarn test` invoked in the package (e.g. common). So I would rather override `test` scripts in all packages and from lerna just invoke `test.

**Review by jstastny-cz — APPROVED** [review]
Solves our PR coverage reports, approving regardless my nitpick above.

**Comment by cristianonicolai** [comment]
> my concerns is that now `yarn test` invoked in top-level will behave differently from `yarn test` invoked in the package (e.g. common). So I would rather override `test` scripts in all packages and from lerna just invoke `test.

+1 I guess test command should include coverage by default in this case.

**Pull request merged**
