### PR TITLE
KOGITO-4443 - Set skipOriginalJarRename in quarkus apps

### PR DESCRIPTION
**Pull request by r00ta**
JIRA: https://issues.redhat.com/browse/KOGITO-4443

Specify skipOriginalJarRename in quarkus apps according to https://github.com/kiegroup/kogito-apps/pull/647#discussion_r576778802

Many thanks for submitting your Pull Request :heart:! 

Please make sure that your PR meets the following requirements:

- [x] You have read the [contributors guide](https://github.com/kiegroup/kogito-runtimes#contributing-to-kogito)
- [x] Pull Request title is properly formatted: `KOGITO-XYZ Subject`
- [x] Pull Request title contains the target branch if not targeting master: `[0.9.x] KOGITO-XYZ Subject`
- [x] Pull Request contains link to the JIRA issue
- [x] Pull Request contains link to any dependent or related Pull Request
- [x] Pull Request contains description of the issue
- [x] Pull Request does not include fixes for issues other than the main ticket

### CODE REVIEW

**Review by radtriste — APPROVED** [review]
Thx for quick action on that !

**Comment by radtriste** [comment]
I guess we should also cherry-pick to 1.3.x ...

**Review by danielezonca — APPROVED** [review]

**Comment by danielezonca** [comment]
> I guess we should also cherry-pick to 1.3.x ...

I agree @r00ta can you please cherry pick this PR to 1.3.x?

**Comment by r00ta** [comment]
Here it is https://github.com/kiegroup/kogito-apps/pull/650

**Pull request merged**
