### PR TITLE
Ignore DMN resources copied during build

### PR DESCRIPTION
**Pull request by cristianonicolai**

### CODE REVIEW

**Comment by cristianonicolai** [comment]
jenkins please retest this

**Comment by cristianonicolai** [comment]
jenkins please retest this

**Comment by mareknovotny** [comment]
jenkins retest this please

**Comment by radtriste** [comment]
Jenkins retest this

**Comment by cristianonicolai** [comment]
@danielezonca @r00ta fine with this?

**Review by danielezonca — APPROVED** [review]

**Pull request merged**
