### PR TITLE
[1.27.x] Bump Quarkus version to 2.7.6.Final

### PR DESCRIPTION
**Pull request by radtriste**
- https://github.com/kiegroup/kogito-pipelines/pull/623
- https://github.com/kiegroup/kogito-pipelines/pull/624
- https://github.com/kiegroup/drools/pull/4717
- https://github.com/kiegroup/kogito-runtimes/pull/2512
- https://github.com/kiegroup/kogito-apps/pull/1478
- https://github.com/kiegroup/kogito-examples/pull/1415
- https://github.com/kiegroup/kogito-docs/pull/216

### CODE REVIEW

**Review by cristianonicolai — APPROVED** [review]

**Comment by cristianonicolai** [comment]
jenkins please retest this

**Comment by radtriste** [comment]
> jenkins please retest this

There is no Jenkins run because it is only GHA changes here :)

**Comment by radtriste** [comment]
jenkins retest this

**Comment by radtriste** [comment]
waiting for https://github.com/kiegroup/kogito-apps/pull/1479

**Comment by radtriste** [comment]
jenkins rerun kogito-apps tests

**Comment by pefernan** [comment]
yay!

**Pull request merged**
