### PR TITLE
[KOGITO-2893] Update tests with 201 response code

### PR DESCRIPTION
**Pull request by ruromero**
Signed-off-by: ruromero <rromerom@redhat.com>

Fix https://issues.redhat.com/browse/KOGITO-2893
Follow up on kiegroup/kogito-runtimes#656

### CODE REVIEW

**Review by tiagodolphine — APPROVED** [review]

**Comment by ruromero** [comment]
jenkins retest this

**Comment by tiagodolphine** [comment]
jenkins retest this

**Comment by ruromero** [comment]
jenkins retest this

**Comment by ruromero** [comment]
jenkins retest this

**Comment by ruromero** [comment]
jenkins retest this

**Comment by ruromero** [comment]
jenkins retest this please

**Comment by ruromero** [comment]
jenkins retest this

**Review by cristianonicolai — APPROVED** [review]

**Pull request merged**
