### PR TITLE
[0.13.x] KOGITO-2922  Bump Infinispan to 11.0.1.Final

### PR DESCRIPTION
**Pull request by evacchi**
ensemble:
- https://github.com/kiegroup/kogito-runtimes/pull/672

### CODE REVIEW

**Comment by evacchi** [comment]
@cristianonicolai @tiagodolphine the queryFactory in org.kie.kogito.jobs.service.repository.infinispan.InfinispanJobRepository is deprecated, we need to take a look how to fix that. Apparently we should use Ickle. Don't know how much work that requires; anyway, problem for another day, I'll open a JIRA

**Comment by evacchi** [comment]
@radtriste not sure what's happening on CI here :thinking:

**Comment by evacchi** [comment]
jenkins please retest this

**Comment by radtriste** [comment]
@evacchi there was an update in shared libraries which makes multiple projects with same branch name to fai when you test all in one PR check. This is the update https://github.com/kiegroup/jenkins-pipeline-shared-libraries/blob/master/vars/githubscm.groovy.
I asked @Ginxo about that

**Comment by evacchi** [comment]
shall we rebase or...? @radtriste

**Comment by radtriste** [comment]
nope, this is a pipeline issue

**Comment by evacchi** [comment]
ok will wait thanks @radtriste

**Comment by evacchi** [comment]
jenkins please retest this

**Review by tiagodolphine — APPROVED** [review]
LGTM, @evacchi regarding the QueryBuilder it is deprecated indeed, we need to change it at some point to use Ickle query, I'll open a JIRA, it seems on data-index it is already using ickle @cristianonicolai , right?
thanks.

**Comment by evacchi** [comment]
@tiagodolphine apparently some tests are failing, but maybe I need to upgrade to Quarkus 1.7 together with this

**Pull request closed without merging**
