### PR TITLE
FAI-646: CF UI - Highlighted results columns transparent background

### PR DESCRIPTION
**Pull request by kelvah**
See: https://issues.redhat.com/browse/FAI-646

The background color animation to highlight new results columns is ending with a transparent background. When scrolling the table down, the scrolled content will be visible behind the table heading.

With this PR I've changed the ending background color to a full white.

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>Pull Request</b>  
  Please add comment: <b>Jenkins retest this</b>
 
* <b>Quarkus LTS checks</b>  
  Please add comment: <b>Jenkins run LTS</b>

* <b>Native checks</b>  
  Please add comment: <b>Jenkins run native</b>

</details>

### CODE REVIEW

**Review by manstis — APPROVED** [review]
Works well for me :+1: Thank-you.

**Comment by kelvah** [comment]
Jenkins retest this

**Comment by manstis** [comment]
@kelvah I think we can ignore SonarCloud's analysis of your PR!

**Review by sjamboro — APPROVED** [review]

**Comment by manstis** [comment]
Jenkins is green, SonarCloud needs a vacation and GH actions failed for something completely unrelated.

Given the change actually contained in this PR I'm pretty confident it can be merged.

**Pull request merged**
