### PR TITLE
KOGITO-6196 Review persistence model to handle Milestones with same i…

### PR DESCRIPTION
**Pull request by cristianonicolai**
…d for different process instances.

Assembly:
- https://github.com/kiegroup/kogito-apps/pull/1094
- https://github.com/kiegroup/kie-docs/pull/4042

### CODE REVIEW

**Review by radtriste — COMMENTED** [review]
will those changes be backward compatible with previous model ?

**Comment by radtriste** [comment]
could you also check the code smell reported by SonarCloud ? ;)

**Comment by cristianonicolai** [comment]
> will those changes be backward compatible with previous model ?

indeed not, it was quite a mess to be honest :/

**Review by nmirasch — APPROVED** [review]

**Comment by cristianonicolai** [comment]
jenkins please retest this

**Comment by cristianonicolai** [comment]
Jenkins rerun apps tests

**Comment by cristianonicolai** [comment]
Jenkins rerun apps tests

**Comment by cristianonicolai** [comment]
Jenkins rerun apps tests

**Comment by cristianonicolai** [comment]
jenkins please retest this

**Comment by radtriste** [comment]
> > will those changes be backward compatible with previous model ?
> 
> indeed not, it was quite a mess to be honest :/

Then we need to make sure it is properly documented

**Review by radtriste — APPROVED** [review]

**Comment by Scuilion** [comment]
This schema is so much easier to understand now! :tada:

**Pull request merged**
