### PR TITLE
[1.13.x] Bump Quarkus version to 2.13.4.Final (#1501)

### PR DESCRIPTION
**Pull request by cristianonicolai**
Assembly:
- https://github.com/kiegroup/kogito-runtimes/pull/2820
- https://github.com/kiegroup/kogito-apps/pull/1639
- https://github.com/kiegroup/kogito-examples/pull/1581
- https://github.com/kiegroup/optaplanner/pull/2639
- https://github.com/kiegroup/optaplanner-quickstarts/pull/522

### CODE REVIEW

**Comment by cristianonicolai** [comment]
jenkins please retest this

**Comment by cristianonicolai** [comment]
jenkins please retest this

**Comment by cristianonicolai** [comment]
jenkins please retest this

**Comment by radtriste** [comment]
jenkins retest this

**Comment by radtriste** [comment]
@cristianonicolai why do you need that one ?

**Review by radtriste — APPROVED** [review]

**Pull request merged**
