### PR TITLE
KOGITO-3681 Manually copy bpmn files to avoid duplication

### PR DESCRIPTION
**Pull request by cristianonicolai**
Assembly:
- https://github.com/kiegroup/kogito-runtimes/pull/842
- https://github.com/kiegroup/kogito-apps/pull/498

### CODE REVIEW

**Comment by cristianonicolai** [comment]
@tiagodolphine please take a look, I had to change the approach as somehow Quarkus compilation was picking up bpmn files twice, and so starting to complain that process id was duplicated.

**Review by tiagodolphine — APPROVED** [review]
+1 and I think this approach is fine and clear, copying the files directly from the FS instead of getting it from the jar dependency.

**Comment by cristianonicolai** [comment]
jenkins please retest this

**Comment by cristianonicolai** [comment]
jenkins please retest this

**Pull request merged**
