### PR TITLE
[kie-issues#843] Make Java binaries reproducible

### LINKED ISSUE #843: Reproducible Build: `kogito-apps` repo
As part of the Apache migration, after adding the required configurations, we need to fully enable the [Reproducible Build](https://maven.apache.org/guides/mini/guide-reproducible-builds.html) mechanism in `kogito-apps` repo

Current status: 
Screenshot 2024-01-19 at 16 06 57

### PR DESCRIPTION
**Pull request by baldimir**
Closes https://github.com/apache/incubator-kie-issues/issues/843

- Makes Java binaries in kogito-apps reproducible. 
- These PRs are required to be merged to make also apps-integration-tests modules reproducible: 
    - https://github.com/apache/incubator-kie-drools/pull/5676

### CODE REVIEW

**Review by mariofusco — APPROVED** [review]

**Review by ricardozanini — APPROVED** [review]

**Review by yesamer — APPROVED** [review]

**Comment by kie-ci3** [comment]
**PR job** `#1` was: **UNSTABLE**
Possible explanation: This should be test failures


<details>
<summary><b>Reproducer</b></summary>



build-chain build full_downstream  -f 'https://raw.githubusercontent.com/${AUTHOR:apache}/incubator-kie-kogito-pipelines/${BRANCH:main}/.ci/buildchain-config-pr-cdb.yaml' -o 'bc' -p apache/incubator-kie-kogito-apps -u https://github.com/apache/incubator-kie-kogito-apps/pull/1981 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-apps-pr/job/PR-1981/1/display/redirect

**Test results:**
- PASSED: 2856
- FAILED: 5

Those are the test failures: 
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-apps-pr/job/PR-1981/1/testReport/org.kie.kogito.index.infinispan/ProcessDataIndexInfinispanHttpIT/testProcessInstanceEvents/">org.kie.kogito.index.infinispan.ProcessDataIndexInfinispanHttpIT.testProcessInstanceEvents</a></summary>
1 expectation failed.<br/>JSON path errors doesn't match.<br/>Expected: null<br/>  Actual: <[{message=Exception while fetching data (/UserTaskInstanceCommentUpdate) : Index 0 out of bounds for length 0, locations=[{line=1, column=12}], path=[UserTaskInstanceCommentUpdate], extensions={classification=DataFetchingException}}]><br/>
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-apps-pr/job/PR-1981/1/testReport/org.kie.kogito.index.mongodb/ProcessDataIndexMongoDBHttpIT/testProcessInstanceEvents/">org.kie.kogito.index.mongodb.ProcessDataIndexMongoDBHttpIT.testProcessInstanceEvents</a></summary>
1 expectation failed.<br/>JSON path data.UserTaskInstances[0].potentialGroups[0] doesn't match.<br/>Expected: managers<br/>  Actual: null<br/>
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-apps-pr/job/PR-1981/1/testReport/org.kie.kogito.index.mongodb/ProcessDataIndexMongoDBKafkaIT/testProcessInstanceEvents/">org.kie.kogito.index.mongodb.ProcessDataIndexMongoDBKafkaIT.testProcessInstanceEvents</a></summary>
1 expectation failed.<br/>JSON path data.UserTaskInstances[0].potentialGroups[0] doesn't match.<br/>Expected: managers<br/>  Actual: null<br/>
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-apps-pr/job/PR-1981/1/testReport/org.kie.kogito.index.oracle/ProcessDataIndexOracleHttpIT/testProcessInstanceEvents/">org.kie.kogito.index.oracle.ProcessDataIndexOracleHttpIT.testProcessInstanceEvents</a></summary>
1 expectation failed.<br/>JSON path data.UserTaskInstances[0].potentialGroups[0] doesn't match.<br/>Expected: managers<br/>  Actual: null<br/>
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-apps-pr/job/PR-1981/1/testReport/org.kie.kogito.index/ProcessDataIndexMongoDBIT/testProcessInstanceEvents/">org.kie.kogito.index.ProcessDataIndexMongoDBIT.testProcessInstanceEvents</a></summary>
1 expectation failed.<br/>JSON path data.UserTaskInstances[0].potentialGroups[0] doesn't match.<br/>Expected: managers<br/>  Actual: null<br/>
</details>

**Review by pefernan — APPROVED** [review]

**Comment by yesamer** [comment]
@baldimir oh-ho, We have a conflict here!

**Comment by kie-ci3** [comment]
**PR job** `#2` was: **UNSTABLE**
Possible explanation: This should be test failures


<details>
<summary><b>Reproducer</b></summary>



build-chain build full_downstream  -f 'https://raw.githubusercontent.com/${AUTHOR:apache}/incubator-kie-kogito-pipelines/${BRANCH:main}/.ci/buildchain-config-pr-cdb.yaml' -o 'bc' -p apache/incubator-kie-kogito-apps -u https://github.com/apache/incubator-kie-kogito-apps/pull/1981 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-apps-pr/job/PR-1981/2/display/redirect

**Test results:**
- PASSED: 2815
- FAILED: 8

Those are the test failures: 
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-apps-pr/job/PR-1981/2/testReport/org.kie.kogito.index.infinispan/ProcessDataIndexInfinispanHttpIT/testProcessInstanceEvents/">org.kie.kogito.index.infinispan.ProcessDataIndexInfinispanHttpIT.testProcessInstanceEvents</a></summary>
1 expectation failed.<br/>JSON path data.UserTaskInstances[0].potentialGroups[0] doesn't match.<br/>Expected: managers<br/>  Actual: null<br/>
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-apps-pr/job/PR-1981/2/testReport/org.kie.kogito.index.infinispan/ProcessDataIndexInfinispanKafkaIT/testProcessInstanceEvents/">org.kie.kogito.index.infinispan.ProcessDataIndexInfinispanKafkaIT.testProcessInstanceEvents</a></summary>
1 expectation failed.<br/>Expected status code <201> but was <409>.<br/>
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-apps-pr/job/PR-1981/2/testReport/org.kie.kogito.index.mongodb/ProcessDataIndexMongoDBHttpIT/testProcessInstanceEvents/">org.kie.kogito.index.mongodb.ProcessDataIndexMongoDBHttpIT.testProcessInstanceEvents</a></summary>
1 expectation failed.<br/>Expected status code <201> but was <409>.<br/>
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-apps-pr/job/PR-1981/2/testReport/org.kie.kogito.index.mongodb/ProcessDataIndexMongoDBKafkaIT/testProcessInstanceEvents/">org.kie.kogito.index.mongodb.ProcessDataIndexMongoDBKafkaIT.testProcessInstanceEvents</a></summary>
1 expectation failed.<br/>Expected status code <201> but was <409>.<br/>
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-apps-pr/job/PR-1981/2/testReport/org.kie.kogito.index.postgresql/ProcessDataIndexPostgreSqlHttpIT/testProcessInstanceEvents/">org.kie.kogito.index.postgresql.ProcessDataIndexPostgreSqlHttpIT.testProcessInstanceEvents</a></summary>
1 expectation failed.<br/>Expected status code <201> but was <409>.<br/>
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-apps-pr/job/PR-1981/2/testReport/org.kie.kogito.index.postgresql/ProcessDataIndexPostgreSqlKafkaIT/testProcessInstanceEvents/">org.kie.kogito.index.postgresql.ProcessDataIndexPostgreSqlKafkaIT.testProcessInstanceEvents</a></summary>
1 expectation failed.<br/>Expected status code <201> but was <409>.<br/>
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-apps-pr/job/PR-1981/2/testReport/org.kie.kogito.index/ProcessDataIndexMongoDBIT/testProcessInstanceEvents/">org.kie.kogito.index.ProcessDataIndexMongoDBIT.testProcessInstanceEvents</a></summary>
1 expectation failed.<br/>JSON path data.UserTaskInstances[0].potentialGroups[0] doesn't match.<br/>Expected: managers<br/>  Actual: null<br/>
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-apps-pr/job/PR-1981/2/testReport/org.kie.kogito.index/ProcessDataIndexPostgreSqlIT/testProcessInstanceEvents/">org.kie.kogito.index.ProcessDataIndexPostgreSqlIT.testProcessInstanceEvents</a></summary>
1 expectation failed.<br/>Expected status code <201> but was <409>.<br/>
</details>

**Comment by kie-ci3** [comment]
**PR job** `#3` was: **UNSTABLE**
Possible explanation: This should be test failures


<details>
<summary><b>Reproducer</b></summary>



build-chain build full_downstream  -f 'https://raw.githubusercontent.com/${AUTHOR:apache}/incubator-kie-kogito-pipelines/${BRANCH:main}/.ci/buildchain-config-pr-cdb.yaml' -o 'bc' -p apache/incubator-kie-kogito-apps -u https://github.com/apache/incubator-kie-kogito-apps/pull/1981 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-apps-pr/job/PR-1981/3/display/redirect

**Test results:**
- PASSED: 2819
- FAILED: 4

Those are the test failures: 
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-apps-pr/job/PR-1981/3/testReport/org.kie.kogito.index.infinispan/ProcessDataIndexInfinispanHttpIT/testProcessInstanceEvents/">org.kie.kogito.index.infinispan.ProcessDataIndexInfinispanHttpIT.testProcessInstanceEvents</a></summary>
1 expectation failed.<br/>JSON path data.UserTaskInstances[0].potentialGroups[0] doesn't match.<br/>Expected: managers<br/>  Actual: null<br/>
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-apps-pr/job/PR-1981/3/testReport/org.kie.kogito.index.mongodb/ProcessDataIndexMongoDBHttpIT/testProcessInstanceEvents/">org.kie.kogito.index.mongodb.ProcessDataIndexMongoDBHttpIT.testProcessInstanceEvents</a></summary>
1 expectation failed.<br/>JSON path data.UserTaskInstances[0].potentialGroups[0] doesn't match.<br/>Expected: managers<br/>  Actual: null<br/>
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-apps-pr/job/PR-1981/3/testReport/org.kie.kogito.index.mongodb/ProcessDataIndexMongoDBKafkaIT/testProcessInstanceEvents/">org.kie.kogito.index.mongodb.ProcessDataIndexMongoDBKafkaIT.testProcessInstanceEvents</a></summary>
1 expectation failed.<br/>JSON path data.UserTaskInstances[0].potentialGroups[0] doesn't match.<br/>Expected: managers<br/>  Actual: null<br/>
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-apps-pr/job/PR-1981/3/testReport/org.kie.kogito.index/ProcessDataIndexMongoDBIT/testProcessInstanceEvents/">org.kie.kogito.index.ProcessDataIndexMongoDBIT.testProcessInstanceEvents</a></summary>
1 expectation failed.<br/>JSON path errors doesn't match.<br/>Expected: null<br/>  Actual: <[{message=Exception while fetching data (/UserTaskInstances[0]/schema) : Runtime service URL not defined, please review the kogito.service.url system property to point the public URL for this runtime., locations=[{line=1, column=85}], path=[UserTaskInstances, 0, schema], extensions={classification=DataFetchingException}}]><br/>
</details>

**Comment by baldimir** [comment]
The test failures are unrelated to my changes. Merging this.

**Pull request merged**
