### PR TITLE
FAI-695: Unify the root folder for Cypress tests

### PR DESCRIPTION
**Pull request by sjamboro**
See https://issues.redhat.com/browse/FAI-695.

Goal:
- rename the 'it-tests' folder to 'cypress'

Not goal:
- to run the `yarn test:e2e` script because we are preparing new approach. See https://github.com/kiegroup/kogito-apps/pull/1092

### CODE REVIEW

**Comment by jstastny-cz** [comment]
You could just extend what is being archived, you don't need to move from it-tests to cypress necessarily.

**Comment by sjamboro** [comment]
Jenkins retest this

**Comment by sjamboro** [comment]
> You could just extend what is being archived, you don't need to move from it-tests to cypress necessarily.

@jstastny-cz you are right but I saw that similar name is used for tasks and management-console and etc. So I would like to unify it.

**Comment by sjamboro** [comment]
@jstastny-cz @manstis can you approve these changes? Jenkins build success and it seems that GHA failed in `integration-tests-jobs-service`. In the GHA log I can see that the test suites at the new location were performed and succeed.

**Comment by sjamboro** [comment]
There could be a merge confict with https://github.com/kiegroup/kogito-apps/pull/1092/files (trusty package.json)

**Comment by sjamboro** [comment]
@ruivieira can you take a look at GHA? There is failing explainability test. 
```
kiegroup_kogito_apps/explainability/explainability-core/src/test/java/org/kie/kogito/explainability/local/counterfactual/CounterfactualExplainerTest.java:873 | org.opentest4j.AssertionFailedError: expected: <1> but was: <0> 
```
My changes should not cause it. I can confirm that the integration test suite (trusty in ui-packages) which folder has been renamed was performed without problems.

**Review by jstastny-cz — APPROVED** [review]
LGTM.

**Comment by sjamboro** [comment]
@kelvah can you review this PR?

**Comment by kie-ci1** [comment]
**(tests) - kogito-apps job** #585 was: **ABORTED**
Possible explanation: Most probably a timeout, please review


**Test results:**
- PASSED: 2402
- FAILED: 0

Those are the test failures: none

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-apps.tests.kogito-apps/585/display/redirect or see console log:
<details>
<summary><b>Console Logs</b></summary>
[2022-01-31T16:41:16.970Z] [INFO] --------------------------------[ jar ]---------------------------------<br/>[2022-01-31T16:41:16.970Z] [INFO] <br/>[2022-01-31T16:41:16.970Z] [INFO] --- maven-enforcer-plugin:3.0.0-M2:enforce (enforce-versions) @ trusty-storage-redis ---<br/>[2022-01-31T16:41:16.970Z] [INFO] Skipping Rule Enforcement.<br/>[2022-01-31T16:41:16.970Z] [INFO] <br/>[2022-01-31T16:41:16.970Z] [INFO] --- maven-enforcer-plugin:3.0.0-M2:enforce (enforce-java-version) @ trusty-storage-redis ---<br/>[2022-01-31T16:41:16.970Z] [INFO] Skipping Rule Enforcement.<br/>[2022-01-31T16:41:16.970Z] [INFO] <br/>[2022-01-31T16:41:16.970Z] [INFO] --- maven-enforcer-plugin:3.0.0-M2:enforce (enforce-maven-version) @ trusty-storage-redis ---<br/>[2022-01-31T16:41:16.970Z] [INFO] Skipping Rule Enforcement.<br/>[2022-01-31T16:41:16.970Z] [INFO] <br/>[2022-01-31T16:41:16.970Z] [INFO] --- maven-checkstyle-plugin:3.0.0:check (default) @ trusty-storage-redis ---<br/>[2022-01-31T16:41:16.970Z] [INFO] <br/>[2022-01-31T16:41:16.970Z] [INFO] --- maven-antrun-plugin:1.8:run (default) @ trusty-storage-redis ---<br/>[2022-01-31T16:41:16.970Z] [INFO] Executing tasks<br/>[2022-01-31T16:41:16.970Z] <br/>[2022-01-31T16:41:16.970Z] main:<br/>[2022-01-31T16:41:16.970Z]      [echo] Generating JaCoCo Reports<br/>[2022-01-31T16:41:16.970Z]     [mkdir] Created dir: /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-apps.tests.kogito-apps/bc/kiegroup_kogito_apps/kogito-apps/trusty/trusty-storage/trusty-storage-redis/target/site/jacoco<br/>[2022-01-31T16:41:16.970Z]    [report] Loading execution data file /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-apps.tests.kogito-apps/bc/kiegroup_kogito_apps/kogito-apps/target/jacoco.exec<br/>[2022-01-31T16:41:25.087Z]    [report] Writing bundle 'trusty-storage-redis' with 728 classes<br/>[2022-01-31T16:41:26.346Z] Cancelling nested steps due to timeout<br/>[2022-01-31T16:41:26.349Z] Sending interrupt signal to process<br/>[2022-01-31T16:41:27.020Z] + test 143 -eq 0<br/>[2022-01-31T16:41:27.028Z] script returned exit code 1<br/>[Pipeline] }<br/>[Pipeline] // withCredentials<br/>[Pipeline] }<br/>[Pipeline] // dir<br/>[Pipeline] }<br/>[Pipeline] // script<br/>[Pipeline] }<br/>[Pipeline] // withEnv<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (check space after build)<br/>Stage "check space after build" skipped due to earlier failure(s)<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Declarative: Post Actions)<br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] sh<br/>[2022-01-31T16:41:27.749Z] + wget --no-check-certificate -qO - https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-apps.tests.kogito-apps/585/api/json<br/>[Pipeline] readJSON<br/>[Pipeline] sh<br/>[2022-01-31T16:41:29.188Z] + wget --no-check-certificate -qO - https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-apps.tests.kogito-apps/585/consoleText<br/>[2022-01-31T16:41:29.188Z] + tail -n 50<br/>
</details>

**Review by kelvah — APPROVED** [review]

**Review by danielezonca — APPROVED** [review]

**Pull request merged**
