### PR TITLE
DROOLS-7130 Fix unresolved type exception inside kogito-apps/org.kie.kogito:jitexecutor-runner

### PR DESCRIPTION
**Pull request by baldimir**
Adding PMML implementation dependency to the jitexecutor project. This dependency is needed to fix the native build as the Efesto changes removed dependencies (probably transitive changes) to the PMML implementation.  

**referenced Pull Requests**: 
https://github.com/kiegroup/drools/pull/4658

<details>
<summary>
How to replicate CI configuration locally?
</summary>

Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use latest version of the code for each repository.
 
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you need to change multiple repositories and send multiple dependent pull requests related with a change you can easily reproduce the same build by executing it on Github hosted environment or locally in your development environment. See [local execution](https://github.com/kiegroup/github-action-build-chain#local-execution) details to get more information about it.
</details>

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

- for <b>pull request checks</b>  
  Please add comment: <b>Jenkins retest this</b>

- for a <b>specific pull request check</b>  
  Please add comment: <b>Jenkins (re)run [kogito-apps|kogito-examples] tests</b>

- for <b>quarkus branch checks</b>  
  Run checks against Quarkus current used branch  
  Please add comment: <b>Jenkins run quarkus-branch</b>

- for a <b>quarkus branch specific check</b>  
  Run checks against Quarkus current used branch  
  Please add comment: <b>Jenkins (re)run [kogito-apps|kogito-examples] quarkus-branch</b>

- for <b>quarkus main checks</b>  
  Run checks against Quarkus main branch  
  Please add comment: <b>Jenkins run quarkus-main</b>

- for a <b>specific quarkus main check</b>  
  Run checks against Quarkus main branch  
  Please add comment: <b>Jenkins (re)run [kogito-apps|kogito-examples] quarkus-branch</b>

- for <b>native checks</b>  
  Run native checks  
  Please add comment: <b>Jenkins run native</b>

- for a <b>specific native check</b>  
  Run native checks 
  Please add comment: <b>Jenkins (re)run [kogito-apps|kogito-examples] native</b>

- for <b>mandrel checks</b>  
  Run native checks against Mandrel image
  Please add comment: <b>Jenkins run mandrel</b>

- for a <b>specific mandrel check</b>  
  Run native checks against Mandrel image  
  Please add comment: <b>Jenkins (re)run [kogito-apps|kogito-examples] mandrel</b>

</details>

### CODE REVIEW

**Comment by baldimir** [comment]
Jenkins run native

**Review by gitgabrio — APPROVED** [review]
Hi @baldimir , thanks for the PR, LGTM!

**Review by tarilabs — COMMENTED** [review]
Hi @baldimir , as I tried to explain during our investigation session, I'm not sure this is the correct fix, as in my current understanding, this would bring the pmml compilers (and evaluators) in the JIT scope, and more specifically into the JIT DMN scope.

In other words, "before" it was something ~like this:

```
[INFO] +- org.kie:kie-pmml-evaluator-assembler:jar:8.26.0.Beta:compile
[INFO] |  +- org.kie:kie-pmml-evaluator-api:jar:8.26.0.Beta:compile
[INFO] |  |  +- org.kie:kie-pmml-api:jar:8.26.0.Beta:compile
[INFO] |  |  |  \- org.apache.commons:commons-math3:jar:3.4.1:compile
[INFO] |  |  \- org.kie:kie-pmml-commons:jar:8.26.0.Beta:compile
[INFO] |  |     \- org.apache.commons:commons-text:jar:1.9:compile
[INFO] |  +- org.kie:kie-pmml-evaluator-core:jar:8.26.0.Beta:compile
[INFO] |  +- org.kie:kie-pmml-compiler-core:jar:8.26.0.Beta:compile
[INFO] |  |  \- org.kie:kie-pmml-compiler-commons:jar:8.26.0.Beta:compile
[INFO] |  |     \- org.kie:kie-pmml-compiler-api:jar:8.26.0.Beta:compile
[INFO] |  |        \- org.glassfish.jaxb:jaxb-runtime:jar:2.3.3-b02:compile
[INFO] |  |           +- jakarta.xml.bind:jakarta.xml.bind-api:jar:2.3.3:compile
[INFO] |  |           +- org.glassfish.jaxb:txw2:jar:2.3.3-b02:compile
[INFO] |  |           \- com.sun.istack:istack-commons-runtime:jar:3.0.10:compile
[INFO] |  +- org.kie:kie-pmml-kie-internal:jar:8.26.0.Beta:compile
[INFO] |  +- org.kie:kie-internal:jar:8.26.0.Beta:compile
[INFO] |  +- org.drools:drools-compiler:jar:8.26.0.Beta:compile
[INFO] |  |  +- org.drools:drools-drl-parser:jar:8.26.0.Beta:compile
[INFO] |  |  +- org.drools:drools-drl-extensions:jar:8.26.0.Beta:compile
[INFO] |  |  +- org.drools:drools-drl-ast:jar:8.26.0.Beta:compile
[INFO] |  |  +- org.drools:drools-kiesession:jar:8.26.0.Beta:compile
[INFO] |  |  +- org.kie:kie-util-xml:jar:8.26.0.Beta:compile
[INFO] |  |  +- org.kie:kie-util-maven-support:jar:8.26.0.Beta:compile
[INFO] |  |  \- org.antlr:antlr-runtime:jar:3.5.2:compile
[INFO] |  +- org.drools:drools-core:jar:8.26.0.Beta:compile
[INFO] |  |  +- org.drools:drools-wiring-static:jar:8.26.0.Beta:compile
[INFO] |  |  +- org.drools:drools-io:jar:8.26.0.Beta:compile
[INFO] |  |  \- commons-codec:commons-codec:jar:1.15:compile
[INFO] |  +- org.drools:drools-canonical-model:jar:8.26.0.Beta:compile
[INFO] |  +- org.drools:drools-model-codegen:jar:8.26.0.Beta:compile
[INFO] |  |  +- org.drools:drools-codegen-common:jar:8.26.0.Beta:compile
[INFO] |  |  \- org.drools:drools-mvel-compiler:jar:8.26.0.Beta:compile
[INFO] |  +- org.drools:drools-ecj:jar:8.26.0.Beta:compile
[INFO] |  \- commons-io:commons-io:jar:2.11.0:compile
```

(notice no compilers for the models)

With this modification, "after" what is brought into scope is _this_:

```
[INFO] +- org.kie.kogito:kogito-pmml:jar:2.0.0-SNAPSHOT:compile
[INFO] |  +- org.kie.kogito:kogito-api:jar:2.0.0-SNAPSHOT:compile
[INFO] |  |  +- org.kie:kie-api:jar:8.27.0-SNAPSHOT:compile
[INFO] |  |  +- org.drools:drools-ruleunits-api:jar:8.27.0-SNAPSHOT:compile
[INFO] |  |  +- org.kie.kogito:kogito-timer:jar:2.0.0-SNAPSHOT:compile
[INFO] |  |  \- org.kie.kogito:kogito-pmml-api-dependencies:pom:2.0.0-SNAPSHOT:compile
[INFO] |  |     +- org.kie:kie-pmml-evaluator-api:jar:8.27.0-SNAPSHOT:compile
[INFO] |  |     \- org.kie:kie-pmml-commons:jar:8.27.0-SNAPSHOT:compile
[INFO] |  |        \- org.apache.commons:commons-text:jar:1.9:compile
[INFO] |  +- org.kie.kogito:kogito-drools:jar:2.0.0-SNAPSHOT:compile
[INFO] |  |  +- org.drools:drools-compiler:jar:8.27.0-SNAPSHOT:compile
[INFO] |  |  |  +- org.drools:drools-drl-parser:jar:8.27.0-SNAPSHOT:compile
[INFO] |  |  |  +- org.drools:drools-drl-extensions:jar:8.27.0-SNAPSHOT:compile
[INFO] |  |  |  +- org.drools:drools-drl-ast:jar:8.27.0-SNAPSHOT:compile
[INFO] |  |  |  +- org.drools:drools-kiesession:jar:8.27.0-SNAPSHOT:compile
[INFO] |  |  |  +- org.drools:drools-ecj:jar:8.27.0-SNAPSHOT:compile
[INFO] |  |  |  +- org.kie:kie-util-xml:jar:8.27.0-SNAPSHOT:compile
[INFO] |  |  |  +- org.kie:kie-util-maven-support:jar:8.27.0-SNAPSHOT:compile
[INFO] |  |  |  \- org.antlr:antlr-runtime:jar:3.5.2:compile
[INFO] |  |  +- org.drools:drools-ruleunits-impl:jar:8.27.0-SNAPSHOT:compile
[INFO] |  |  \- org.drools:drools-model-codegen:jar:8.27.0-SNAPSHOT:compile
[INFO] |  |     +- org.drools:drools-codegen-common:jar:8.27.0-SNAPSHOT:compile
[INFO] |  |     \- org.drools:drools-mvel-compiler:jar:8.27.0-SNAPSHOT:compile
[INFO] |  +- org.kie.kogito:kogito-pmml-dependencies:pom:2.0.0-SNAPSHOT:compile
[INFO] |  |  +- org.kie:kie-pmml-dependencies:jar:8.27.0-SNAPSHOT:compile
[INFO] |  |  |  +- org.kie:kie-pmml-api:jar:8.27.0-SNAPSHOT:compile
[INFO] |  |  |  |  \- org.apache.commons:commons-math3:jar:3.4.1:compile
[INFO] |  |  |  +- org.kie:kie-pmml-compiler-api:jar:8.27.0-SNAPSHOT:compile
[INFO] |  |  |  |  \- org.glassfish.jaxb:jaxb-runtime:jar:2.3.3-b02:compile
[INFO] |  |  |  |     +- jakarta.xml.bind:jakarta.xml.bind-api:jar:2.3.3:compile
[INFO] |  |  |  |     +- org.glassfish.jaxb:txw2:jar:2.3.3-b02:compile
[INFO] |  |  |  |     \- com.sun.istack:istack-commons-runtime:jar:3.0.10:compile
[INFO] |  |  |  +- org.kie:kie-pmml-compiler-core:jar:8.27.0-SNAPSHOT:compile
[INFO] |  |  |  +- org.kie:kie-pmml-compiler-commons:jar:8.27.0-SNAPSHOT:compile
[INFO] |  |  |  +- org.kie:kie-pmml-evaluator-core:jar:8.27.0-SNAPSHOT:compile
[INFO] |  |  |  +- org.kie:kie-pmml-evaluator-utils:jar:8.27.0-SNAPSHOT:compile
[INFO] |  |  |  +- org.kie:kie-pmml-models-drools-common:jar:8.27.0-SNAPSHOT:compile
[INFO] |  |  |  +- org.kie:kie-pmml-models-regression-model:jar:8.27.0-SNAPSHOT:compile
[INFO] |  |  |  +- org.kie:kie-pmml-models-regression-compiler:jar:8.27.0-SNAPSHOT:compile
[INFO] |  |  |  +- org.kie:kie-pmml-models-regression-evaluator:jar:8.27.0-SNAPSHOT:compile
[INFO] |  |  |  +- org.kie:kie-pmml-models-mining-model:jar:8.27.0-SNAPSHOT:compile
[INFO] |  |  |  +- org.kie:kie-pmml-models-mining-compiler:jar:8.27.0-SNAPSHOT:compile
[INFO] |  |  |  +- org.kie:kie-pmml-models-mining-evaluator:jar:8.27.0-SNAPSHOT:compile
[INFO] |  |  |  +- org.kie:kie-pmml-models-clustering-model:jar:8.27.0-SNAPSHOT:compile
[INFO] |  |  |  +- org.kie:kie-pmml-models-clustering-compiler:jar:8.27.0-SNAPSHOT:compile
[INFO] |  |  |  \- org.kie:kie-pmml-models-clustering-evaluator:jar:8.27.0-SNAPSHOT:compile
[INFO] |  |  +- org.kie:kie-pmml-models-drools-tree-model:jar:8.27.0-SNAPSHOT:compile
[INFO] |  |  +- org.kie:kie-pmml-models-drools-tree-compiler:jar:8.27.0-SNAPSHOT:compile
[INFO] |  |  +- org.kie:kie-pmml-models-drools-tree-evaluator:jar:8.27.0-SNAPSHOT:compile
[INFO] |  |  |  \- org.kie:kie-pmml-compiler-api:jar:tests:8.27.0-SNAPSHOT:test
[INFO] |  |  +- org.kie:kie-pmml-models-drools-scorecard-model:jar:8.27.0-SNAPSHOT:compile
[INFO] |  |  +- org.kie:kie-pmml-models-drools-scorecard-compiler:jar:8.27.0-SNAPSHOT:compile
[INFO] |  |  \- org.kie:kie-pmml-models-drools-scorecard-evaluator:jar:8.27.0-SNAPSHOT:compile
[INFO] |  +- org.kie.kogito:kogito-efesto-drl:pom:2.0.0-SNAPSHOT:compile
[INFO] |  |  +- org.kie:kie-drl-compilation-common:jar:8.27.0-SNAPSHOT:compile
[INFO] |  |  \- org.kie:kie-drl-map-input-runtime:jar:8.27.0-SNAPSHOT:compile
[INFO] |  |     \- org.kie:kie-drl-runtime-common:jar:8.27.0-SNAPSHOT:compile
[INFO] |  \- org.kie:efesto-dependencies:jar:8.27.0-SNAPSHOT:compile
[INFO] |     +- org.kie:efesto-common-utils:jar:8.27.0-SNAPSHOT:compile
[INFO] |     +- org.kie:efesto-common-api:jar:8.27.0-SNAPSHOT:compile
[INFO] |     +- org.kie:efesto-compilation-manager-api:jar:8.27.0-SNAPSHOT:compile
[INFO] |     +- org.kie:efesto-compilation-manager-core:jar:8.27.0-SNAPSHOT:compile
[INFO] |     +- org.kie:efesto-runtime-manager-api:jar:8.27.0-SNAPSHOT:compile
[INFO] |     \- org.kie:efesto-runtime-manager-core:jar:8.27.0-SNAPSHOT:compile
```

My doubts are specifically pertaining to all `models-<model>-compiler`s, which in my _current understanding_ (but happy to be demonstrated differently) are not validated in a JIT scenario.

So in summary I have these doubts as anticipated in during the support activities I've tried at my best during the investigation:
- in my _current understanding_ some of these dependencies are not validated into a JIT scenario (as it would be executable model _compiler_ for instance), so they shouldn't be part of the final binary artifact
- to my knowledge there is no validated JIT scenario for PMML, so while still not wired up for JIT this would however only cover only for the supported type of models from the chosen implementation (expected) without however a solution for a pluggable integration
- the implications/impact on the final binary artifact (eg: compilation time, size, etc.) are out of my assessment radar

👉**To avoid potential misunderstanding**👉 I'm not _against_ this solution, I just believe (as I've tried to explain) there are alternatives which have been preferable, such as adopt similar strategy as what was used in kogito runtimes for analogous cases, guarding the code analysis.

Alternatively, rather than binding this inside `jitexecutor-dmn`, could this be bound directly inside the `jitexecutor-runner`? But in this alternative (as well for the current status of the PR) my 3 doubts listed above still holds.

I really hope this helps in a constructive way 🤓 
/cc @danielezonca

**Comment by baldimir** [comment]
Ok Matteo, I will try to find out if some reduced set of dependencies work for this.

**Comment by gitgabrio** [comment]
@danielezonca @baldimir @tarilabs 
I'm looking at that jitexecutor-dm/jitexecutor-runner. From the Readme it seems that the use case is to 1) send a dmn 2) execute it on the fly. I can not understand how this would work when a DMN refers to a PMML. In that case, the PMML model should be sent and compiled. And for the compilation to work, the compiler modules are needed.
Has ever been tested this use case ? Otherwise, I have the impression this has always been broken e no-one ever knows.
@baldimir please suspend experiments until this is clarified, and please involve me in any discussion about it, thanks!

**Comment by danielezonca** [comment]
> @danielezonca @baldimir @tarilabs I'm looking at that jitexecutor-dm/jitexecutor-runner. From the Readme it seems that the use case is to 1) send a dmn 2) execute it on the fly. I can not understand how this would work when a DMN refers to a PMML. In that case, the PMML model should be sent and compiled. And for the compilation to work, the compiler modules are needed. Has ever been tested this use case ? Otherwise, I have the impression this has always been broken e no-one ever knows. @baldimir please suspend experiments until this is clarified, and please involve me in any discussion about it, thanks!

As far as I know DMN + PMML execution is excluded (or at least not tested) in the jitexecutor so this codepath is not expected to work.
Btw it should be possible to execute a DMN via jitexecutor without the need to add PMML impl dependencies

**Comment by gitgabrio** [comment]
> > @danielezonca @baldimir @tarilabs I'm looking at that jitexecutor-dm/jitexecutor-runner. From the Readme it seems that the use case is to 1) send a dmn 2) execute it on the fly. I can not understand how this would work when a DMN refers to a PMML. In that case, the PMML model should be sent and compiled. And for the compilation to work, the compiler modules are needed. Has ever been tested this use case ? Otherwise, I have the impression this has always been broken e no-one ever knows. @baldimir please suspend experiments until this is clarified, and please involve me in any discussion about it, thanks!
> 
> As far as I know DMN + PMML execution is excluded (or at least not tested) in the jitexecutor so this codepath is not expected to work. Btw it should be possible to execute a DMN via jitexecutor without the need to add PMML impl dependencies

Overall, this is also my impression. So, the required fix here is different and more radical, i.e. completely remove direct dependency, inside dmn, from pmml modules. This, in turn, would need to write some efesto-specific classes inside kie-dmn-core, and register them for reflection inside kie-dmn-core' reflect-config.json.
Modify that file broke some tests, because it refers to classes that are in a different module and those tests verify an absolute identity from the classes in the different module (kie-dmn-feel) and the ones declared in the kie-dmn-core' reflect-config.json. 

About: ` Btw it should be possible to execute a DMN via jitexecutor without the need to add PMML impl dependencies`: I'm not sure if we are saying the same thing: if  DMN refers to a PMML, it must have a dependency (at least during execution) to PMML implementations (kie-pmml-trusty or jpmml, it does not matter). In that specific case, if there is a choice to never allow that path, then I agree that we have to remove any pmml dependency.

**Comment by tarilabs** [comment]
As I tried to explain in https://github.com/kiegroup/kogito-apps/pull/1452#pullrequestreview-1095293350, to my knowledge there was not, and there is currently no functional requirement / validated requirement to have a DMN+PMML evaluation in a jitrunner scenario (or for a PMML evaluation alone for that matter).

I hope comment by Daniele https://github.com/kiegroup/kogito-apps/pull/1452#issuecomment-1236848667 gives the confirmation you might have been looking for.

For completeness, reiterating based on my current understanding a native image jitexecution evaluation of PMML (incl. DMN->PMML) is not technically feasible, analogously for a DRL to be evaluated going through an executable model route. Happy to be demonstrated otherwise, if advancements in the native image platform do allow for a solution in this (niche?) space.
If confirmed, an alternative potential solution there, as I mentioned also to Kogito Tooling team in the past, would be to consider a jpackage route.

Hope this helps!

**Comment by gitgabrio** [comment]
> As I tried to explain in [#1452 (review)](https://github.com/kiegroup/kogito-apps/pull/1452#pullrequestreview-1095293350), to my knowledge there was not, and there is currently no functional requirement / validated requirement to have a DMN+PMML evaluation in a jitrunner scenario (or for a PMML evaluation alone for that matter).
> 
> I hope comment by Daniele [#1452 (comment)](https://github.com/kiegroup/kogito-apps/pull/1452#issuecomment-1236848667) gives the confirmation you might have been looking for.
> 
> For completeness, reiterating based on my current understanding a native image jitexecution evaluation of PMML (incl. DMN->PMML) is not technically feasible, analogously for a DRL to be evaluated going through an executable model route. Happy to be demonstrated otherwise, if advancements in the native image platform do allow for a solution in this (niche?) space. If confirmed, an alternative potential solution there, as I mentioned also to Kogito Tooling team in the past, would be to consider a jpackage route.
> 
> Hope this helps!

Yes @tarilabs, thanks,  it helps to understand the situation and clarify the goal. As I wrote above, this means that the fix is slightly more radical, but much cleaner. The only slight issue is about that reflect-config.json - i.e. just to decide if modify the existing one, and adapt tests and logic, or create a new one. This is your choice, I would like to have a call on that so to better understand pros/cons and alternatives. With a clear global picture, it would be easy to finally made the fix. 
@baldimir @danielezonca It does not really matter who will write the actual code and how, what is really important is to understand the required approach.

**Comment by tarilabs** [comment]
> The only slight issue is about that reflect-config.json - i.e. just to decide if modify the existing one, and adapt tests and logic, or create a new one. This is your choice, I would like to have a call on that so to better understand pros/cons and alternatives. With a clear global picture, it would be easy to finally made the fix. 

I don't think it's my choice at all, during support session with @baldimir I've explained an alternative solution based on code guarding as referenced earlier and as similarly done in the past for kogito runtimes, which should equivalently solve.

I'm always available to explain in more details as preferred/needed, hope this helps!

**Comment by gitgabrio** [comment]
> native image jitexecution evaluation of PMML (incl. DMN->PMML) is not technically feasible, analogously for a DRL to be evaluated going through an executable model route.

@tarilabs just to understand that better because it is an interesting matter for me: why do you say so ? Is that because both drl and pmml requires a "compilation" ? Said differently: if they would use only already existing classes, without code-generation,  could they work ?

**Comment by gitgabrio** [comment]
> I don't think it's my choice at all, during support session with @baldimir I've explained an alternative solution based on code guarding as referenced earlier and as similarly done in the past for kogito runtimes, which should equivalently solve.
> 
> I'm always available to explain in more details as preferred/needed, hope this helps!

Thanks @tarilabs : alas, I don't know what you discussed with @baldimir, so I can't say exactly. I read your suggestion on the twin PR, but it is not clear to me and I would appreciate an explanation: efesto dtos are already "marker" interfaces, but that does not help, AFAIK. 
Last, my idea (what has been done in all other efesto plugins) is to write reflect-json for any plugin-specific implementation of the efesto interfaces, where they are implemented. 
In the case of dmn, that can't be done easily because it would mean to modify the already existing reflect-config file, and that would break the existing tests. So, I was asking your preference on how to deal with that

**Comment by baldimir** [comment]
Closing based on the discussion. The solution should be discussed tomorrow.

**Pull request closed without merging**
