### PR TITLE
KOGITO-2690 Task details redesign

### PR DESCRIPTION
**Pull request by AjayJagan**
Many thanks for submitting your Pull Request :heart:! 

Description: This pr adds the details as a drawer to the taskdetails page.

JIRA: https://issues.redhat.com/browse/KOGITO-2690

### CODE REVIEW

**Comment by AjayJagan** [comment]
jenkins please retest this

**Review by pefernan — CHANGES_REQUESTED** [review]
@AjayJagan on TaskDetails.test.tsx there's an unused import (lodash), a part from that everythign else is fine.

Thanks!

**Review by pefernan — APPROVED** [review]
Thanks @AjayJagan! +1

**Review by jstastny-cz — APPROVED** [review]
LGTM

**Pull request merged**
