### PR TITLE
KOGITO-2316 Expose the task endpoint on GraphQL

### PR DESCRIPTION
**Pull request by cristianonicolai**
Depends on https://github.com/kiegroup/kogito-runtimes/pull/640

### CODE REVIEW

**Review by pefernan — APPROVED** [review]
Yay thanks!

**Comment by pefernan** [comment]
@cristianonicolai could you please rebase?

**Comment by cristianonicolai** [comment]
@pefernan done

**Review by tiagodolphine — APPROVED** [review]
LGTM

**Pull request merged**
