### PR TITLE
FAI-440: CF: TrustyService endpoint for CF resultsets

### PR DESCRIPTION
**Pull request by manstis**
See https://issues.redhat.com/browse/FAI-440

This PR exposes a REST end-point for use from the UI. 

Many thanks for submitting your Pull Request :heart:! 

Please make sure that your PR meets the following requirements:

- [x] You have read the [contributors guide](https://github.com/kiegroup/kogito-runtimes#contributing-to-kogito)
- [x] Pull Request title is properly formatted: `KOGITO-XYZ Subject`
- [x] Pull Request title contains the target branch if not targeting master: `[0.9.x] KOGITO-XYZ Subject`
- [x] Pull Request contains link to the JIRA issue
- [x] Pull Request contains link to any dependent or related Pull Request
- [x] Pull Request contains description of the issue
- [x] Pull Request does not include fixes for issues other than the main ticket

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>Pull Request</b>  
  Please add comment: <b>Jenkins retest this</b>
 
* <b>Quarkus LTS checks</b>  
  Please add comment: <b>Jenkins run LTS</b>

* <b>Native checks</b>  
  Please add comment: <b>Jenkins run native</b>

</details>

### CODE REVIEW

**Comment by manstis** [comment]
Jenkins retest this

**Comment by manstis** [comment]
@ruivieira @danielezonca @r00ta @jiripetrlik This PR is now ready for review too.

**Comment by manstis** [comment]
Jenkins retest this

**Review by danielezonca — APPROVED** [review]

**Review by ruivieira — APPROVED** [review]
lgtm, thanks @manstis

**Comment by manstis** [comment]
Jenkins retest this

**Comment by manstis** [comment]
Jenkins retest this

**Comment by manstis** [comment]
Jenkins retest this

**Comment by manstis** [comment]
Jenkins retest this

**Review by r00ta — APPROVED** [review]
Nice work! LGTM

**Comment by manstis** [comment]
Jenkins retest this

**Comment by manstis** [comment]
Jenkins retest this

**Comment by manstis** [comment]
Jenkins retest this

**Comment by manstis** [comment]
@jiripetrlik Could you please try to take a look so we can get this merged this week?

**Comment by manstis** [comment]
Jenkins retest this

**Comment by manstis** [comment]
Jenkins retest this

**Comment by manstis** [comment]
Build timeout exceeded... trying again.

**Review by jiripetrlik — APPROVED** [review]
LGTM

**Comment by danielezonca** [comment]
Flaky test MatrixUtilsTest.testSecureJitterInvert(MatrixUtilsTest.java:462
org.opentest4j.AssertionFailedError: array contents differ at index [1], expected: <1.430511474609375E-6> but was: <0.0>
https://issues.redhat.com/browse/KOGITO-5172

Rerun but we can merge

jenkins retest this please

**Pull request merged**
