### PR TITLE
FAI-455: Configurable counterfactual producer in explainability service

### PR DESCRIPTION
**Pull request by ruivieira**
[FAI-455](https://issues.redhat.com/browse/FAI-455):

Add ability to the `CounterfactualExplainerProducer` to specify a maximum running time for the `CounterfactualExplainer`.
The configuration can be made with the `trusty.explainability.counterfactuals.maxRunningTimeSeconds` in the properties file and the default value is 60 seconds.

> Many thanks for submitting your Pull Request :heart:! 
> 
> Please make sure that your PR meets the following requirements:
> 
> - [x] You have read the [contributors guide](https://github.com/kiegroup/kogito-runtimes#contributing-to-kogito)
> - [x] Pull Request title is properly formatted: `KOGITO-XYZ Subject`
> - [ ] Pull Request title contains the target branch if not targeting master: `[0.9.x] KOGITO-XYZ Subject`
> - [x] Pull Request contains link to the JIRA issue
> - [x] Pull Request contains link to any dependent or related Pull Request
> - [x] Pull Request contains description of the issue
> - [x] Pull Request does not include fixes for issues other than the main ticket

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>Pull Request</b>  
  Please add comment: <b>Jenkins retest this</b>
 
* <b>Quarkus LTS checks</b>  
  Please add comment: <b>Jenkins run LTS</b>

* <b>Native checks</b>  
  Please add comment: <b>Jenkins run native</b>

</details>

### CODE REVIEW

**Review by manstis — APPROVED** [review]
LGTM (date in test header is wrong; but I can live with that).

**Comment by ruivieira** [comment]
Jenkins retest this please

**Review by jiripetrlik — APPROVED** [review]

**Comment by manstis** [comment]
@ruivieira you might need to rebase.. there was a fix to a UI test earlier today that had been failing.

**Comment by ruivieira** [comment]
> @ruivieira you might need to rebase.. there was a fix to a UI test earlier today that had been failing.

Thanks @manstis, done.

**Review by r00ta — APPROVED** [review]

**Review by danielezonca — APPROVED** [review]

**Pull request merged**
