### PR TITLE
FAI-444 Outcomes with null values are not managed

### PR DESCRIPTION
**Pull request by kelvah**
JIRA ticket: https://issues.redhat.com/browse/FAI-444

This PR adds handling of outcomes with null values (and does the same for inputs).

While updating tests I also found some ts errors on other unrelated tests that I fixed too.

### CODE REVIEW

**Review by manstis — APPROVED** [review]
Thank-you @kelvah LGTM.

**Comment by manstis** [comment]
@kelvah @r00ta I'm just joining the dots here..

I _think_ one of your two PRs will need revising depending on whose is merged first: #730 #724

I'm not sure either will lead to a merge conflict so just a heads up.

**Comment by r00ta** [comment]
> @kelvah @r00ta I'm just joining the dots here..
> 
> I _think_ one of your two PRs will need revising depending on whose is merged first: #730 #724
> 
> I'm not sure either will lead to a merge conflict so just a heads up.

Hi @manstis , I might be missing something, but as far as I can see there should be no conflict. My refactoring is not changing the API (the UI is properly ignoring additional/unknown properties in the response). Is this correct @kelvah ?

**Comment by kelvah** [comment]
That's correct @r00ta.

**Comment by manstis** [comment]
I don't think there will be a merge conflict either; which possibly makes it even more important to monitor.

@r00ta changes some of the field names in the JSON response, that might need updating in this PR to match?

If I am completely wrong; forgive me :-)

**Comment by manstis** [comment]
I don't think there will be a merge conflict either; which possibly makes it even more important to monitor.

@r00ta changes some of the field names in the JSON response, that might need updating in this PR to match?

If I am completely wrong; forgive me :-)

**Comment by r00ta** [comment]
> I don't think there will be a merge conflict either; which possibly makes it even more important to monitor.
> 
> @r00ta changes some of the field names in the JSON response, that might need updating in this PR to match?
> 
> If I am completely wrong; forgive me :-)

@manstis I kept the same response stuctures with my refactoring. In only one endpoint there is an additional property but this is not going to break the consumers (like the UI) since they do ignore unknown properties.
We *should* be ok :)

**Comment by kelvah** [comment]
Jenkins retest this please

**Comment by jstastny-cz** [comment]
I'm not able to review in timely manner, removing myself as a reviewer, please assess if you want to replace me with someone else (regardless their role in the team).

**Comment by kelvah** [comment]
hi @tomasdavidorg, is it OK if I add you as reviewer for this PR (and eventually to other ones needing a QA review)?

**Comment by tomasdavidorg** [comment]
Hi @kelvah, @sjamboro will take a look. Thanks 🙂

**Comment by sjamboro** [comment]
@kelvah do you know why these suites are failing?
- Kogito Apps :: Integration Tests :: Jobs Service :: Quarkus
- Kogito Apps :: Integration Tests :: Data Index :: Quarkus

**Comment by kelvah** [comment]
@sjamboro I didn't investigate it much because I don't think it's related to the changes in this PR. I was waiting to get all the reviews (and eventually commit further changes) before taking care of them.

**Review by sjamboro — APPROVED** [review]

**Comment by kelvah** [comment]
Jenkins retest this please

**Comment by kelvah** [comment]
Jenkins retest this please

**Comment by kelvah** [comment]
Jenkins retest this please

**Comment by kelvah** [comment]
Jenkins retest this please

**Pull request merged**
