### PR TITLE
FAI-637: CF UI: Handle Explainer limitations: Updated narrative

### PR DESCRIPTION
**Pull request by manstis**
See https://issues.redhat.com/browse/FAI-637

This PR updates the text shown in the UI for counterfactuals.

It also addresses a comment made that we should be using sentence case and not camel case.

Many thanks for submitting your Pull Request :heart:! 

Please make sure that your PR meets the following requirements:

- [ ] You have read the [contributors guide](https://github.com/kiegroup/kogito-runtimes#contributing-to-kogito)
- [ ] Pull Request title is properly formatted: `KOGITO-XYZ Subject`
- [ ] Pull Request title contains the target branch if not targeting main: `[0.9.x] KOGITO-XYZ Subject`
- [ ] Pull Request contains link to the JIRA issue
- [ ] Pull Request contains link to any dependent or related Pull Request
- [ ] Pull Request contains description of the issue
- [ ] Pull Request does not include fixes for issues other than the main ticket

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>Pull Request</b>  
  Please add comment: <b>Jenkins retest this</b>
 
* <b>Quarkus LTS checks</b>  
  Please add comment: <b>Jenkins run LTS</b>

* <b>Native checks</b>  
  Please add comment: <b>Jenkins run native</b>

</details>

### CODE REVIEW

**Comment by manstis** [comment]
@kelvah snapshots updated for new texts.

@sjamboro I've checked integration tests still pass.

**Review by kelvah — APPROVED** [review]
LGTM

**Comment by sjamboro** [comment]
@manstis Can you change "Audit Investigation", "Outcome Details", "Input Data", "Model Lookup" labels in TrafficViolation.ts (See links below)? Otherwise I will reflected these changes in new JIRA. 
https://github.com/manstis/kogito-apps/blob/FAI-637/ui-packages/packages/trusty/it-tests/e2e/TrafficViolation.ts#L72
https://github.com/manstis/kogito-apps/blob/FAI-637/ui-packages/packages/trusty/it-tests/e2e/TrafficViolation.ts#L94
https://github.com/manstis/kogito-apps/blob/FAI-637/ui-packages/packages/trusty/it-tests/e2e/TrafficViolation.ts#L95
https://github.com/manstis/kogito-apps/blob/FAI-637/ui-packages/packages/trusty/it-tests/e2e/TrafficViolation.ts#L96

In case that you want to run TrafficViolation.ts locally follow these steps:
https://github.com/manstis/kogito-apps/tree/FAI-637/ui-packages/packages/trusty/it-tests#run-integration-tests-with-real-data

**Review by sjamboro — APPROVED** [review]

**Comment by manstis** [comment]
Thank-you @sjamboro.

I've corrected the e2e tests in this PR (and can confirm they completed successfully locally).

**Review by sjamboro — APPROVED** [review]

**Comment by sjamboro** [comment]
@manstis thank you.

**Comment by manstis** [comment]
Jenkins retest this

**Pull request merged**
