### PR TITLE
[KOGITO-1559] MongoDB for Data Index service

### PR DESCRIPTION
**Pull request by xieshenzh**
Jira: https://issues.redhat.com/browse/KOGITO-1559

Description: support MongoDB as storage solution for data index.

Many thanks for submitting your Pull Request :heart:! 

Please make sure that your PR meets the following requirements:

- [x] You have read the [contributors guide](https://github.com/kiegroup/kogito-runtimes#contributing-to-kogito)
- [x] Pull Request title is properly formatted: `KOGITO-XYZ Subject`
- [ ] Pull Request title contains the target branch if not targeting master: `[0.9.x] KOGITO-XYZ Subject`
- [x] Pull Request contains link to the JIRA issue
- [x] Pull Request contains link to any dependent or related Pull Request
- [x] Pull Request contains description of the issue
- [x] Pull Request does not include fixes for issues other than the main ticket

### CODE REVIEW

**Comment by xieshenzh** [comment]
Assembly:
https://github.com/kiegroup/kogito-runtimes/pull/487
#205

**Comment by xieshenzh** [comment]
Pull request for runtime: https://github.com/kiegroup/kogito-runtimes/pull/487

**Comment by xieshenzh** [comment]
@rhtevan @bmozaffa Pull request submitted.

**Review by ricardozanini — CHANGES_REQUESTED** [review]
We need further discussions with the community on this topic before merging it.

**Comment by xieshenzh** [comment]
Close the RP for now. Will discuss with the community first.

**Pull request closed without merging**
