### PR TITLE
NO_ISSUE: use release shared library

### PR DESCRIPTION
**Pull request by jstastny-cz**
Depends on:
* apache/incubator-kie-kogito-pipelines#1206

Where `release` share pipeline library was added with gpg specific methods to import keys,etc.

### CODE REVIEW

**Review by rodrigonull — APPROVED** [review]
LGTM.

**Comment by kie-ci3** [comment]
**PR job** `#1` was: **UNSTABLE**
Possible explanation: This should be test failures


<details>
<summary><b>Reproducer</b></summary>



build-chain build full_downstream  -f 'https://raw.githubusercontent.com/${AUTHOR:apache}/incubator-kie-kogito-pipelines/${BRANCH:main}/.ci/buildchain-config-pr-cdb.yaml' -o 'bc' -p apache/incubator-kie-kogito-apps -u https://github.com/apache/incubator-kie-kogito-apps/pull/2064 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-apps-pr/job/PR-2064/1/display/redirect

**Test results:**
- PASSED: 1613
- FAILED: 1

Those are the test failures: 
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-apps-pr/job/PR-2064/1/testReport/org.kie.kogito.jobs.embedded/EmbeddedJobsServiceTest/testJobService/">org.kie.kogito.jobs.embedded.EmbeddedJobsServiceTest.testJobService</a></summary>
java.util.ConcurrentModificationException<br/>	at java.base/java.util.ArrayList.forEach(ArrayList.java:1513)<br/>	at org.kie.kogito.jobs.embedded.EmbeddedJobsServiceTest.testJobService(EmbeddedJobsServiceTest.java:99)<br/>	at java.base/java.lang.reflect.Method.invoke(Method.java:568)<br/>	at io.quarkus.test.junit.QuarkusTestExtension.runExtensionMethod(QuarkusTestExtension.java:1013)<br/>	at io.quarkus.test.junit.QuarkusTestExtension.interceptTestMethod(QuarkusTestExtension.java:827)<br/>	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)<br/>	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)<br/>
</details>

**Comment by kie-ci3** [comment]
**PR job** `#2` was: **UNSTABLE**
Possible explanation: This should be test failures


<details>
<summary><b>Reproducer</b></summary>



build-chain build full_downstream  -f 'https://raw.githubusercontent.com/${AUTHOR:apache}/incubator-kie-kogito-pipelines/${BRANCH:main}/.ci/buildchain-config-pr-cdb.yaml' -o 'bc' -p apache/incubator-kie-kogito-apps -u https://github.com/apache/incubator-kie-kogito-apps/pull/2064 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://ci-builds.apache.org/job/KIE/job/kogito/job/apache_migration/job/pullrequest_jobs/job/kogito-apps-pr/job/PR-2064/2/display/redirect

**Test results:**
- PASSED: 558
- FAILED: 1

Those are the test failures: 
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/apache_migration/job/pullrequest_jobs/job/kogito-apps-pr/job/PR-2064/2/testReport/org.kie.kogito.jobs.service.management/JobServiceInstanceManagerTest/heartbeatLeader/">org.kie.kogito.jobs.service.management.JobServiceInstanceManagerTest.heartbeatLeader</a></summary>
<br/>repository.heartbeat(<br/>    JobServiceManagementInfo[id=null, lastHeartbeat=2024-05-29T07:41:15.774Z, token=a6bef71b-eff9-4b44-87ef-eb692fdbf0db]<br/>);<br/>Wanted 1 time:<br/>-> at org.kie.kogito.jobs.service.repository.impl.DefaultJobServiceManagementRepository.heartbeat(DefaultJobServiceManagementRepository.java:52)<br/>But was 2 times:<br/>-> at org.kie.kogito.jobs.service.management.JobServiceInstanceManager.heartbeat(JobServiceInstanceManager.java:186)<br/>-> at org.kie.kogito.jobs.service.management.JobServiceInstanceManager.heartbeat(JobServiceInstanceManager.java:186)<br/><br/>
</details>

**Comment by kie-ci3** [comment]
**PR job** `#5` was: **UNSTABLE**
Possible explanation: This should be test failures


<details>
<summary><b>Reproducer</b></summary>



build-chain build full_downstream  -f 'https://raw.githubusercontent.com/${AUTHOR:apache}/incubator-kie-kogito-pipelines/${BRANCH:main}/.ci/buildchain-config-pr-cdb.yaml' -o 'bc' -p apache/incubator-kie-kogito-apps -u https://github.com/apache/incubator-kie-kogito-apps/pull/2064 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://ci-builds.apache.org/job/KIE/job/kogito/job/apache_migration/job/pullrequest_jobs/job/kogito-apps-pr/job/PR-2064/5/display/redirect

**Test results:**
- PASSED: 1664
- FAILED: 1

Those are the test failures: 
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/apache_migration/job/pullrequest_jobs/job/kogito-apps-pr/job/PR-2064/5/testReport/org.kie.kogito.index/ProcessDataIndexMongoDBIT/testProcessInstanceEvents/">org.kie.kogito.index.ProcessDataIndexMongoDBIT.testProcessInstanceEvents</a></summary>
1 expectation failed.<br/>JSON path errors doesn't match.<br/>Expected: null<br/>  Actual: <[{message=Exception while fetching data (/UserTaskInstances[0]/schema) : Runtime service URL not defined, please review the kogito.service.url system property to point the public URL for this runtime., locations=[{line=1, column=85}], path=[UserTaskInstances, 0, schema], extensions={classification=DataFetchingException}}]><br/>
</details>

**Pull request merged**
