### PR TITLE
FAI-675: Outcome influencing inputs are not present on the UI

### PR DESCRIPTION
**Pull request by manstis**
See https://issues.redhat.com/browse/FAI-675

Many thanks for submitting your Pull Request :heart:! 

Please make sure that your PR meets the following requirements:

- [x] You have read the [contributors guide](https://github.com/kiegroup/kogito-runtimes#contributing-to-kogito)
- [x] Pull Request title is properly formatted: `KOGITO-XYZ Subject`
- [x] Pull Request title contains the target branch if not targeting main: `[0.9.x] KOGITO-XYZ Subject`
- [x] Pull Request contains link to the JIRA issue
- [x] Pull Request contains link to any dependent or related Pull Request
- [x] Pull Request contains description of the issue
- [x] Pull Request does not include fixes for issues other than the main ticket

<details>
<summary>
How to replicate CI configuration locally?
</summary>

Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use latest version of the code for each repository.
 
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you need to change multiple repositories and send multiple dependent pull requests related with a change you can easily reproduce the same build by executing it on Github hosted environment or locally in your development environment. See [local execution](https://github.com/kiegroup/github-action-build-chain#local-execution) details to get more information about it.
</details>

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>Pull Request</b>  
  Please add comment: <b>Jenkins retest this</b>
 
* <b>Quarkus LTS checks</b>  
  Please add comment: <b>Jenkins run LTS</b>

* <b>Native checks</b>  
  Please add comment: <b>Jenkins run native</b>

</details>

### CODE REVIEW

**Comment by r00ta** [comment]
I'll take a look when #1083 gets merged :)

**Comment by manstis** [comment]
@r00ta @jiripetrlik This PR is now ready for review.

**Comment by manstis** [comment]
The UI component expects a collection not a map (and it used to always get a collection before FAI-628).

The UI component is used in two places; one of which is getting a collection from the REST endpoint the other a map.

This PR restores the REST endpoint's response to be a collection.

**Comment by manstis** [comment]
@r00ta @jiripetrlik This PR is now ready for review.

**Review by r00ta — APPROVED** [review]

**Comment by r00ta** [comment]
@manstis 1.14 has been already branched. Do you think we should cherry pick this PR?

**Comment by manstis** [comment]
@r00ta Is `1.15` to be branched from `main` or `1.14`?

If from `main` I suggest not cherry-picking as it's not a blocker and Trusty remains _alpha-release_.

**Comment by r00ta** [comment]
> @r00ta Is `1.15` to be branched from `main` or `1.14`?
> 
> If from `main` I suggest not cherry-picking as it's not a blocker and Trusty remains _alpha-release_.

ATM the latest release is `1.13`. `1.14` has been branched today and is affected by this bug. 

It's fine, this fix will be included in `1.15`

**Comment by manstis** [comment]
Hi @jiripetrlik could you please review.

**Review by jiripetrlik — APPROVED** [review]

**Pull request merged**
