### PR TITLE
[incubator-kie-issues-1324] Live reload does not work for KN CLI plugin

### LINKED ISSUE #1324: Live reload does not work for KN CLI plugin
1. Create a project
2. kn create
3. Open the directory
4. cd new-project
5. Run project
6. kn run
7. Open http://localhost:8080/q/dev-ui/extensions
8. Open Serverless Workflow Tools → Workflows → Workflow Definitions
9. Start Hello Workflow and check the status/result of the workflow
10. Keep the kn running and check live reload by editing the workflow.sw.json
11. Save the file and click refresh on the Dev UI page
12. Expected result: the page is refreshed, workflow can be start again
13. Current result: there is 503 Error

### PR DESCRIPTION
**Pull request by treblereel**
Closes: https://github.com/apache/incubator-kie-issues/issues/1324

### CODE REVIEW

**Comment by treblereel** [comment]
The cause of this issue is that we continue to send the heartbeat when the CDI container is already shutting down and the `PostgreSqlJobServiceManagementRepository` is unable to obtain the `PgPool`. The fix involves stopping the heartbeat first (by checking isLeader()).

This issue can be easily reproduced using the `examples/jbpm-compact-architecture-example` with the command `mvn clean package quarkus:dev -Pdevelopment`. To trigger the rebuild just edit `CandidateData.java` or `Offer.java` and reload the `http://localhost:8080/q/dev-ui/extensions`

To verify the fix, build incubator-kie-kogito-apps followed by incubator-kie-tools, replacing `999-20240509-SNAPSHOT` with `999-SNAPSHOT`.

**Comment by treblereel** [comment]
@ricardozanini ^^

**Comment by kie-ci3** [comment]
**PR job** `#1` was: **UNSTABLE**
Possible explanation: This should be test failures


<details>
<summary><b>Reproducer</b></summary>



build-chain build full_downstream  -f 'https://raw.githubusercontent.com/${AUTHOR:apache}/incubator-kie-kogito-pipelines/${BRANCH:main}/.ci/buildchain-config-pr-cdb.yaml' -o 'bc' -p apache/incubator-kie-kogito-apps -u https://github.com/apache/incubator-kie-kogito-apps/pull/2074 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-apps-pr/job/PR-2074/1/display/redirect

**Test results:**
- PASSED: 1664
- FAILED: 1

Those are the test failures: 
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-apps-pr/job/PR-2074/1/testReport/org.kie.kogito.index/ProcessDataIndexMongoDBIT/testProcessInstanceEvents/">org.kie.kogito.index.ProcessDataIndexMongoDBIT.testProcessInstanceEvents</a></summary>
1 expectation failed.<br/>JSON path errors doesn't match.<br/>Expected: null<br/>  Actual: <[{message=Exception while fetching data (/UserTaskInstances[0]/schema) : Runtime service URL not defined, please review the kogito.service.url system property to point the public URL for this runtime., locations=[{line=1, column=85}], path=[UserTaskInstances, 0, schema], extensions={classification=DataFetchingException}}]><br/>
</details>

**Review by ricardozanini — APPROVED** [review]

**Review by wmedvede — APPROVED** [review]

**Comment by kie-ci3** [comment]
**PR job** `#2` was: **UNSTABLE**
Possible explanation: This should be test failures


<details>
<summary><b>Reproducer</b></summary>



build-chain build full_downstream  -f 'https://raw.githubusercontent.com/${AUTHOR:apache}/incubator-kie-kogito-pipelines/${BRANCH:main}/.ci/buildchain-config-pr-cdb.yaml' -o 'bc' -p apache/incubator-kie-kogito-apps -u https://github.com/apache/incubator-kie-kogito-apps/pull/2074 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-apps-pr/job/PR-2074/2/display/redirect

**Test results:**
- PASSED: 1664
- FAILED: 1

Those are the test failures: 
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-apps-pr/job/PR-2074/2/testReport/org.kie.kogito.index.service/InfinispanDomainIndexingServiceIT/testConcurrentProcessInstanceIndex/">org.kie.kogito.index.service.InfinispanDomainIndexingServiceIT.testConcurrentProcessInstanceIndex</a></summary>
Assertion condition defined as a org.kie.kogito.index.service.AbstractIndexingServiceIT 1 expectation failed.<br/>JSON path data.ProcessInstances[0].state doesn't match.<br/>Expected: is "COMPLETED"<br/>  Actual: ACTIVE<br/> within 30 seconds.
</details>

**Comment by kie-ci3** [comment]
**PR job** `#3` was: **UNSTABLE**
Possible explanation: This should be test failures


<details>
<summary><b>Reproducer</b></summary>



build-chain build full_downstream  -f 'https://raw.githubusercontent.com/${AUTHOR:apache}/incubator-kie-kogito-pipelines/${BRANCH:main}/.ci/buildchain-config-pr-cdb.yaml' -o 'bc' -p apache/incubator-kie-kogito-apps -u https://github.com/apache/incubator-kie-kogito-apps/pull/2074 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-apps-pr/job/PR-2074/3/display/redirect

**Test results:**
- PASSED: 1661
- FAILED: 4

Those are the test failures: 
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-apps-pr/job/PR-2074/3/testReport/org.kie.kogito.index.infinispan/ProcessDataIndexInfinispanHttpIT/testProcessInstanceEvents/">org.kie.kogito.index.infinispan.ProcessDataIndexInfinispanHttpIT.testProcessInstanceEvents</a></summary>
1 expectation failed.<br/>JSON path data.UserTaskInstances[0].potentialGroups[0] doesn't match.<br/>Expected: managers<br/>  Actual: null<br/>
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-apps-pr/job/PR-2074/3/testReport/org.kie.kogito.index.mongodb/ProcessDataIndexMongoDBHttpIT/testProcessInstanceEvents/">org.kie.kogito.index.mongodb.ProcessDataIndexMongoDBHttpIT.testProcessInstanceEvents</a></summary>
1 expectation failed.<br/>JSON path data.UserTaskInstances[0].potentialGroups[0] doesn't match.<br/>Expected: managers<br/>  Actual: null<br/>
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-apps-pr/job/PR-2074/3/testReport/org.kie.kogito.index.mongodb/ProcessDataIndexMongoDBKafkaIT/testProcessInstanceEvents/">org.kie.kogito.index.mongodb.ProcessDataIndexMongoDBKafkaIT.testProcessInstanceEvents</a></summary>
Cannot invoke method size() on null object
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-apps-pr/job/PR-2074/3/testReport/org.kie.kogito.index/ProcessDataIndexMongoDBIT/testProcessInstanceEvents/">org.kie.kogito.index.ProcessDataIndexMongoDBIT.testProcessInstanceEvents</a></summary>
Cannot invoke method size() on null object
</details>

**Comment by treblereel** [comment]
@ricardozanini @wmedvede @dgutierr

From what I see, this error is not related to the PR. Moreover, the other PRs also contain the same error (3 out of 4). I agree with @domhanak, who suggests investigating this. WDYT?

**Comment by domhanak** [comment]
@treblereel where did I say that? :D unrelated flaky tests should be reported in an issue and we can disregard them :)

On the other hand, to test this with `kn workflow plugin` - do you have steps to build this with the CLI?
I assume Apps -> kie-tools is the order but not sure what is the current state of kie-tools and the weekly snapshot problem. Any clues?

EDIT: Turns out I can't read properly - `To verify the fix, build incubator-kie-kogito-apps followed by incubator-kie-tools, replacing 999-20240509-SNAPSHOT with 999-SNAPSHOT.`

Will check soon

**Comment by domhanak** [comment]
@treblereel Worked well, I was able to finish the use case of live reload properly.
One thing that kinda alarms me is that we are not having any unit or integration test here to verify this issue.

Do you think we could add a test to check this cause:  `The cause of this issue is that we continue to send the heartbeat when the CDI container is already shutting down and the PostgreSqlJobServiceManagementRepository is unable to obtain the PgPool`. Let me know please, we have `testHeartbeat() and testConflictHeartbeat()` in `PostgreSqlJobServiceManagementRepositoryTest` maybe we can expand it?

**Comment by treblereel** [comment]
@domhanak here https://github.com/apache/incubator-kie-kogito-apps/pull/1530#issuecomment-2044202536 :)

hmm, for some unknown reason, it's green today :)

**Comment by domhanak** [comment]
@treblereel Yea sometimes the CI is slower, depends on the machine and some tests are flaky. 

The comment you are referencing point to different PR, is that right?

**Comment by treblereel** [comment]
@domhanak I don't think we need tests here, all we need is to check the fix is ok. Moreover, fwiv it's not that easy to write tests for this case. But if you think we need it, let me know, maybe we can merge it as is (in case fix is ok) and create a separate issue for tests

**Comment by domhanak** [comment]
Ack, created one for me for E2E here - https://github.com/apache/incubator-kie-issues/issues/1380
If you have an idea how to check this on lower levels of testing please create something similar.
Thanks!

**Review by domhanak — APPROVED** [review]

**Comment by treblereel** [comment]
@domhanak thank you

**Pull request merged**
