### PR TITLE
FAI-534: SHAP Error Bounds

### PR DESCRIPTION
**Pull request by RobGeada**
[FAI-534](https://issues.redhat.com/browse/FAI-534) introduces a number of changes:

1. The WeightedLinearRegression now reports coefficient error and P-values
2. WeightedLinearRegressionResults can now generate configurable confidence intervals of each coefficient
3. FeatureImportance now accepts an optional confidence interval parameter, which is 0 by default
4. The ShapConfig now accepts a confidence interval parameter in the config, default .95
5. The ShapKernelExplainer now returns an array of Saliencies of size `n_model_outputs`, which combines the feature importances found by SHAP with their confidence intervals
6. TestUtils now has a NoisySum model, that outputs the sum of each input feature added to a configurable random noise, to test non-perfect models and their SHAP error bounds.

Many thanks for submitting your Pull Request :heart:! 

Please make sure that your PR meets the following requirements:

- [x] You have read the [contributors guide](https://github.com/kiegroup/kogito-runtimes#contributing-to-kogito)
- [x] Pull Request title is properly formatted: `KOGITO-XYZ Subject`
- [x] Pull Request title contains the target branch if not targeting main: `[0.9.x] KOGITO-XYZ Subject`
- [x] Pull Request contains link to the JIRA issue
- [x] Pull Request contains link to any dependent or related Pull Request
- [x] Pull Request contains description of the issue
- [x] Pull Request does not include fixes for issues other than the main ticket

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>Pull Request</b>  
  Please add comment: <b>Jenkins retest this</b>
 
* <b>Quarkus LTS checks</b>  
  Please add comment: <b>Jenkins run LTS</b>

* <b>Native checks</b>  
  Please add comment: <b>Jenkins run native</b>

</details>

### CODE REVIEW

**Comment by RobGeada** [comment]
jenkins retest this pretty please

**Review by danielezonca — APPROVED** [review]
LGTM 👍

**Comment by RobGeada** [comment]
jenkins retest this please

**Comment by RobGeada** [comment]
jenkins retest this please

**Comment by RobGeada** [comment]
jenkins retest this

**Review by ruivieira — APPROVED** [review]
LGTM, thanks @RobGeada

**Review by tteofili — APPROVED** [review]
LGTM

**Pull request merged**
