### PR TITLE
[master] Task Assigning Service pom.xml quick fix (#913)

### PR DESCRIPTION
**Pull request by wmedvede**
(cherry picked from commit 994a1da615bc727f9c36c2c96e524889e91845f7)

Many thanks for submitting your Pull Request :heart:! 

Please make sure that your PR meets the following requirements:

- [X] You have read the [contributors guide](https://github.com/kiegroup/kogito-runtimes#contributing-to-kogito)
- [X] Pull Request title is properly formatted: `KOGITO-XYZ Subject`
- [X] Pull Request title contains the target branch if not targeting master: `[0.9.x] KOGITO-XYZ Subject`
- [X] Pull Request contains link to the JIRA issue
- [X] Pull Request contains link to any dependent or related Pull Request
- [X] Pull Request contains description of the issue
- [X] Pull Request does not include fixes for issues other than the main ticket

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>Pull Request</b>  
  Please add comment: <b>Jenkins retest this</b>
 
* <b>Quarkus LTS checks</b>  
  Please add comment: <b>Jenkins run LTS</b>

* <b>Native checks</b>  
  Please add comment: <b>Jenkins run native</b>

</details>

### CODE REVIEW

**Comment by wmedvede** [comment]
jenkins please retest

**Comment by wmedvede** [comment]
Jenkins please retest this

**Comment by wmedvede** [comment]
Hi @evacchi , this is the cherry-pick corresponding to the quick fix we added in 1.8.x as part of the Quarkus 2.0.0 migration.
Would you mind approve so I can merge it here?

Thanks!

**Review by Christopher-Chianelli — APPROVED** [review]

**Review by yurloc — APPROVED** [review]
LGTM.

**Pull request merged**
