### PR TITLE
KOGITO-1230 sorting controls in process list

### PR DESCRIPTION
**Pull request by AjayJagan**
Description: Added sorting controls to process list in management-console.
JIRA:  https://issues.redhat.com/browse/KOGITO-1230

### CODE REVIEW

**Comment by nmirasch** [comment]
@AjayJagan I found an issue with the sorting here.
To reproduce: Add a filter by Business key,  access to details , back to process instance list (link at breadcrumb) and try to sort.   The sorting breaks the page with the following error: {"graphQLErrors":[{"message":"Variable 'or' has an invalid value : Expected type 'Map' but was 'String'. Variables for input objects must be an instance of type 'Map'.","locations":[{"line":1,"column":27}],"extensions":{"classification":"ValidationError"}}],"networkError":null,"message":"GraphQL error: Variable 'or' has an invalid value : Expected type 'Map' but was 'String'. Variables for input objects must be an instance of type 'Map'."}

**Comment by AjayJagan** [comment]
> @AjayJagan I found an issue with the sorting here.
> To reproduce: Add a filter by Business key, access to details , back to process instance list (link at breadcrumb) and try to sort. The sorting breaks the page with the following error: {"graphQLErrors":[{"message":"Variable 'or' has an invalid value : Expected type 'Map' but was 'String'. Variables for input objects must be an instance of type 'Map'.","locations":[{"line":1,"column":27}],"extensions":{"classification":"ValidationError"}}],"networkError":null,"message":"GraphQL error: Variable 'or' has an invalid value : Expected type 'Map' but was 'String'. Variables for input objects must be an instance of type 'Map'."}

@nmirasch - the query variables where not generated properly, now it is resolved. Thanks :)

**Comment by Sara4994** [comment]
@AjayJagan LGTM

**Review by nmirasch — APPROVED** [review]

**Review by jstastny-cz — APPROVED** [review]
LGTM

**Review by Sara4994 — APPROVED** [review]

**Comment by Sara4994** [comment]
Looks good :+1:

**Pull request merged**
