### PR TITLE
KOGITO-4077: Update consoles templates to use Qute

### PR DESCRIPTION
**Pull request by pefernan**
Guys, just played a little with Qute to make the consoles use it to generate the HTML, the issue I found is that it needs to have the index.html in the resources folder, so I couldn't take the one from the ui module. Let's see how you see that.

It should be merge after:
https://github.com/kiegroup/kogito-apps/pull/546

Many thanks for submitting your Pull Request :heart:! 

Please make sure that your PR meets the following requirements:

- [ ] You have read the [contributors guide](https://github.com/kiegroup/kogito-runtimes#contributing-to-kogito)
- [ ] Pull Request title is properly formatted: `KOGITO-XYZ Subject`
- [ ] Pull Request title contains the target branch if not targeting master: `[0.9.x] KOGITO-XYZ Subject`
- [ ] Pull Request contains link to the JIRA issue
- [ ] Pull Request contains link to any dependent or related Pull Request
- [ ] Pull Request contains description of the issue
- [ ] Pull Request does not include fixes for issues other than the main ticket

### CODE REVIEW

**Comment by pefernan** [comment]
jenkins retest this

**Comment by jstastny-cz** [comment]
@pefernan what is the justification for the change? I mean Jira https://issues.redhat.com/browse/KOGITO-4077 refers to a PR in examples, it's not clear what we're fixing here. Could you please provide description to the Jira, so that it's clear what happens here?

**Review by cristianonicolai — APPROVED** [review]

**Review by Sara4994 — APPROVED** [review]

**Review by AjayJagan — APPROVED** [review]
:+1:

**Review by jstastny-cz — APPROVED** [review]
@pefernan thanks for the description, looks good.

**Review by nmirasch — APPROVED** [review]
looks good!

**Pull request merged**
