### PR TITLE
FAI-489: Displaying a shortened version of executions ids

### PR DESCRIPTION
**Pull request by kelvah**
JIRA: https://issues.redhat.com/browse/FAI-489

Displaying a shortened version of executions IDs to make them more readable.

I arbitrary decided to cut them to 8 chars, it's the first chunk of the ID. I added Red Hat monospaced font and reverted the ID to lower case to further improve readability.

Execution header: (I've reintroduced the "Execution" title that was removed to make room to the UUID) 

Screenshot from 2021-05-19 18-08-20

Executions list:

Screenshot from 2021-05-19 18-09-13

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>Pull Request</b>  
  Please add comment: <b>Jenkins retest this</b>
 
* <b>Quarkus LTS checks</b>  
  Please add comment: <b>Jenkins run LTS</b>

* <b>Native checks</b>  
  Please add comment: <b>Jenkins run native</b>

</details>

### CODE REVIEW

**Comment by manstis** [comment]
@kelvah You may need to rebase this with `master` that had been broken up until a recent fix was merged (today).

**Review by danielezonca — APPROVED** [review]

**Comment by danielezonca** [comment]
@etirelli 
Do you like new id? :)

**Comment by etirelli** [comment]
> @etirelli
> Do you like new id? :)

👏👏👏

**Review by manstis — APPROVED** [review]
LGTM thanks @kelvah

**Comment by kelvah** [comment]
Jenkins please retest this

**Comment by danielezonca** [comment]
jenkins retest this please

**Comment by kelvah** [comment]
Jenkins retest this

**Review by sjamboro — APPROVED** [review]
Approved. I hope that real UUIDs are generated differently than the mocked one
image

**Review by sjamboro — APPROVED** [review]

**Comment by kelvah** [comment]
> Approved. I hope that real UUIDs are generated differently than the mocked one

Thank you @sjamboro for pointing that out.
I have updated the mocked data so the UUIDs are all different now.

**Pull request merged**
