### PR TITLE
FAI-421: MathUtils class for combinametrics utilities

### PR DESCRIPTION
**Pull request by RobGeada**
Needed a few functions to compute BinomialCoefficients and set combinations for SHAP, implemented them into a MathUtils class.

[FAI-421](https://issues.redhat.com/browse/FAI-421l)

Many thanks for submitting your Pull Request :heart:! 

Please make sure that your PR meets the following requirements:

- [ ] You have read the [contributors guide](https://github.com/kiegroup/kogito-runtimes#contributing-to-kogito)
- [ ] Pull Request title is properly formatted: `KOGITO-XYZ Subject`
- [ ] Pull Request title contains the target branch if not targeting master: `[0.9.x] KOGITO-XYZ Subject`
- [ ] Pull Request contains link to the JIRA issue
- [ ] Pull Request contains link to any dependent or related Pull Request
- [ ] Pull Request contains description of the issue
- [ ] Pull Request does not include fixes for issues other than the main ticket

### CODE REVIEW

**Comment by r00ta** [comment]
Hi @RobGeada , is this equivalent to this function https://commons.apache.org/proper/commons-math/javadocs/api-3.3/org/apache/commons/math3/util/CombinatoricsUtils.html#combinationsIterator(int,%20int) ?

**Comment by RobGeada** [comment]
@r00ta it totally is, and the other is equivalent to https://commons.apache.org/proper/commons-math/javadocs/api-3.3/org/apache/commons/math3/util/CombinatoricsUtils.html#binomialCoefficient(int,%20int); I wasn't sure about requiring a dependence on all of Commons Math for just two functions. If we'd rather just import the functions, the Combinatorics utils would suit my needs equally well!

**Comment by r00ta** [comment]
> @r00ta it totally is, and the other is equivalent to https://commons.apache.org/proper/commons-math/javadocs/api-3.3/org/apache/commons/math3/util/CombinatoricsUtils.html#binomialCoefficient(int,%20int); I wasn't sure about requiring a dependence on all of Commons Math for just two functions. If we'd rather just import the functions, the Combinatorics utils would suit my needs equally well!

Hey @RobGeada sorry for the late reply. I think Optaplanner already imports `commons-math3` (https://github.com/kiegroup/optaplanner/blob/65eca5f7f6db907d99ba907ed15e51dee6cafe26/optaplanner-core/pom.xml#L75), and since we import OP we end up having it already in the final jar (or in the `/libs` if the final application is not creating an uber-jar). You can then import `commons-math3` and use the existing function with no overhead at all

**Comment by r00ta** [comment]
> > @r00ta it totally is, and the other is equivalent to https://commons.apache.org/proper/commons-math/javadocs/api-3.3/org/apache/commons/math3/util/CombinatoricsUtils.html#binomialCoefficient(int,%20int); I wasn't sure about requiring a dependence on all of Commons Math for just two functions. If we'd rather just import the functions, the Combinatorics utils would suit my needs equally well!
> 
> Hey @RobGeada sorry for the late reply. I think Optaplanner already imports `commons-math3` (https://github.com/kiegroup/optaplanner/blob/65eca5f7f6db907d99ba907ed15e51dee6cafe26/optaplanner-core/pom.xml#L75), and since we import OP we end up having it already in the final jar (or in the `/libs` if the final application is not creating an uber-jar). You can then import `commons-math3` and use the existing function with no overhead at all

Hey @RobGeada , any feedback on this?

**Pull request closed without merging**
