### PR TITLE
NO-ISSUE: Trigger jitexecutor-native Github workflow as part of the Kogito Apps weekly job

### PR DESCRIPTION
**Pull request by rodrigonull**
This PR is part of the effort for the Apache 10 release and it adds a new trigger for the jitexecutor-native workflow to run as part of the Kogito Apps weekly job.

Depends on: https://github.com/apache/incubator-kie-kogito-apps/pull/2049

### CODE REVIEW

**Review by tiagobento — APPROVED** [review]

**Review by jstastny-cz — APPROVED** [review]
LGTM, I suppose the gh workflow run command requires our "push" credentials.

**Comment by tiagobento** [comment]
getGitAuthor and getRepoName will always return `apache` and `incubator-kie-tools` in this case?

**Comment by tiagobento** [comment]
Or it returns whatever is configured in the Jenkins job "Configuration"?

**Comment by rodrigonull** [comment]
It returns what is in the job configuration, which is `apache` and `incubator-kie-kogito-apps`.

**Review by tiagobento — APPROVED** [review]

**Pull request merged**
