### PR TITLE
FAI-614: Configurable explanation section

### PR DESCRIPTION
**Pull request by kelvah**
JIRA ticket: https://issues.redhat.com/browse/FAI-614

With this PR it is now possible to turn off the explanation charts (and table) inside the Outcome Details page.

I added the configuration prop `explanationEnabled` to `TrustyApp` and set up a context inside it to share the configuration across the application.

There are some changes and renaming because the component serving the Outcome Details page was called `Explanation` (the original name of the page in the early days). Now that the explanation can be turned off it made no sense anymore, so I renamed  the old `Explanation` component to `OutcomeDetails` and I moved the _explanation_ part of it to a dedicated component called `Explanation`, unsurprisingly.

I hope it's not too confusing :sweat_smile: 

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>Pull Request</b>  
  Please add comment: <b>Jenkins retest this</b>
 
* <b>Quarkus LTS checks</b>  
  Please add comment: <b>Jenkins run LTS</b>

* <b>Native checks</b>  
  Please add comment: <b>Jenkins run native</b>

</details>

### CODE REVIEW

**Review by manstis — APPROVED** [review]
LGTM @kelvah (and works too!)

**Review by sjamboro — APPROVED** [review]

**Comment by manstis** [comment]
Jenkins retest this

**Comment by manstis** [comment]
When this is merged I'll do the same for counterfactuals :+1:

**Comment by kelvah** [comment]
Jenkins retest this

**Comment by kelvah** [comment]
What's going on with Sonar? :thinking:
It was green before I rebased onto main to resolve conflicts.

**Comment by manstis** [comment]
It looks like coverage for `data-index` is being incorrectly included in your PR :cry: 

If the problem continues just comment the PR for whoever will merge it to look and confirm you're good to go.

**Comment by manstis** [comment]
Jenkins retest this

**Comment by manstis** [comment]
Merging. SonarCloud is reporting lack of test coverage on files not even part of this PR.

**Pull request merged**
