### PR TITLE
kie-issues#746: set timeout for testcontainers after waitingFor invocation

### PR DESCRIPTION
**Pull request by jstastny-cz**
Fixes
* apache/incubator-kie-issues#746

Another batch of fixes due to misconfiguration of testcontainers coming from the fact that `waitingFor` method invocation drops previously configured `withStartupTimeout` value.
Need to override after each such call - can't rely on the value set in parent classes.

### CODE REVIEW

**Comment by kie-ci3** [comment]
**PR job** `#3` was: **UNSTABLE**
Possible explanation: This should be test failures


<details>
<summary><b>Reproducer</b></summary>



build-chain build full_downstream  -f 'https://raw.githubusercontent.com/${AUTHOR:apache}/incubator-kie-kogito-pipelines/${BRANCH:main}/.ci/buildchain-config-pr-cdb.yaml' -o 'bc' -p apache/incubator-kie-kogito-apps -u https://github.com/apache/incubator-kie-kogito-apps/pull/1932 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-apps-pr/job/PR-1932/3/display/redirect

**Test results:**
- PASSED: 2836
- FAILED: 1

Those are the test failures: 
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-apps-pr/job/PR-1932/3/testReport/org.kie.kogito.index.service/MongoDomainIndexingServiceIT/testConcurrentProcessInstanceIndex/">org.kie.kogito.index.service.MongoDomainIndexingServiceIT.testConcurrentProcessInstanceIndex</a></summary>
Assertion condition defined as a org.kie.kogito.index.service.AbstractIndexingServiceIT 1 expectation failed.<br/>JSON path data.ProcessInstances[0].state doesn't match.<br/>Expected: is "COMPLETED"<br/>  Actual: ACTIVE<br/> within 30 seconds.
</details>

**Review by pefernan — APPROVED** [review]

**Comment by pefernan** [comment]
@jstastny-cz should we have this in q3 branch?

**Comment by jstastny-cz** [comment]
It would be safer - unless we are certain that the version of testcontainers used overthere has changed the implemented behavior.

**Comment by jstastny-cz** [comment]
I'll try cherry-pick.

**Review by nmirasch — APPROVED** [review]

**Pull request merged**
