### PR TITLE
KOGITO-7766 - Add inmemory and postgresql Data Index addon to produc…

### PR DESCRIPTION
**Pull request by cristianonicolai**
…tized profile

### CODE REVIEW

**Comment by cristianonicolai** [comment]
jenkins run quarkus-lts

**Review by radtriste — APPROVED** [review]

**Comment by kie-ci3** [comment]
**(tests) - kogito-apps job** `#631` was: **UNSTABLE**
Possible explanation: This should be test failures

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-apps.tests.kogito-apps/631/display/redirect

**Test results:**
- PASSED: 1971
- FAILED: 1

Those are the test failures: 
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-apps.tests.kogito-apps/631/testReport/org.kie.kogito.index/ProcessDataIndexPostgreSqlIT/testProcessInstanceEvents/">org.kie.kogito.index.ProcessDataIndexPostgreSqlIT.testProcessInstanceEvents</a></summary>
java.lang.AssertionError: <br/>1 expectation failed.<br/>JSON path data.UserTaskInstances[0].comments.size() doesn't match.<br/>Expected: is <1><br/>  Actual: <0><br/><br/>
</details>

**Comment by cristianonicolai** [comment]
Jenkins rerun kogito-apps tests

**Review by nmirasch — APPROVED** [review]

**Comment by nmirasch** [comment]
@cristianonicolai I just saw a typo in commit text "KOGITO-7766 - Add inmemory and postrgresql..". Maybe remove the extra 'r' before merge?

**Pull request merged**
