### PR TITLE
KOGITO-4363: Fixed refresh icon on Jobs management

### PR DESCRIPTION
**Pull request by Sara4994**
Fixed refresh icon on jobs management page

### CODE REVIEW

**Comment by nmirasch** [comment]
@Sara4994 it works fine now. Ready to merge when tests get the green. (FAIL  src/components/Templates/JobsManagementPage/tests/JobsManagementPage.test.tsx)

**Comment by Sara4994** [comment]
jenkins please retest this

**Comment by radtriste** [comment]
Jenkins retest this

**Comment by Sara4994** [comment]
Jenkins retest this

**Review by nmirasch — APPROVED** [review]

**Review by jstastny-cz — APPROVED** [review]

**Pull request merged**
