### PR TITLE
KOGITO-4336 - Manage all testcontainers dependencies for using correc…

### PR DESCRIPTION
**Pull request by cristianonicolai**
…t version

### CODE REVIEW

**Review by radtriste — APPROVED** [review]

**Comment by cristianonicolai** [comment]
jenkins please retest this

**Review by nmirasch — APPROVED** [review]

**Comment by cristianonicolai** [comment]
jenkins please retest this

**Comment by cristianonicolai** [comment]
jenkins please retest this

**Comment by cristianonicolai** [comment]
jenkins please retest this

**Pull request merged**
