### PR TITLE
[KOGITO-4335] Fix integration tests resources to include generics

### PR DESCRIPTION
**Pull request by tiagodolphine**
Depends on 
https://github.com/kiegroup/kogito-runtimes/pull/1103

Many thanks for submitting your Pull Request :heart:! 

Please make sure that your PR meets the following requirements:

- [ ] You have read the [contributors guide](https://github.com/kiegroup/kogito-runtimes#contributing-to-kogito)
- [ ] Pull Request title is properly formatted: `KOGITO-XYZ Subject`
- [ ] Pull Request title contains the target branch if not targeting master: `[0.9.x] KOGITO-XYZ Subject`
- [ ] Pull Request contains link to the JIRA issue
- [ ] Pull Request contains link to any dependent or related Pull Request
- [ ] Pull Request contains description of the issue
- [ ] Pull Request does not include fixes for issues other than the main ticket

### CODE REVIEW

**Comment by tiagodolphine** [comment]
jenkins retest this

**Comment by tiagodolphine** [comment]
jenkins retest this

**Review by MarianMacik — APPROVED** [review]

**Comment by tiagodolphine** [comment]
jenkins retest this

**Comment by tiagodolphine** [comment]
@cristianonicolai can you review this one, just minor changes to align with modification in test resources.

**Review by cristianonicolai — APPROVED** [review]

**Pull request merged**
