### PR TITLE
KOGITO-5409 JIT Executor Native Image tests fail

### PR DESCRIPTION
**Pull request by tarilabs**
https://issues.redhat.com/browse/KOGITO-5409

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>Pull Request</b>  
  Please add comment: <b>Jenkins retest this</b>
 
* <b>Quarkus LTS checks</b>  
  Please add comment: <b>Jenkins run LTS</b>

* <b>Native checks</b>  
  Please add comment: <b>Jenkins run native</b>

</details>

### CODE REVIEW

**Comment by tarilabs** [comment]
Jenkins run native

**Comment by tarilabs** [comment]
# (build) Apps — Build finished. 1766 tests run, 7 skipped, 0 failed.

```

[2021-06-24T14:07:31.300Z] [INFO] ------------------------------------------------------------------------

[2021-06-24T14:07:31.300Z] [INFO] Reactor Summary for Kogito Apps 2.0.0-SNAPSHOT:

[2021-06-24T14:07:31.300Z] [INFO] 

[2021-06-24T14:07:31.300Z] [INFO] Kogito Apps ........................................ SUCCESS [  3.969 s]

[2021-06-24T14:07:31.300Z] [INFO] Kogito Apps :: BOM ................................. SUCCESS [  0.079 s]

[2021-06-24T14:07:31.301Z] [INFO] Kogito Apps :: Build Parent BOM .................... SUCCESS [  0.088 s]

[2021-06-24T14:07:31.301Z] [INFO] Kogito Apps :: Persistence Commons ................. SUCCESS [  0.077 s]

[2021-06-24T14:07:31.301Z] [INFO] Kogito Apps :: Persistence Commons API ............. SUCCESS [  3.821 s]

[2021-06-24T14:07:31.301Z] [INFO] Kogito Apps :: Persistence Commons Protobuf ........ SUCCESS [  5.724 s]

[2021-06-24T14:07:31.301Z] [INFO] Kogito Apps :: Persistence Commons Infinispan ...... SUCCESS [ 28.405 s]

[2021-06-24T14:07:31.301Z] [INFO] Kogito Apps :: Persistence Commons MongoDB ......... SUCCESS [ 37.737 s]

[2021-06-24T14:07:31.301Z] [INFO] Kogito Apps :: Persistence Commons Redis ........... SUCCESS [  6.330 s]

[2021-06-24T14:07:31.301Z] [INFO] Kogito Apps :: Persistence Commons PostgreSQL ...... SUCCESS [ 28.682 s]

[2021-06-24T14:07:31.301Z] [INFO] Kogito Apps :: Jobs Service ........................ SUCCESS [  0.057 s]

[2021-06-24T14:07:31.301Z] [INFO] Kogito Apps :: Jobs Service Common ................. SUCCESS [03:24 min]

[2021-06-24T14:07:31.301Z] [INFO] Kogito Apps :: Jobs Service Infinispan ............. SUCCESS [02:54 min]

[2021-06-24T14:07:31.301Z] [INFO] Kogito Apps :: Jobs Service PostgreSQL ............. SUCCESS [02:55 min]

[2021-06-24T14:07:31.301Z] [INFO] Kogito Apps :: Jobs Service :: MongoDB ............. SUCCESS [02:45 min]

[2021-06-24T14:07:31.301Z] [INFO] Kogito Apps :: Data Index .......................... SUCCESS [  0.114 s]

[2021-06-24T14:07:31.301Z] [INFO] Kogito Apps :: Data Index Storage .................. SUCCESS [  0.072 s]

[2021-06-24T14:07:31.301Z] [INFO] Kogito Apps :: Data Index Storage API .............. SUCCESS [  2.060 s]

[2021-06-24T14:07:31.301Z] [INFO] Kogito Apps :: Data Index Storage Protobuf ......... SUCCESS [  3.263 s]

[2021-06-24T14:07:31.301Z] [INFO] Kogito Apps :: Data Index Storage Infinispan ....... SUCCESS [  5.914 s]

[2021-06-24T14:07:31.301Z] [INFO] Kogito Apps :: Data Index Storage MongoDB .......... SUCCESS [ 23.619 s]

[2021-06-24T14:07:31.301Z] [INFO] Kogito Apps :: Data Index Storage PostgreSQL ....... SUCCESS [ 26.503 s]

[2021-06-24T14:07:31.301Z] [INFO] Kogito Apps :: Data Index Service .................. SUCCESS [  0.058 s]

[2021-06-24T14:07:31.301Z] [INFO] Kogito Apps :: Data Index Service Common ........... SUCCESS [ 15.763 s]

[2021-06-24T14:07:31.301Z] [INFO] Kogito Apps :: Data Index Service with Infinispan .. SUCCESS [03:41 min]

[2021-06-24T14:07:31.301Z] [INFO] Kogito Apps :: Data Index Service with MongoDB ..... SUCCESS [03:29 min]

[2021-06-24T14:07:31.301Z] [INFO] Kogito Apps :: Data Index Service with PostgreSQL .. SUCCESS [03:10 min]

[2021-06-24T14:07:31.301Z] [INFO] Kogito Apps :: UI Packages ......................... FAILURE [11:12 min]

[2021-06-24T14:07:31.301Z] [INFO] Kogito Apps :: Security Commons .................... SUCCESS [ 56.726 s]

[2021-06-24T14:07:31.301Z] [INFO] Kogito Apps :: Management Console .................. SKIPPED

[2021-06-24T14:07:31.301Z] [INFO] Kogito Apps :: Trusty UI ........................... SKIPPED

[2021-06-24T14:07:31.301Z] [INFO] Kogito Apps :: Task Console ........................ SKIPPED

[2021-06-24T14:07:31.301Z] [INFO] Kogito Apps :: Explainability ...................... SUCCESS [  0.060 s]

[2021-06-24T14:07:31.301Z] [INFO] Kogito Apps :: Explainability Api .................. SUCCESS [  3.549 s]

[2021-06-24T14:07:31.301Z] [INFO] Kogito Apps :: Explainability Core ................. SUCCESS [01:22 min]

[2021-06-24T14:07:31.301Z] [INFO] Kogito Apps :: Explainability Integration Tests .... SUCCESS [  0.059 s]

[2021-06-24T14:07:31.301Z] [INFO] Kogito Apps :: Explainability Integration Tests DMN  SUCCESS [01:31 min]

[2021-06-24T14:07:31.301Z] [INFO] Kogito Apps :: Explainability Integration Tests OpenNLP SUCCESS [  7.489 s]

[2021-06-24T14:07:31.301Z] [INFO] Kogito Apps :: Explainability Integration Tests PMML SUCCESS [ 14.278 s]

[2021-06-24T14:07:31.301Z] [INFO] Kogito Apps :: Explainability Service .............. SUCCESS [  7.855 s]

[2021-06-24T14:07:31.301Z] [INFO] Kogito Apps :: Explainability Service Messaging .... SUCCESS [01:18 min]

[2021-06-24T14:07:31.301Z] [INFO] Kogito Apps :: Explainability Service Rest ......... SUCCESS [01:19 min]

[2021-06-24T14:07:31.301Z] [INFO] Kogito Apps :: Trusty .............................. SUCCESS [  0.061 s]

[2021-06-24T14:07:31.301Z] [INFO] Kogito Apps :: Trusty Storage ...................... SUCCESS [  0.046 s]

[2021-06-24T14:07:31.301Z] [INFO] Kogito Apps :: Trusty Storage API .................. SUCCESS [  3.305 s]

[2021-06-24T14:07:31.301Z] [INFO] Kogito Apps :: Trusty Storage Common ............... SUCCESS [  0.202 s]

[2021-06-24T14:07:31.301Z] [INFO] Kogito Apps :: Trusty Storage Infinispan ........... SUCCESS [  5.284 s]

[2021-06-24T14:07:31.301Z] [INFO] Kogito Apps :: Trusty Storage Redis ................ SUCCESS [  3.332 s]

[2021-06-24T14:07:31.301Z] [INFO] Kogito Apps :: Trusty Service ...................... SUCCESS [  0.048 s]

[2021-06-24T14:07:31.301Z] [INFO] Kogito Apps :: Trusty Service :: API ............... SUCCESS [  0.270 s]

[2021-06-24T14:07:31.301Z] [INFO] Kogito Apps :: Trusty Service Common ............... SUCCESS [02:41 min]

[2021-06-24T14:07:31.301Z] [INFO] Kogito Apps :: Trusty Service Infinispan ........... SUCCESS [01:37 min]

[2021-06-24T14:07:31.301Z] [INFO] Kogito Apps :: Trusty Service Redis ................ SUCCESS [01:05 min]

[2021-06-24T14:07:31.301Z] [INFO] Kogito Apps :: Task Assigning ...................... SUCCESS [  0.055 s]

[2021-06-24T14:07:31.301Z] [INFO] Kogito Apps :: Task Assigning Core ................. SUCCESS [ 20.754 s]

[2021-06-24T14:07:31.301Z] [INFO] Kogito Apps :: Task Assigning Process Service Client SUCCESS [ 26.019 s]

[2021-06-24T14:07:31.301Z] [INFO] Kogito Apps :: Task Assigning :: Integration API ... SUCCESS [  0.409 s]

[2021-06-24T14:07:31.301Z] [INFO] Kogito Apps :: Task Assigning :: User Service ...... SUCCESS [  0.059 s]

[2021-06-24T14:07:31.301Z] [INFO] Kogito Apps :: Task Assigning :: User Service Properties SUCCESS [  3.998 s]

[2021-06-24T14:07:31.301Z] [INFO] Kogito Apps :: Task Assigning Service .............. SUCCESS [ 36.296 s]

[2021-06-24T14:07:31.301Z] [INFO] Kogito Apps :: JIT Executor ........................ SUCCESS [  0.054 s]

[2021-06-24T14:07:31.301Z] [INFO] Kogito Apps :: JIT Executor DMN .................... SUCCESS [ 29.733 s]

[2021-06-24T14:07:31.301Z] [INFO] Kogito Apps :: JIT Executor Runner ................. SUCCESS [ 10.411 s]

[2021-06-24T14:07:31.301Z] [INFO] Kogito Apps :: Integration Tests ................... SUCCESS [  0.060 s]

[2021-06-24T14:07:31.301Z] [INFO] Kogito Apps :: Integration Tests :: Jobs Service ... SUCCESS [  0.061 s]

[2021-06-24T14:07:31.301Z] [INFO] Kogito Apps :: Integration Tests :: Jobs Service :: Common SUCCESS [  0.442 s]

[2021-06-24T14:07:31.301Z] [INFO] Kogito Apps :: Integration Tests :: Jobs Service :: Quarkus SUCCESS [01:09 min]

[2021-06-24T14:07:31.301Z] [INFO] Kogito Apps :: Integration Tests :: Jobs Service :: Spring Boot SUCCESS [ 37.947 s]

[2021-06-24T14:07:31.301Z] [INFO] Kogito Apps :: Integration Tests :: Trusty Service . SUCCESS [  0.063 s]

[2021-06-24T14:07:31.301Z] [INFO] Kogito Apps :: Integration Tests :: Trusty Service :: Common SUCCESS [  0.554 s]

[2021-06-24T14:07:31.301Z] [INFO] Kogito Apps :: Integration Tests :: Trusty Service :: Quarkus SUCCESS [01:44 min]

[2021-06-24T14:07:31.301Z] [INFO] Kogito Apps :: Integration Tests :: Trusty Service :: Spring Boot SUCCESS [01:38 min]

[2021-06-24T14:07:31.301Z] [INFO] Kogito Apps :: Integration Tests :: Data Index ..... SUCCESS [  0.061 s]

[2021-06-24T14:07:31.301Z] [INFO] Kogito Apps :: Integration Tests :: Data Index :: Common SUCCESS [  0.598 s]

[2021-06-24T14:07:31.301Z] [INFO] Kogito Apps :: Integration Tests :: Data Index :: Quarkus SUCCESS [02:51 min]

[2021-06-24T14:07:31.301Z] [INFO] Kogito Apps :: Integration Tests :: Data Index :: Spring Boot SUCCESS [01:43 min]

[2021-06-24T14:07:31.301Z] [INFO] ------------------------------------------------------------------------

[2021-06-24T14:07:31.301Z] [INFO] BUILD FAILURE

[2021-06-24T14:07:31.301Z] [INFO] ------------------------------------------------------------------------

[2021-06-24T14:07:31.301Z] [INFO] Total time:  01:01 h

[2021-06-24T14:07:31.301Z] [INFO] Finished at: 2021-06-24T10:07:30-04:00

[2021-06-24T14:07:31.301Z] [INFO] ------------------------------------------------------------------------

[2021-06-24T14:07:31.301Z] [ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.9.1:yarn (yarn test) on project kogito-apps-ui-packages: Failed to run task: 'yarn run test --registry=https://repository.engineering.redhat.com/nexus/repository/registry.npmjs.org/' failed. org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1) -> [Help 1]
```

so unrelated.

# (native) Apps — Build finished. 1447 tests run, 1 skipped, 2 failed.

```
[INFO] ------------------------------------------------------------------------

[INFO] Reactor Summary for Kogito Apps 2.0.0-SNAPSHOT:

[INFO] 

[INFO] Kogito Apps ........................................ SUCCESS [  2.055 s]

[INFO] Kogito Apps :: BOM ................................. SUCCESS [  0.073 s]

[INFO] Kogito Apps :: Build Parent BOM .................... SUCCESS [  0.061 s]

[INFO] Kogito Apps :: Persistence Commons ................. SUCCESS [  0.070 s]

[INFO] Kogito Apps :: Persistence Commons API ............. SUCCESS [  3.807 s]

[INFO] Kogito Apps :: Persistence Commons Protobuf ........ SUCCESS [  4.238 s]

[INFO] Kogito Apps :: Persistence Commons Infinispan ...... SUCCESS [  5.305 s]

[INFO] Kogito Apps :: Persistence Commons MongoDB ......... SUCCESS [  3.679 s]

[INFO] Kogito Apps :: Persistence Commons Redis ........... SUCCESS [  3.494 s]

[INFO] Kogito Apps :: Persistence Commons PostgreSQL ...... SUCCESS [  1.985 s]

[INFO] Kogito Apps :: Jobs Service ........................ SUCCESS [  0.048 s]

[INFO] Kogito Apps :: Jobs Service Common ................. SUCCESS [03:43 min]

[INFO] Kogito Apps :: Jobs Service Infinispan ............. SUCCESS [03:20 min]

[INFO] Kogito Apps :: Jobs Service PostgreSQL ............. SUCCESS [03:21 min]

[INFO] Kogito Apps :: Jobs Service :: MongoDB ............. FAILURE [03:53 min]

[INFO] Kogito Apps :: Data Index .......................... SUCCESS [  0.056 s]

[INFO] Kogito Apps :: Data Index Storage .................. SUCCESS [  0.038 s]

[INFO] Kogito Apps :: Data Index Storage API .............. SUCCESS [  0.820 s]

[INFO] Kogito Apps :: Data Index Storage Protobuf ......... SUCCESS [  1.519 s]

[INFO] Kogito Apps :: Data Index Storage Infinispan ....... SUCCESS [  3.246 s]

[INFO] Kogito Apps :: Data Index Storage MongoDB .......... SUCCESS [  2.179 s]

[INFO] Kogito Apps :: Data Index Storage PostgreSQL ....... SUCCESS [  4.129 s]

[INFO] Kogito Apps :: Data Index Service .................. SUCCESS [  0.042 s]

[INFO] Kogito Apps :: Data Index Service Common ........... SUCCESS [  8.439 s]

[INFO] Kogito Apps :: Data Index Service with Infinispan .. SUCCESS [03:07 min]

[INFO] Kogito Apps :: Data Index Service with MongoDB ..... SUCCESS [03:05 min]

[INFO] Kogito Apps :: Data Index Service with PostgreSQL .. SUCCESS [03:53 min]

[INFO] Kogito Apps :: UI Packages ......................... SUCCESS [  0.337 s]

[INFO] Kogito Apps :: Security Commons .................... SUCCESS [01:57 min]

[INFO] Kogito Apps :: Management Console .................. SUCCESS [02:21 min]

[INFO] Kogito Apps :: Trusty UI ........................... FAILURE [03:01 min]

[INFO] Kogito Apps :: Task Console ........................ FAILURE [02:11 min]

[INFO] Kogito Apps :: Explainability ...................... SUCCESS [  0.035 s]

[INFO] Kogito Apps :: Explainability Api .................. SUCCESS [  1.555 s]

[INFO] Kogito Apps :: Explainability Core ................. SUCCESS [ 58.463 s]

[INFO] Kogito Apps :: Explainability Integration Tests .... SUCCESS [  0.040 s]

[INFO] Kogito Apps :: Explainability Integration Tests DMN  SUCCESS [ 57.867 s]

[INFO] Kogito Apps :: Explainability Integration Tests OpenNLP SUCCESS [  4.288 s]

[INFO] Kogito Apps :: Explainability Integration Tests PMML SUCCESS [  5.739 s]

[INFO] Kogito Apps :: Explainability Service .............. SUCCESS [  3.666 s]

[INFO] Kogito Apps :: Explainability Service Messaging .... FAILURE [01:39 min]

[INFO] Kogito Apps :: Explainability Service Rest ......... FAILURE [01:34 min]

[INFO] Kogito Apps :: Trusty .............................. SUCCESS [  0.049 s]

[INFO] Kogito Apps :: Trusty Storage ...................... SUCCESS [  0.073 s]

[INFO] Kogito Apps :: Trusty Storage API .................. SUCCESS [  1.552 s]

[INFO] Kogito Apps :: Trusty Storage Common ............... SUCCESS [  0.172 s]

[INFO] Kogito Apps :: Trusty Storage Infinispan ........... SUCCESS [  2.251 s]

[INFO] Kogito Apps :: Trusty Storage Redis ................ SUCCESS [  1.657 s]

[INFO] Kogito Apps :: Trusty Service ...................... SUCCESS [  0.038 s]

[INFO] Kogito Apps :: Trusty Service :: API ............... SUCCESS [  0.207 s]

[INFO] Kogito Apps :: Trusty Service Common ............... SUCCESS [01:02 min]

[INFO] Kogito Apps :: Trusty Service Infinispan ........... SUCCESS [02:46 min]

[INFO] Kogito Apps :: Trusty Service Redis ................ SUCCESS [02:32 min]

[INFO] Kogito Apps :: Task Assigning ...................... SUCCESS [  0.048 s]

[INFO] Kogito Apps :: Task Assigning Core ................. SUCCESS [ 10.210 s]

[INFO] Kogito Apps :: Task Assigning Process Service Client SUCCESS [ 12.436 s]

[INFO] Kogito Apps :: Task Assigning :: Integration API ... SUCCESS [  0.257 s]

[INFO] Kogito Apps :: Task Assigning :: User Service ...... SUCCESS [  0.028 s]

[INFO] Kogito Apps :: Task Assigning :: User Service Properties SUCCESS [  1.790 s]

[INFO] Kogito Apps :: Task Assigning Service .............. SUCCESS [03:55 min]

[INFO] Kogito Apps :: JIT Executor ........................ SUCCESS [  0.044 s]

[INFO] Kogito Apps :: JIT Executor DMN .................... SUCCESS [ 13.808 s]

[INFO] Kogito Apps :: JIT Executor Runner ................. SUCCESS [03:12 min]

[INFO] Kogito Apps :: Integration Tests ................... SUCCESS [  0.050 s]

[INFO] Kogito Apps :: Integration Tests :: Jobs Service ... SUCCESS [  0.034 s]

[INFO] Kogito Apps :: Integration Tests :: Jobs Service :: Common SUCCESS [  0.431 s]

[INFO] Kogito Apps :: Integration Tests :: Jobs Service :: Quarkus SUCCESS [02:37 min]

[INFO] Kogito Apps :: Integration Tests :: Jobs Service :: Spring Boot SUCCESS [  8.835 s]

[INFO] Kogito Apps :: Integration Tests :: Trusty Service . SKIPPED

[INFO] Kogito Apps :: Integration Tests :: Trusty Service :: Common SKIPPED

[INFO] Kogito Apps :: Integration Tests :: Trusty Service :: Quarkus SKIPPED

[INFO] Kogito Apps :: Integration Tests :: Trusty Service :: Spring Boot SKIPPED

[INFO] Kogito Apps :: Integration Tests :: Data Index ..... SUCCESS [  0.048 s]

[INFO] Kogito Apps :: Integration Tests :: Data Index :: Common SUCCESS [  0.357 s]

[INFO] Kogito Apps :: Integration Tests :: Data Index :: Quarkus SUCCESS [03:10 min]

[INFO] Kogito Apps :: Integration Tests :: Data Index :: Spring Boot SUCCESS [  5.948 s]

[INFO] ------------------------------------------------------------------------

[INFO] BUILD FAILURE

[INFO] ------------------------------------------------------------------------

[INFO] Total time:  01:00 h

[INFO] Finished at: 2021-06-24T10:04:06-04:00

[INFO] ------------------------------------------------------------------------

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-failsafe-plugin:3.0.0-M5:verify (integration-test) on project jobs-service-mongodb: There are test failures.

[ERROR] 

[ERROR] Please refer to /home/jenkins/workspace/KIE/kogito/pullrequest/kogito-apps.native.apps/kogito-apps/jobs-service/jobs-service-mongodb/target/failsafe-reports for the individual test results.

[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.

[ERROR] -> [Help 1]

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-failsafe-plugin:3.0.0-M5:verify (integration-test) on project trusty-ui: There are test failures.

[ERROR] 

[ERROR] Please refer to /home/jenkins/workspace/KIE/kogito/pullrequest/kogito-apps.native.apps/kogito-apps/trusty-ui/target/failsafe-reports for the individual test results.

[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.

[ERROR] org.apache.maven.surefire.booter.SurefireBooterForkException: The forked VM terminated without properly saying goodbye. VM crash or System.exit called?

[ERROR] Command was /bin/sh -c cd /home/jenkins/workspace/KIE/kogito/pullrequest/kogito-apps.native.apps/kogito-apps/trusty-ui && /usr/lib/jvm/java-11-openjdk-11.0.11.0.9-1.el7_9.x86_64/bin/java @/home/jenkins/workspace/KIE/kogito/pullrequest/kogito-apps.native.apps/kogito-apps/trusty-ui/target/surefire/surefireargs2422727265705641345 /home/jenkins/workspace/KIE/kogito/pullrequest/kogito-apps.native.apps/kogito-apps/trusty-ui/target/surefire 2021-06-24T09-03-42_151-jvmRun1 surefire7076353608325591628tmp surefire_317716996139534858313tmp
```

so this PR is fixing JIT Runner test failures on master and the other failures are unrelated to the scope of this PR.

**Review by evacchi — APPROVED** [review]
🎉

**Comment by evacchi** [comment]
@tiagodolphine it is possible that the fix for the jobs service is as simple as this one 🤔

**Comment by evacchi** [comment]
I'd say the non-native jenkins run is just flaky (GHA is fine), while native fails 2 because they are unrelated. Merge?

**Review by danielezonca — APPROVED** [review]
LGTM 👍

**Pull request merged**
