### PR TITLE
KOGITO-5209 unify data-table to PF standards

### PR DESCRIPTION
**Pull request by AjayJagan**
unified data table according to PF standards

### CODE REVIEW

**Review by pefernan — CHANGES_REQUESTED** [review]
Really good @AjayJagan! would it be possible to also show the no-filters-selected empty state in the table? It should be easy to pass it using the ErrorComponent property and pass the error flag as true...

**Comment by AjayJagan** [comment]
> Really good @AjayJagan! would it be possible to also show the no-filters-selected empty state in the table? It should be easy to pass it using the ErrorComponent property and pass the error flag as true...

@pefernan , in management console , when displaying the no status selected , we hide the table headers .. and in task console we have the same functionality .. so do we need to change it?

**Comment by pefernan** [comment]
@AjayJagan you're right, my bad!

**Comment by pefernan** [comment]
jenkins retest this

**Review by pefernan — APPROVED** [review]
+1

**Pull request merged**
