### PR TITLE
KOGITO-4803: Update to latest Kogito-tooling version (0.8.6)

### PR DESCRIPTION
**Pull request by pefernan**
Upgraded to latest version of kogito-tooling to allow components render in divs instead of iframes.

@kelvah added you as a reviewer because I upgraded trusty deps too...

Many thanks for submitting your Pull Request :heart:! 

Please make sure that your PR meets the following requirements:

- [ ] You have read the [contributors guide](https://github.com/kiegroup/kogito-runtimes#contributing-to-kogito)
- [ ] Pull Request title is properly formatted: `KOGITO-XYZ Subject`
- [ ] Pull Request title contains the target branch if not targeting master: `[0.9.x] KOGITO-XYZ Subject`
- [ ] Pull Request contains link to the JIRA issue
- [ ] Pull Request contains link to any dependent or related Pull Request
- [ ] Pull Request contains description of the issue
- [ ] Pull Request does not include fixes for issues other than the main ticket

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>Pull Request</b>  
  Please add comment: <b>Jenkins retest this</b>
 
* <b>Quarkus LTS checks</b>  
  Please add comment: <b>Jenkins run LTS</b>

* <b>Native checks</b>  
  Please add comment: <b>Jenkins run native</b>

</details>

### CODE REVIEW

**Comment by pefernan** [comment]
Unrelated build failure

**Comment by pefernan** [comment]
jenkins retest this please

**Review by paulovmr — APPROVED** [review]

**Comment by pefernan** [comment]
yarn retest this please

**Comment by pefernan** [comment]
jenkins retest this please

**Comment by pefernan** [comment]
Jenkins retest this please

**Comment by pefernan** [comment]
jenkins retest this

**Review by Sara4994 — APPROVED** [review]

**Comment by pefernan** [comment]
jenkins restest this

**Review by kelvah — APPROVED** [review]
Hi @pefernan, trusty is working as expected. Thank you.

**Comment by pefernan** [comment]
@kelvah cool, now let's wait for jenkins to do his part...

**Comment by pefernan** [comment]
jenkins retest this please

**Comment by pefernan** [comment]
jenkins retest this

**Review by jstastny-cz — APPROVED** [review]
LGTM.

**Pull request merged**
