### PR TITLE
Use extended Scalar

### PR DESCRIPTION
**Pull request by cristianonicolai**

### CODE REVIEW

**Review by evacchi — APPROVED** [review]

**Comment by cristianonicolai** [comment]
jenkins please retest this

**Comment by radtriste** [comment]
please merge this one directly on `bump-main-quarkus-2.5.0.Final`

**Comment by radtriste** [comment]
and then create a PR to main

**Comment by radtriste** [comment]
merged and created https://github.com/kiegroup/kogito-apps/pull/1123 so that other repo/branch are taken into account

**Comment by radtriste** [comment]
please work directly on [that one](https://github.com/kiegroup/kogito-apps/pull/1123)

**Pull request merged**
