### PR TITLE
KOGITO-4325 - Remove deprecated skipOriginalJarRename and use quarkus.package.type

### PR DESCRIPTION
**Pull request by r00ta**
JIRA: https://issues.redhat.com/browse/KOGITO-4325

This PR aims to use `quarkus.package.type` to build the uber jar of the kogito-apps and remove the deprecated skipOriginalJarRename

Many thanks for submitting your Pull Request :heart:! 

Please make sure that your PR meets the following requirements:

- [ ] You have read the [contributors guide](https://github.com/kiegroup/kogito-runtimes#contributing-to-kogito)
- [ ] Pull Request title is properly formatted: `KOGITO-XYZ Subject`
- [ ] Pull Request title contains the target branch if not targeting master: `[0.9.x] KOGITO-XYZ Subject`
- [ ] Pull Request contains link to the JIRA issue
- [ ] Pull Request contains link to any dependent or related Pull Request
- [ ] Pull Request contains description of the issue
- [ ] Pull Request does not include fixes for issues other than the main ticket

### CODE REVIEW

**Comment by radtriste** [comment]
so a Maven generation is configured into the `application.properties` of the application ???

**Review by radtriste — APPROVED** [review]

**Comment by danielezonca** [comment]
Can you please make sure the new configuration is compatible with our images?
I don't know if we expect a specific jar name or similar and without the `skipOriginalJarRename` it might break

**Comment by r00ta** [comment]
> skipOriginalJarRename

Hi @danielezonca , the jar name is always the same `<artifact-id>-<version>-runner.jar`. `skipOriginalJarRename` is also deprecated, and looking at the code it looks like it's a leftover of a very old quarkus setup.. https://github.com/quarkusio/quarkus/blob/master/devtools/maven/src/main/java/io/quarkus/maven/BuildMojo.java#L109

**Review by danielezonca — APPROVED** [review]

**Comment by danielezonca** [comment]
> > skipOriginalJarRename
> 
> Hi @danielezonca , the jar name is always the same `<artifact-id>-<version>-runner.jar`. `skipOriginalJarRename` is also deprecated, and looking at the code it looks like it's a leftover of a very old quarkus setup.. https://github.com/quarkusio/quarkus/blob/master/devtools/maven/src/main/java/io/quarkus/maven/BuildMojo.java#L109

Ok thanks for checking

**Pull request merged**
