### PR TITLE
kie-issues#639: Upgrade kie-tools to 0.32

### LINKED ISSUE #639: Upgrade `kie-tools` version in `kogito-apps` to `0.32`
Currently `kogito-apps` is using `kie-tools@0.29` which is bringing some CVE's like [sanitize-url-6.0.0.tgz @ kogito-apps](https://github.com/bamoe/private-bamoe-issues/issues/1061) & [semver-7.3.5.tgz @ kogito-apps](https://github.com/bamoe/private-bamoe-issues/issues/1063), both  CVE's are already fixed in `kie-tools@0.32`.

We should upgrade `kogito-apps` to use the latest `kie-tools@0.32` release so we get rid of the CVE`s.

Also would be nice to align trusty, that's using an even older version of the standalone editors, and align it too.

### PR DESCRIPTION
**Pull request by pefernan**
Closes https://github.com/apache/incubator-kie-issues/issues/639

Many thanks for submitting your Pull Request :heart:! 

Please make sure that your PR meets the following requirements:

- [ ] You have read the [contributors guide](https://github.com/apache/incubator-kie-kogito-runtimes#contributing-to-kogito)
- [ ] Pull Request title is properly formatted: `KOGITO-XYZ Subject`
- [ ] Pull Request title contains the target branch if not targeting main: `[0.9.x] KOGITO-XYZ Subject`
- [ ] Pull Request contains link to the JIRA issue
- [ ] Pull Request contains link to any dependent or related Pull Request
- [ ] Pull Request contains description of the issue
- [ ] Pull Request does not include fixes for issues other than the main ticket

<details>
<summary>
How to replicate CI configuration locally?
</summary>

Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use latest version of the code for each repository.
 
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you need to change multiple repositories and send multiple dependent pull requests related with a change you can easily reproduce the same build by executing it on Github hosted environment or locally in your development environment. See [local execution](https://github.com/kiegroup/github-action-build-chain#local-execution) details to get more information about it.
</details>

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

- for <b>pull request checks</b>  
  Please add comment: <b>Jenkins retest this</b>

- for a <b>specific pull request check</b>  
  Please add comment: <b>Jenkins (re)run [kogito-apps|kogito-examples] tests</b>

- for <b>quarkus branch checks</b>  
  Run checks against Quarkus current used branch  
  Please add comment: <b>Jenkins run quarkus-branch</b>

- for a <b>quarkus branch specific check</b>  
  Run checks against Quarkus current used branch  
  Please add comment: <b>Jenkins (re)run [kogito-apps|kogito-examples] quarkus-branch</b>

- for <b>quarkus main checks</b>  
  Run checks against Quarkus main branch  
  Please add comment: <b>Jenkins run quarkus-main</b>

- for a <b>specific quarkus main check</b>  
  Run checks against Quarkus main branch  
  Please add comment: <b>Jenkins (re)run [kogito-apps|kogito-examples] quarkus-main</b>

- for <b>quarkus lts checks</b>  
  Run checks against Quarkus lts branch  
  Please add comment: <b>Jenkins run quarkus-lts</b>

- for a <b>specific quarkus lts check</b>  
  Run checks against Quarkus lts branch  
  Please add comment: <b>Jenkins (re)run [kogito-apps|kogito-examples] quarkus-lts</b>
 
- for <b>native checks</b>  
  Run native checks  
  Please add comment: <b>Jenkins run native</b>

- for a <b>specific native check</b>  
  Run native checks 
  Please add comment: <b>Jenkins (re)run [kogito-apps|kogito-examples] native</b>

- for <b>native lts checks</b>  
  Run native checks against quarkus lts branch
  Please add comment: <b>Jenkins run native-lts</b>

- for a <b>specific native lts check</b>  
  Run native checks against quarkus lts branch
  Please add comment: <b>Jenkins (re)run [kogito-apps|kogito-examples] native-lts</b>
 
</details>

<details>
<summary>
How to backport a pull request to a different branch?
</summary>

In order to automatically create a **backporting pull request** please add one or more labels having the following format `backport-<branch-name>`, where `<branch-name>` is the name of the branch where the pull request must be backported to (e.g., `backport-7.67.x` to backport the original PR to the `7.67.x` branch).

> **NOTE**: **backporting** is an action aiming to move a change (usually a commit) from a branch (usually the main one) to another one, which is generally referring to a still maintained release branch. Keeping it simple: it is about to move a specific change or a set of them from one branch to another.

Once the original pull request is successfully merged, the automated action will create one backporting pull request per each label (with the previous format) that has been added.

If something goes wrong, the author will be notified and at this point a manual backporting is needed.

> **NOTE**: this automated backporting is triggered whenever a pull request on `main` branch is labeled or closed, but both conditions must be satisfied to get the new PR created.
</details>

<details>
<summary>
Quarkus-3 PR check is failing ... what to do ?
</summary>
The Quarkus 3 check is applying patches from the `.ci/environments/quarkus-3/patches`.

The first patch, called `0001_before_sh.patch`, is generated from Openrewrite `.ci/environments/quarkus-3/quarkus3.yml` recipe. The patch is created to speed up the check. But it may be that some changes in the PR broke this patch.  
No panic, there is an easy way to regenerate it. You just need to comment on the PR:
```
jenkins rewrite quarkus-3
```
and it should, after some minutes (~20/30min) apply a commit on the PR with the patch regenerated.

Other patches were generated manually. If any of it fails, you will need to manually update it... and push your changes.
</details>

### CODE REVIEW

**Comment by pefernan** [comment]
@yesamer @jstastny-cz @paulovmr just sent the PR to see how it goes with the CI. Please don't merge yet

**Comment by kie-ci3** [comment]
**PR job** `#1` was: **UNSTABLE**
Possible explanation: This should be test failures


<details>
<summary><b>Reproducer</b></summary>



build-chain build full_downstream  -f 'https://raw.githubusercontent.com/${AUTHOR:apache}/incubator-kie-kogito-pipelines/${BRANCH:main}/.ci/buildchain-config-pr-cdb.yaml' -o 'bc' -p apache/incubator-kie-kogito-apps -u https://github.com/apache/incubator-kie-kogito-apps/pull/1899 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-apps-pr/job/PR-1899/1/display/redirect

**Test results:**
- PASSED: 2800
- FAILED: 3

Those are the test failures: 
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-apps-pr/job/PR-1899/1/testReport/org.kie.kogito.index.oracle/ProcessDataIndexOracleHttpIT/testProcessInstanceEvents/">org.kie.kogito.index.oracle.ProcessDataIndexOracleHttpIT.testProcessInstanceEvents</a></summary>
java.util.concurrent.CompletionException: java.lang.RuntimeException: Unable to start Quarkus test resource class org.kie.kogito.index.test.quarkus.http.DataIndexOracleHttpQuarkusTestResource
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-apps-pr/job/PR-1899/1/testReport/org.kie.kogito.index.oracle/ProcessDataIndexOracleKafkaIT/testProcessInstanceEvents/">org.kie.kogito.index.oracle.ProcessDataIndexOracleKafkaIT.testProcessInstanceEvents</a></summary>
java.util.concurrent.CompletionException: java.lang.RuntimeException: Unable to start Quarkus test resource class org.kie.kogito.index.test.quarkus.kafka.DataIndexOracleQuarkusKafkaTestResource
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-apps-pr/job/PR-1899/1/testReport/org.kie.kogito.index/ProcessDataIndexOracleIT/testProcessInstanceEvents/">org.kie.kogito.index.ProcessDataIndexOracleIT.testProcessInstanceEvents</a></summary>
Failed to load ApplicationContext
</details>

**Review by yesamer — APPROVED** [review]

**Comment by pefernan** [comment]
@paulovmr @caponetto guys, applied the version update and so far everything looks fine, but there's a problem on the text editor when opening a swf on `kogito-quarkus-serverless-workflow-devui`. I'm digging, but looks like monaco isn't correctly loaded. I may need some assistance :S

**Comment by kie-ci3** [comment]
**PR job** `#5` was: **UNSTABLE**
Possible explanation: This should be test failures


<details>
<summary><b>Reproducer</b></summary>



build-chain build full_downstream  -f 'https://raw.githubusercontent.com/${AUTHOR:apache}/incubator-kie-kogito-pipelines/${BRANCH:main}/.ci/buildchain-config-pr-cdb.yaml' -o 'bc' -p apache/incubator-kie-kogito-apps -u https://github.com/apache/incubator-kie-kogito-apps/pull/1899 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-apps-pr/job/PR-1899/5/display/redirect
See console log:
<details>
<summary><b>Console Logs</b></summary>
find: Ã¢ÂÂ./bc/apache_incubator-kie-kogito-apps/ui-packages/packages/jobs-management/node_modulesÃ¢ÂÂ: No such file or directory<br/>find: Ã¢ÂÂ./bc/apache_incubator-kie-kogito-apps/ui-packages/packages/task-console-webapp/node_modulesÃ¢ÂÂ: No such file or directory<br/>find: Ã¢ÂÂ./bc/apache_incubator-kie-kogito-apps/ui-packages/packages/task-inbox/node_modulesÃ¢ÂÂ: No such file or directory<br/>find: Ã¢ÂÂ./bc/apache_incubator-kie-kogito-apps/ui-packages/packages/management-console-shared/node_modulesÃ¢ÂÂ: No such file or directory<br/>find: Ã¢ÂÂ./bc/apache_incubator-kie-kogito-apps/ui-packages/packages/form-displayer/node_modulesÃ¢ÂÂ: No such file or directory<br/>find: Ã¢ÂÂ./bc/apache_incubator-kie-kogito-apps/ui-packages/packages/custom-dashboard-view/node_modulesÃ¢ÂÂ: No such file or directory<br/>find: Ã¢ÂÂ./bc/apache_incubator-kie-kogito-apps/ui-packages/packages/management-console-webapp/dist-it/fonts/_/_/node_modulesÃ¢ÂÂ: No such file or directory<br/>find: Ã¢ÂÂ./bc/apache_incubator-kie-kogito-apps/ui-packages/packages/management-console-webapp/dist/fonts/_/_/node_modulesÃ¢ÂÂ: No such file or directory<br/>find: Ã¢ÂÂ./bc/apache_incubator-kie-kogito-apps/ui-packages/packages/management-console-webapp/node_modulesÃ¢ÂÂ: No such file or directory<br/>find: Ã¢ÂÂ./bc/apache_incubator-kie-kogito-apps/ui-packages/packages/ouia-tools/node_modulesÃ¢ÂÂ: No such file or directory<br/>find: Ã¢ÂÂ./bc/apache_incubator-kie-kogito-apps/ui-packages/packages/trusty/node_modulesÃ¢ÂÂ: No such file or directory<br/>find: Ã¢ÂÂ./bc/apache_incubator-kie-kogito-apps/ui-packages/packages/task-form/node_modulesÃ¢ÂÂ: No such file or directory<br/>find: Ã¢ÂÂ./bc/apache_incubator-kie-kogito-apps/ui-packages/packages/runtime-tools-dev-ui-webapp/dist/webapp/fonts/_/_/node_modulesÃ¢ÂÂ: No such file or directory<br/>find: Ã¢ÂÂ./bc/apache_incubator-kie-kogito-apps/ui-packages/packages/runtime-tools-dev-ui-webapp/node_modulesÃ¢ÂÂ: No such file or directory<br/>find: Ã¢ÂÂ./bc/apache_incubator-kie-kogito-apps/ui-packages/packages/cloud-event-form/node_modulesÃ¢ÂÂ: No such file or directory<br/>find: Ã¢ÂÂ./bc/apache_incubator-kie-kogito-apps/ui-packages/packages/monitoring/node_modulesÃ¢ÂÂ: No such file or directory<br/>find: Ã¢ÂÂ./bc/apache_incubator-kie-kogito-apps/ui-packages/packages/consoles-common/node_modulesÃ¢ÂÂ: No such file or directory<br/>find: Ã¢ÂÂ./bc/apache_incubator-kie-kogito-apps/ui-packages/packages/cypress-ouia/node_modulesÃ¢ÂÂ: No such file or directory<br/>find: Ã¢ÂÂ./bc/apache_incubator-kie-kogito-apps/ui-packages/packages/process-list/node_modulesÃ¢ÂÂ: No such file or directory<br/>find: Ã¢ÂÂ./bc/apache_incubator-kie-kogito-apps/ui-packages/packages/process-details/node_modulesÃ¢ÂÂ: No such file or directory<br/>find: Ã¢ÂÂ./bc/apache_incubator-kie-kogito-apps/ui-packages/packages/components-common/node_modulesÃ¢ÂÂ: No such file or directory<br/>find: Ã¢ÂÂ./bc/apache_incubator-kie-kogito-apps/ui-packages/packages/process-definition-list/node_modulesÃ¢ÂÂ: No such file or directory<br/>find: Ã¢ÂÂ./bc/apache_incubator-kie-kogito-apps/kogito-quarkus-serverless-workflow-devui-parent/kogito-quarkus-serverless-workflow-devui-deployment/target/classes/dev-static/webapp/fonts/_/_/node_modulesÃ¢ÂÂ: No such file or directory<br/>find: Ã¢ÂÂ./bc/apache_incubator-kie-kogito-apps/management-console/target/classes/META-INF/resources/fonts/_/_/node_modulesÃ¢ÂÂ: No such file or directory<br/>find: Ã¢ÂÂ./bc/apache_incubator-kie-kogito-apps/runtime-tools-quarkus-extension-parent/runtime-tools-quarkus-extension-deployment/target/classes/dev-static/webapp/fonts/_/_/node_modulesÃ¢ÂÂ: No such file or directory<br/>+ true<br/>[Pipeline] junit<br/>Recording test results<br/>[Checks API] No suitable checks publisher found.<br/>[Pipeline] archiveArtifacts<br/>Archiving artifacts<br/>[Pipeline] }<br/>[Pipeline] // withCredentials<br/>[Pipeline] }<br/>Deleting 1 temporary files<br/>[Pipeline] // configFileProvider<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Sonar analysis)<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] echo<br/>Got build result UNSTABLE<br/>[Pipeline] sh<br/>+ wget --no-check-certificate -qO - 'https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-apps-pr/job/PR-1899/5/api/json?depth=0'<br/>[Pipeline] readJSON<br/>[Pipeline] sh<br/>+ wget --no-check-certificate -qO - https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-apps-pr/job/PR-1899/5/consoleText<br/>+ tail -n 50<br/>
</details>

**Review by paulovmr — APPROVED** [review]

**Comment by kie-ci3** [comment]
**PR job** `#8` was: **UNSTABLE**
Possible explanation: This should be test failures


<details>
<summary><b>Reproducer</b></summary>



build-chain build full_downstream  -f 'https://raw.githubusercontent.com/${AUTHOR:apache}/incubator-kie-kogito-pipelines/${BRANCH:main}/.ci/buildchain-config-pr-cdb.yaml' -o 'bc' -p apache/incubator-kie-kogito-apps -u https://github.com/apache/incubator-kie-kogito-apps/pull/1899 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-apps-pr/job/PR-1899/8/display/redirect

**Test results:**
- PASSED: 2819
- FAILED: 3

Those are the test failures: 
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-apps-pr/job/PR-1899/8/testReport/org.kie.kogito.index.oracle/ProcessDataIndexOracleKafkaIT/testProcessInstanceEvents/">org.kie.kogito.index.oracle.ProcessDataIndexOracleKafkaIT.testProcessInstanceEvents</a></summary>
java.util.concurrent.CompletionException: java.lang.RuntimeException: Unable to start Quarkus test resource class org.kie.kogito.index.test.quarkus.kafka.DataIndexOracleQuarkusKafkaTestResource
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-apps-pr/job/PR-1899/8/testReport/org.kie.kogito.index/ProcessDataIndexInfinispanIT/testProcessInstanceEvents/">org.kie.kogito.index.ProcessDataIndexInfinispanIT.testProcessInstanceEvents</a></summary>
1 expectation failed.<br/>JSON path errors doesn't match.<br/>Expected: null<br/>  Actual: <[{message=Exception while fetching data (/UserTaskInstanceCommentUpdate) : Index 0 out of bounds for length 0, locations=[{line=1, column=12}], path=[UserTaskInstanceCommentUpdate], extensions={classification=DataFetchingException}}]><br/>
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-apps-pr/job/PR-1899/8/testReport/org.kie.kogito.index/ProcessDataIndexMongoDBIT/testProcessInstanceEvents/">org.kie.kogito.index.ProcessDataIndexMongoDBIT.testProcessInstanceEvents</a></summary>
1 expectation failed.<br/>JSON path data.UserTaskInstances[0].potentialGroups[0] doesn't match.<br/>Expected: managers<br/>  Actual: null<br/>
</details>

**Comment by pefernan** [comment]
test failures not related to the changes

**Comment by yesamer** [comment]
Merging: Tests failures are unrelated.

**Pull request merged**
