### PR TITLE
KOGITO-2097: Task Console Quarkus App

### PR DESCRIPTION
**Pull request by pefernan**
- Adding the Task Console Quarkus App
- Aligning Task Console Webpack configs with management console for a correct displaying of static images.
- Modified _ServerUnavailable_ to accept an _alt_ text.

This is part of an ensemble, please merge with:
https://github.com/kiegroup/kogito-runtimes/pull/603
https://github.com/kiegroup/kogito-apps/pull/303

Many thanks for submitting your Pull Request :heart:! 

Please make sure that your PR meets the following requirements:

- [ ] You have read the [contributors guide](https://github.com/kiegroup/kogito-runtimes#contributing-to-kogito)
- [ ] Pull Request title is properly formatted: `KOGITO-XYZ Subject`
- [ ] Pull Request title contains the target branch if not targeting master: `[0.9.x] KOGITO-XYZ Subject`
- [ ] Pull Request contains link to the JIRA issue
- [ ] Pull Request contains link to any dependent or related Pull Request
- [ ] Pull Request contains description of the issue
- [ ] Pull Request does not include fixes for issues other than the main ticket

### CODE REVIEW

**Review by jstastny-cz — COMMENTED** [review]
@pefernan the changes in ui-packages/packages ... are they actually linked to the quarkus app? I don't see the connection.

**Comment by pefernan** [comment]
@jstastny-cz not directly related but needed.

- I had to change the webpack settings because the static images (Task Console logo & Avatar icon) weren't shown when running the Quarkus app.
- The index.tsx because it wasn't working fine with no data-index conected. So I copied what's in Management Console.
- _ServerUnavailable_ was working fine but it was showing an alt text saying _Management Console Logo_, since it's on common I thought it would be best if the alt text could be configured, so I changed it to allow configure the alt text too.

**Comment by jstastny-cz** [comment]
Ok, I have issue with the last point only - it is a different issue, right? To limit the level of surprise in reviews and when pulling from master I'd do similar things separately. To have the git history telling the full story.

Just a nitpick - I won't block the review because of it if others are fine with that. Just something we should keep in mind.

**Comment by pefernan** [comment]
@jstastny-cz well yea a different issue maybe, but when the logo wasn't appearing on Task Console the _Managment Console Logo_ text was appearing instead and I was feeling that I had to solve it.

**Comment by pefernan** [comment]
jenkins retest this please

**Comment by pefernan** [comment]
jenkins retest this please

**Comment by pefernan** [comment]
jenkins retest this

**Comment by pefernan** [comment]
Jenkins retest this please

**Comment by pefernan** [comment]
Jenkins retest this

**Review by cristianonicolai — APPROVED** [review]

**Review by nmirasch — APPROVED** [review]

**Review by jstastny-cz — APPROVED** [review]

**Pull request merged**
