### PR TITLE
PLANNER-2479: Review introduced Task Assigning Service quick fix

### PR DESCRIPTION
**Pull request by wmedvede**
Many thanks for submitting your Pull Request :heart:! 

Please make sure that your PR meets the following requirements:

- [X] You have read the [contributors guide](https://github.com/kiegroup/kogito-runtimes#contributing-to-kogito)
- [X] Pull Request title is properly formatted: `KOGITO-XYZ Subject`
- [X] Pull Request title contains the target branch if not targeting master: `[0.9.x] KOGITO-XYZ Subject`
- [X] Pull Request contains link to the JIRA issue
- [X] Pull Request contains link to any dependent or related Pull Request
- [X] Pull Request contains description of the issue
- [X] Pull Request does not include fixes for issues other than the main ticket

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>Pull Request</b>  
  Please add comment: <b>Jenkins retest this</b>
 
* <b>Quarkus LTS checks</b>  
  Please add comment: <b>Jenkins run LTS</b>

* <b>Native checks</b>  
  Please add comment: <b>Jenkins run native</b>

</details>

### CODE REVIEW

**Comment by wmedvede** [comment]
Jenkins please retest this

**Comment by wmedvede** [comment]
Hi @ge0ffrey @rsynek would you mind review this PR?
Thanks!

**Comment by wmedvede** [comment]
Jenkins please retest this

**Comment by wmedvede** [comment]
Jenkins please retest this

**Review by rsynek — APPROVED** [review]

**Comment by rsynek** [comment]
@wmedvede there is an ongoing network incident in the Jenkins CI environment.

**Comment by wmedvede** [comment]
> @wmedvede there is an ongoing network incident in the Jenkins CI environment.

yeah, I've heard something. Let's see if I can get the a green before the programmed master -> main branches renaming....

**Comment by wmedvede** [comment]
Jenkins please retest this

**Comment by wmedvede** [comment]
Jenkins please retest this

**Comment by Ginxo** [comment]
converted to draft. Please do not merge it yet, checking PR check error. Thanks.

**Comment by Ginxo** [comment]
tested and back to `ready for review`. Thanks

**Comment by wmedvede** [comment]
Hi @Ginxo I can see that this is green now, however I'm a bit confused regarding the commits you added to this PR, since it look like they affect a file ci-pr.yml that is not related with the TaskAssigningService.

Should I've just "squash and merge" by incorporating your commits too?

**Pull request merged**
