### PR TITLE
Fix Quarkus reflection configuration for native execution.

### PR DESCRIPTION
**Pull request by manstis**
Many thanks for submitting your Pull Request :heart:! 

Please make sure that your PR meets the following requirements:

- [x] You have read the [contributors guide](https://github.com/kiegroup/kogito-runtimes#contributing-to-kogito)
- [x] Pull Request title is properly formatted: `KOGITO-XYZ Subject`
- [x] Pull Request title contains the target branch if not targeting main: `[0.9.x] KOGITO-XYZ Subject`
- [x] Pull Request contains link to the JIRA issue
- [x] Pull Request contains link to any dependent or related Pull Request
- [x] Pull Request contains description of the issue
- [x] Pull Request does not include fixes for issues other than the main ticket

<details>
<summary>
How to replicate CI configuration locally?
</summary>

Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use latest version of the code for each repository.
 
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you need to change multiple repositories and send multiple dependent pull requests related with a change you can easily reproduce the same build by executing it on Github hosted environment or locally in your development environment. See [local execution](https://github.com/kiegroup/github-action-build-chain#local-execution) details to get more information about it.
</details>

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>Pull Request</b>  
  Please add comment: <b>Jenkins retest this</b>
 
* <b>Quarkus LTS checks</b>  
  Please add comment: <b>Jenkins run LTS</b>

* <b>Native checks</b>  
  Please add comment: <b>Jenkins run native</b>

</details>

### CODE REVIEW

**Review by tarilabs — APPROVED** [review]
@manstis you might consider embedding this information inside of TrustyAI similarly to what we did here:
https://github.com/kiegroup/drools/blob/main/kie-dmn/kie-dmn-model/src/main/resources/META-INF/native-image/org.kie/kie-dmn-model/reflect-config.json

There is a JUnit test which make sure all the classes from Jandex which "you know" are part of "API" are included in the JSON. I am pretty positive you can do analogously for TrustyAI API object too.
/cc @r00ta @danielezonca

**Comment by manstis** [comment]
> @manstis you might consider embedding this information inside of TrustyAI similarly to what we did here: https://github.com/kiegroup/drools/blob/main/kie-dmn/kie-dmn-model/src/main/resources/META-INF/native-image/org.kie/kie-dmn-model/reflect-config.json
> 

@tarilabs We do already....  but in a module on which you do not depend (for reasons I do not know - why it's in the given module not why you don't depend on it). I'll make a JIRA to move it from the module in which it currently resides to a module on which you do depend.

**Comment by tarilabs** [comment]
if you prefer to change these dependency I'm all ears:

https://github.com/kiegroup/kogito-apps/blame/3bea57f763771836fe74d8c5585187e734ad7856/jitexecutor/jitexecutor-dmn/pom.xml#L58-L76

**Comment by manstis** [comment]
Jenkins run native

**Comment by manstis** [comment]
Merging as all JIT modules are green (and this PR was to fix the JIT modules):
```
[2021-12-03T18:18:28.004Z] [INFO] Kogito Apps :: JIT Executor ........................ SUCCESS [  0.047 s]
[2021-12-03T18:18:28.004Z] [INFO] Kogito Apps :: JIT Executor DMN .................... SUCCESS [ 15.247 s]
[2021-12-03T18:18:28.004Z] [INFO] Kogito Apps :: JIT Executor Runner ................. SUCCESS [02:54 min]
```

**Pull request merged**
