### PR TITLE
KOGITO-1941 Increase timeout

### PR DESCRIPTION
**Pull request by cristianonicolai**

### CODE REVIEW

**Comment by cristianonicolai** [comment]
@tiagodolphine just saw this one again, lets see if increasing the timeout helps or we should either review or disable the test again.

**Comment by cristianonicolai** [comment]
jenkins please retest this

**Review by tiagodolphine — APPROVED** [review]
+1, it is difficult to make the async IT tests to be green, probably jenkins get overloaded in some situations that require having greater timeouts in the tests :(, not ideal but unless we mock the system clock in some way, we need to do this.

**Comment by cristianonicolai** [comment]
Jenkins rerun apps tests

**Comment by cristianonicolai** [comment]
Jenkins rerun apps tests

**Comment by cristianonicolai** [comment]
Jenkins rerun apps tests

**Pull request merged**
