### PR TITLE
KOGITO-5743 - Review native tests

### PR DESCRIPTION
**Pull request by cristianonicolai**

### CODE REVIEW

**Comment by cristianonicolai** [comment]
@tiagodolphine native tests were using injection, so my guess is that it never actually worked. If jobs service is meant to run in native mode, I guess we need to do a follow up to implement these.

**Comment by cristianonicolai** [comment]
Jenkins run native

**Comment by tiagodolphine** [comment]
> @tiagodolphine native tests were using injection, so my guess is that it never actually worked. If jobs service is meant to run in native mode, I guess we need to do a follow up to implement these.

right, probably they were not working, TBH we never focused to make it run in native build, since it is supposed to be a long running service, if we wanna provide it to run in native mode probably we need to review a few points to make it work, but better to file a Jira for it.

**Review by tiagodolphine — APPROVED** [review]

**Comment by cristianonicolai** [comment]
Jenkins run native

**Comment by cristianonicolai** [comment]
jenkins please retest this

**Comment by cristianonicolai** [comment]
Jenkins run native

**Review by radtriste — APPROVED** [review]

**Comment by cristianonicolai** [comment]
merging this as it already improves/fixes some modules. @r00ta is helping to review the missing fix for trusty service

**Pull request merged**
