### PR TITLE
FAI-692: Integration of regularizers into SHAP

### PR DESCRIPTION
**Pull request by RobGeada**
https://issues.redhat.com/browse/FAI-692

In cases where the number of possible feature coalitions greatly outnumber the number of available samples, some means of regularization must be employed in the linear regression to ensure that the results are reasonably accurate. Now that methods for performing Least Angle Regression Path regularization are included via the FAI-660 merge, these features can now be integrated into SHAP.

 
Many thanks for submitting your Pull Request :heart:! 

Please make sure that your PR meets the following requirements:

- [ ] You have read the [contributors guide](https://github.com/kiegroup/kogito-runtimes#contributing-to-kogito)
- [ ] Pull Request title is properly formatted: `KOGITO-XYZ Subject`
- [ ] Pull Request title contains the target branch if not targeting main: `[0.9.x] KOGITO-XYZ Subject`
- [ ] Pull Request contains link to the JIRA issue
- [ ] Pull Request contains link to any dependent or related Pull Request
- [ ] Pull Request contains description of the issue
- [ ] Pull Request does not include fixes for issues other than the main ticket

<details>
<summary>
How to replicate CI configuration locally?
</summary>

Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use latest version of the code for each repository.
 
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you need to change multiple repositories and send multiple dependent pull requests related with a change you can easily reproduce the same build by executing it on Github hosted environment or locally in your development environment. See [local execution](https://github.com/kiegroup/github-action-build-chain#local-execution) details to get more information about it.
</details>

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>Pull Request</b>  
  Please add comment: <b>Jenkins retest this</b>
 
* <b>Quarkus LTS checks</b>  
  Please add comment: <b>Jenkins run LTS</b>

* <b>Native checks</b>  
  Please add comment: <b>Jenkins run native</b>

</details>

### CODE REVIEW

**Comment by kie-ci1** [comment]
**PR job** #542 was: **ABORTED**
Possible explanation: Most probably a timeout, please review


**Test results:**
- PASSED: 2396
- FAILED: 0

Those are the test failures: none

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-apps.tests.kogito-apps/542/display/redirect or see console log:
```spoiler Console Logs
[2022-01-25T14:48:17.255Z] [INFO] --------------------------------[ jar ]---------------------------------
[2022-01-25T14:48:17.255Z] [INFO] 
[2022-01-25T14:48:17.255Z] [INFO] --- maven-enforcer-plugin:3.0.0-M2:enforce (enforce-versions) @ jitexecutor-runner ---
[2022-01-25T14:48:17.255Z] [INFO] Skipping Rule Enforcement.
[2022-01-25T14:48:17.255Z] [INFO] 
[2022-01-25T14:48:17.255Z] [INFO] --- maven-enforcer-plugin:3.0.0-M2:enforce (enforce-java-version) @ jitexecutor-runner ---
[2022-01-25T14:48:17.255Z] [INFO] Skipping Rule Enforcement.
[2022-01-25T14:48:17.255Z] [INFO] 
[2022-01-25T14:48:17.255Z] [INFO] --- maven-enforcer-plugin:3.0.0-M2:enforce (enforce-maven-version) @ jitexecutor-runner ---
[2022-01-25T14:48:17.255Z] [INFO] Skipping Rule Enforcement.
[2022-01-25T14:48:17.255Z] [INFO] 
[2022-01-25T14:48:17.255Z] [INFO] --- maven-checkstyle-plugin:3.0.0:check (default) @ jitexecutor-runner ---
[2022-01-25T14:48:17.255Z] [INFO] 
[2022-01-25T14:48:17.255Z] [INFO] --- maven-antrun-plugin:1.8:run (default) @ jitexecutor-runner ---
[2022-01-25T14:48:17.255Z] [INFO] Executing tasks
[2022-01-25T14:48:17.255Z] 
[2022-01-25T14:48:17.255Z] main:
[2022-01-25T14:48:17.255Z]      [echo] Generating JaCoCo Reports
[2022-01-25T14:48:17.255Z]     [mkdir] Created dir: /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-apps.tests.kogito-apps/bc/kiegroup_kogito_apps/kogito-apps/jitexecutor/jitexecutor-runner/target/site/jacoco
[2022-01-25T14:48:17.255Z]    [report] Loading execution data file /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-apps.tests.kogito-apps/bc/kiegroup_kogito_apps/kogito-apps/target/jacoco.exec
[2022-01-25T14:48:27.266Z]    [report] Writing bundle 'jitexecutor-runner' with 724 classes
[2022-01-25T14:48:35.649Z] Cancelling nested steps due to timeout
[2022-01-25T14:48:35.653Z] Sending interrupt signal to process
[2022-01-25T14:48:37.587Z] + test 143 -eq 0
[2022-01-25T14:48:37.596Z] script returned exit code 1
[Pipeline] }
[Pipeline] // withCredentials
[Pipeline] }
[Pipeline] // dir
[Pipeline] }
[Pipeline] // script
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
[Pipeline] // stage
[Pipeline] stage
[Pipeline] { (check space after build)
Stage "check space after build" skipped due to earlier failure(s)
[Pipeline] }
[Pipeline] // stage
[Pipeline] stage
[Pipeline] { (Declarative: Post Actions)
[Pipeline] script
[Pipeline] {
[Pipeline] sh
[2022-01-25T14:48:38.415Z] + wget --no-check-certificate -qO - https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-apps.tests.kogito-apps/542/api/json
[Pipeline] readJSON
[Pipeline] sh
[2022-01-25T14:48:39.679Z] + wget --no-check-certificate -qO - https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-apps.tests.kogito-apps/542/consoleText
[2022-01-25T14:48:39.679Z] + tail -n 50

```

**Comment by RobGeada** [comment]
jenkins retest this please?

**Review by tteofili — APPROVED** [review]
thanks @RobGeada it looks good to me! (great job!)

**Review by ruivieira — APPROVED** [review]
LGTM, thanks @RobGeada!

**Pull request merged**
