### PR TITLE
KOGITO-4674 - Fix intermittent test failure avoiding NPE when checkin…

### PR DESCRIPTION
**Pull request by cristianonicolai**
…g collection size

### CODE REVIEW

**Comment by radtriste** [comment]
is that a follow-up of https://github.com/kiegroup/kogito-apps/pull/701 ?

**Comment by cristianonicolai** [comment]
@radtriste yep, just saw the exception in another PR

**Review by radtriste — APPROVED** [review]

**Review by nmirasch — APPROVED** [review]

**Comment by nmirasch** [comment]
jenkins please retest this

**Comment by cristianonicolai** [comment]
jenkins please retest this

**Comment by cristianonicolai** [comment]
jenkins please retest this

**Pull request merged**
