### PR TITLE
KOGITO-3178 - inject baseURL at runtime into trusty-ui application

### PR DESCRIPTION
**Pull request by r00ta**
The aim of this PR is to allow the injection at runtime of the trusty service baseurl. 

Many thanks for submitting your Pull Request :heart:! 

Please make sure that your PR meets the following requirements:

- [x] You have read the [contributors guide](https://github.com/kiegroup/kogito-runtimes#contributing-to-kogito)
- [x] Pull Request title is properly formatted: `KOGITO-XYZ Subject`
- [x] Pull Request title contains the target branch if not targeting master: `[0.9.x] KOGITO-XYZ Subject`
- [x] Pull Request contains link to the JIRA issue
- [x] Pull Request contains link to any dependent or related Pull Request
- [x] Pull Request contains description of the issue
- [x] Pull Request does not include fixes for issues other than the main ticket

### CODE REVIEW

**Review by danielezonca — COMMENTED** [review]
LGTM :+1:

**Review by kelvah — APPROVED** [review]

**Review by jiripetrlik — APPROVED** [review]

**Comment by r00ta** [comment]
jenkins retest this please

**Comment by r00ta** [comment]
jenkins retest this please

**Comment by danielezonca** [comment]
jenkins retest this please

**Review by danielezonca — APPROVED** [review]

**Pull request merged**
