### PR TITLE
FAI-672: Discrepancy between explainability "preview" chart and "complete" chart 

### PR DESCRIPTION
**Pull request by kelvah**
JIRA: https://issues.redhat.com/browse/FAI-672

When switching from an outcome with many features scores (positives or negatives > 5) to one with only a few, the `topFeaturesScoresBySign` value returned by `useFeaturesScores` is not properly cleaned. The explanation section will then display the values of the previous outcome.

It's possible to see an example with the fixed behavior by opening the last decision in the mocked set and switching between the "Mortgage approval" and "Risk score" outcomes inside the outcome details page.

<details>
<summary>
How to replicate CI configuration locally?
</summary>

Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use latest version of the code for each repository.
 
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you need to change multiple repositories and send multiple dependent pull requests related with a change you can easily reproduce the same build by executing it on Github hosted environment or locally in your development environment. See [local execution](https://github.com/kiegroup/github-action-build-chain#local-execution) details to get more information about it.
</details>

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>Pull Request</b>  
  Please add comment: <b>Jenkins retest this</b>
 
* <b>Quarkus LTS checks</b>  
  Please add comment: <b>Jenkins run LTS</b>

* <b>Native checks</b>  
  Please add comment: <b>Jenkins run native</b>

</details>

### CODE REVIEW

**Review by manstis — APPROVED** [review]
LGTM and, looking at `Explanation.tsx`, it's clear how the fix works.

**Comment by kelvah** [comment]
Jenkins please retest this

**Review by sjamboro — COMMENTED** [review]
@kelvah Hi, I can approve that I can not see problem when I switch "Mortal Approval" and "Risk Score", but I can see a blank "Top features score chart" when I switch "Recommended Loan Products" and "Cheese manufacturer". Is it similar problem or another JIRA?

**Comment by kelvah** [comment]
hi @sjamboro, Thank you for spotting it. I think it's caused by some missing mocked data for saliencies. I'll fix it here.

**Comment by kelvah** [comment]
> @kelvah Hi, I can approve that I can not see problem when I switch "Mortal Approval" and "Risk Score", but I can see a blank "Top features score chart" when I switch "Recommended Loan Products" and "Cheese manufacturer". Is it similar problem or another JIRA?

@sjamboro fixed now.

**Comment by sjamboro** [comment]
@kelvah thank you I will check it.

**Comment by sjamboro** [comment]
@kelvah I have got same results: 
image

**Comment by kelvah** [comment]
@sjamboro Everything seems working from here. Could it be a browser cache issue? Could you try cleaning it?

**Comment by sjamboro** [comment]
@kelvah it seems that it works right now

**Review by sjamboro — APPROVED** [review]

**Pull request merged**
