### PR TITLE
Fix skipUI

### PR DESCRIPTION
**Pull request by radtriste**
Problem introduced by https://github.com/kiegroup/kogito-apps/pull/1314

Many thanks for submitting your Pull Request :heart:! 

Please make sure that your PR meets the following requirements:

- [ ] You have read the [contributors guide](https://github.com/kiegroup/kogito-runtimes#contributing-to-kogito)
- [ ] Pull Request title is properly formatted: `KOGITO-XYZ Subject`
- [ ] Pull Request title contains the target branch if not targeting main: `[0.9.x] KOGITO-XYZ Subject`
- [ ] Pull Request contains link to the JIRA issue
- [ ] Pull Request contains link to any dependent or related Pull Request
- [ ] Pull Request contains description of the issue
- [ ] Pull Request does not include fixes for issues other than the main ticket

<details>
<summary>
How to replicate CI configuration locally?
</summary>

Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use latest version of the code for each repository.
 
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you need to change multiple repositories and send multiple dependent pull requests related with a change you can easily reproduce the same build by executing it on Github hosted environment or locally in your development environment. See [local execution](https://github.com/kiegroup/github-action-build-chain#local-execution) details to get more information about it.
</details>

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>Pull Request</b>  
  Please add comment: <b>Jenkins retest this</b>
 
* <b>Quarkus LTS checks</b>  
  Please add comment: <b>Jenkins run LTS</b>

* <b>Native checks</b>  
  Please add comment: <b>Jenkins run native</b>

</details>

### CODE REVIEW

**Comment by radtriste** [comment]
opened https://github.com/kiegroup/kogito-runtimes/pull/2181 as well to test the downstream build

**Review by jstastny-cz — APPROVED** [review]
Looks good. Thanks.

**Comment by kie-ci1** [comment]
**(tests) - kogito-apps job** `#866` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-apps.tests.kogito-apps/866/display/redirect or see console log:
<details>
<summary><b>Console Logs</b></summary>
using GIT_SSH to set credentials SSH: kie-ci service account with access to jboss-integration private github space<br/>[INFO] Currently running in a labeled security context<br/> > /usr/bin/chcon --type=ssh_home_t /tmp/jenkins-gitclient-ssh2346963007292155530.key<br/> > git ls-remote -h https://github.com/kiegroup/jenkins-pipeline-shared-libraries # timeout=10<br/>Found match: refs/heads/main revision 21afeeac35a851b46d694688c2562d914fab8e63<br/>The recommended git tool is: NONE<br/>using credential kie-ci-user-key<br/> > git rev-parse --resolve-git-dir /var/lib/jenkins/jobs/KIE/jobs/kogito/jobs/main/jobs/pullrequest/jobs/kogito-apps.tests.kogito-apps/workspace@libs/d03f8b53ef89e88ec2b15428a250a4b1fb7910bfcdd3e1c33e4e95c3adb758bb/.git # timeout=10<br/>Fetching changes from the remote Git repository<br/> > git config remote.origin.url https://github.com/kiegroup/jenkins-pipeline-shared-libraries # timeout=10<br/>Fetching without tags<br/>Fetching upstream changes from https://github.com/kiegroup/jenkins-pipeline-shared-libraries<br/> > git --version # timeout=10<br/> > git --version # 'git version 1.8.3.1'<br/>using GIT_SSH to set credentials SSH: kie-ci service account with access to jboss-integration private github space<br/>[INFO] Currently running in a labeled security context<br/> > /usr/bin/chcon --type=ssh_home_t /var/lib/jenkins/jobs/KIE/jobs/kogito/jobs/main/jobs/pullrequest/jobs/kogito-apps.tests.kogito-apps/workspace@libs/d03f8b53ef89e88ec2b15428a250a4b1fb7910bfcdd3e1c33e4e95c3adb758bb@tmp/jenkins-gitclient-ssh2330464060504694668.key<br/> > git fetch --no-tags --progress https://github.com/kiegroup/jenkins-pipeline-shared-libraries +refs/heads/*:refs/remotes/origin/* # timeout=10<br/>Checking out Revision 21afeeac35a851b46d694688c2562d914fab8e63 (main)<br/> > git config core.sparsecheckout # timeout=10<br/> > git checkout -f 21afeeac35a851b46d694688c2562d914fab8e63 # timeout=10<br/>Commit message: "pmebuild cleanScript (#188)"<br/> > git rev-list --no-walk 21afeeac35a851b46d694688c2562d914fab8e63 # timeout=10<br/>[Pipeline] Start of Pipeline<br/>[Pipeline] node<br/>Still waiting to schedule task<br/>Waiting for next available executor on ‘kie-rhel7&&kie-mem16g&&!master’<br/>Running on rhos-01-kie-psi-rhel7-xlarge-268 in /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-apps.tests.kogito-apps<br/>[Pipeline] {<br/>[Pipeline] stage<br/>[Pipeline] { (Declarative: Checkout SCM)<br/>[Pipeline] checkout<br/>The recommended git tool is: NONE<br/>using credential kie-ci<br/>Cloning the remote Git repository<br/>Cloning repository https://github.com/kiegroup/kogito-pipelines.git<br/>Avoid second fetch<br/>Checking out Revision b844f47b3febcc273841e554486088d18b72b704 (origin/main)<br/> > git init /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-apps.tests.kogito-apps # timeout=10<br/>Fetching upstream changes from https://github.com/kiegroup/kogito-pipelines.git<br/> > git --version # timeout=10<br/> > git --version # 'git version 2.34.1'<br/>using GIT_ASKPASS to set credentials PSSWD: kie-ci service account with access to jboss-integration private github space<br/> > git fetch --tags --force --progress -- https://github.com/kiegroup/kogito-pipelines.git +refs/heads/*:refs/remotes/origin/* # timeout=10<br/> > git config remote.origin.url https://github.com/kiegroup/kogito-pipelines.git # timeout=10<br/> > git config --add remote.origin.fetch +refs/heads/*:refs/remotes/origin/* # timeout=10<br/> > git rev-parse origin/main^{commit} # timeout=10<br/> > git config core.sparsecheckout # timeout=10<br/> > git checkout -f b844f47b3febcc273841e554486088d18b72b704 # timeout=10<br/>Commit message: "Correct Repo seeds (#425)"<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] withEnv<br/>[Pipeline] {<br/>[Pipeline] withEnv<br/>[Pipeline] {<br/>[Pipeline] timestamps<br/>[Pipeline] {<br/>[Pipeline] timeout<br/>[2022-05-03T15:40:41.923Z] Timeout set to expire in 3 hr 30 min<br/>[Pipeline] {<br/>[Pipeline] stage<br/>[Pipeline] { (Declarative: Tool Install)<br/>[Pipeline] tool<br/>[2022-05-03T15:40:42.032Z] Installing NodeJS from /var/lib/jenkins/caches/nodejs/LINUX/amd64/12.16.3.tar.gz to /home/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/nodejs-12.16.3 on rhos-01-kie-psi-rhel7-xlarge-268<br/>[Pipeline] envVarsForTool<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] withEnv<br/>[Pipeline] {<br/>[Pipeline] stage<br/>[Pipeline] { (Initialize)<br/>[Pipeline] tool<br/>[Pipeline] envVarsForTool<br/>[Pipeline] withEnv<br/>[Pipeline] {<br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] sh<br/>[2022-05-03T15:40:46.860Z] + printenv<br/>[Pipeline] archiveArtifacts<br/>[2022-05-03T15:40:47.007Z] Archiving artifacts<br/>[Pipeline] }<br/>[Pipeline] // script<br/>[Pipeline] }<br/>[Pipeline] // withEnv<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (check space before build)<br/>[Pipeline] tool<br/>[Pipeline] envVarsForTool<br/>[Pipeline] withEnv<br/>[Pipeline] {<br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] dir<br/>[2022-05-03T15:40:47.706Z] Running in /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-apps.tests.kogito-apps<br/>[Pipeline] {<br/>[Pipeline] echo<br/>[2022-05-03T15:40:47.738Z] [INFO] space left on the machine<br/>[Pipeline] sh<br/>[2022-05-03T15:40:48.025Z] + df -h<br/>[2022-05-03T15:40:48.026Z] Filesystem      Size  Used Avail Use% Mounted on<br/>[2022-05-03T15:40:48.026Z] devtmpfs        7.8G     0  7.8G   0% /dev<br/>[2022-05-03T15:40:48.026Z] tmpfs           7.8G     0  7.8G   0% /dev/shm<br/>[2022-05-03T15:40:48.026Z] tmpfs           7.8G   17M  7.8G   1% /run<br/>[2022-05-03T15:40:48.026Z] tmpfs           7.8G     0  7.8G   0% /sys/fs/cgroup<br/>[2022-05-03T15:40:48.026Z] /dev/vda1        80G   18G   63G  23% /<br/>[2022-05-03T15:40:48.026Z] tmpfs           1.6G     0  1.6G   0% /run/user/1000<br/>[Pipeline] echo<br/>[2022-05-03T15:40:48.116Z] [INFO] space of /home/jenkins<br/>[Pipeline] sh<br/>[2022-05-03T15:40:48.409Z] + du -h -d1 /home/jenkins<br/>[2022-05-03T15:40:48.410Z] 4.0K	/home/jenkins/.ssh<br/>[2022-05-03T15:40:48.410Z] 0	/home/jenkins/go<br/>[2022-05-03T15:40:48.410Z] 8.0K	/home/jenkins/.vnc<br/>[2022-05-03T15:40:48.410Z] 8.0K	/home/jenkins/.m2<br/>[2022-05-03T15:40:48.410Z] 2.1G	/home/jenkins/git-repos<br/>[2022-05-03T15:40:48.410Z] 8.0K	/home/jenkins/.config<br/>[2022-05-03T15:40:48.410Z] 4.0K	/home/jenkins/.cekit<br/>[2022-05-03T15:40:48.410Z] 80M	/home/jenkins/virtenvs<br/>[2022-05-03T15:40:48.410Z] 30M	/home/jenkins/remoting<br/>[2022-05-03T15:40:48.410Z] 0	/home/jenkins/.cache<br/>[2022-05-03T15:40:48.410Z] 2.2M	/home/jenkins/workspace<br/>[2022-05-03T15:40:48.410Z] 0	/home/jenkins/.pki<br/>[2022-05-03T15:40:48.410Z] 81M	/home/jenkins/tools<br/>[2022-05-03T15:40:48.410Z] 0	/home/jenkins/caches<br/>[2022-05-03T15:40:48.410Z] 2.3G	/home/jenkins<br/>[Pipeline] echo<br/>[2022-05-03T15:40:48.434Z] [INFO] space of workspace<br/>[Pipeline] sh<br/>[2022-05-03T15:40:48.735Z] + du -h -d3 /home/jenkins/workspace<br/>[2022-05-03T15:40:48.736Z] 2.2M	/home/jenkins/workspace/KIE/kogito/main<br/>[2022-05-03T15:40:48.736Z] 2.2M	/home/jenkins/workspace/KIE/kogito<br/>[2022-05-03T15:40:48.736Z] 2.2M	/home/jenkins/workspace/KIE<br/>[2022-05-03T15:40:48.736Z] 2.2M	/home/jenkins/workspace<br/>[Pipeline] }<br/>[Pipeline] // dir<br/>[Pipeline] }<br/>[Pipeline] // script<br/>[Pipeline] }<br/>[Pipeline] // withEnv<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Install build-chain tool)<br/>[Pipeline] tool<br/>[Pipeline] envVarsForTool<br/>[Pipeline] withEnv<br/>[Pipeline] {<br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] echo<br/>[2022-05-03T15:40:49.085Z] [INFO] Getting build-chain version from composite action file<br/>[Pipeline] readFile<br/>[Pipeline] echo<br/>[2022-05-03T15:40:49.215Z] [INFO] build-chain version recovered '2.3.34'<br/>[Pipeline] sh<br/>[2022-05-03T15:40:49.499Z] + npm install -g @kie/build-chain-action@2.3.34 -registry=https://repository.engineering.redhat.com/nexus/repository/registry.npmjs.org/<br/>[2022-05-03T15:40:52.774Z] /home/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/nodejs-12.16.3/bin/build-chain-action -> /home/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/nodejs-12.16.3/lib/node_modules/@kie/build-chain-action/bin/build-chain-cli.js<br/>[2022-05-03T15:40:52.774Z] npm WARN notsup Unsupported engine for @kie/build-chain-action@2.3.34: wanted: {"node":">= 12.18.0"} (current: {"node":"12.16.3","npm":"6.14.4"})<br/>[2022-05-03T15:40:52.774Z] npm WARN notsup Not compatible with your version of node/npm: @kie/build-chain-action@2.3.34<br/>[2022-05-03T15:40:52.774Z] npm WARN @octokit/plugin-request-log@1.0.4 requires a peer of @octokit/core@>=3 but none is installed. You must install peer dependencies yourself.<br/>[2022-05-03T15:40:52.774Z] <br/>[2022-05-03T15:40:52.774Z] + @kie/build-chain-action@2.3.34<br/>[2022-05-03T15:40:52.774Z] added 108 packages from 88 contributors in 2.704s<br/>[Pipeline] }<br/>[Pipeline] // script<br/>[Pipeline] }<br/>[Pipeline] // withEnv<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Build projects)<br/>[Pipeline] tool<br/>[Pipeline] envVarsForTool<br/>[Pipeline] tool<br/>[Pipeline] envVarsForTool<br/>[Pipeline] tool<br/>[Pipeline] envVarsForTool<br/>[Pipeline] withEnv<br/>[Pipeline] {<br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] configFileProvider<br/>[2022-05-03T15:40:53.200Z] provisioning config files...<br/>[2022-05-03T15:40:53.207Z] copy managed file [kogito_pr_settings] to file:/home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-apps.tests.kogito-apps@tmp/config3832915277033306178tmp<br/>[Pipeline] {<br/>[Pipeline] withCredentials<br/>[2022-05-03T15:40:53.255Z] Masking supported pattern matches of $GITHUB_TOKEN<br/>[Pipeline] {<br/>[Pipeline] sh<br/>[2022-05-03T15:40:53.311Z] Warning: A secret was passed to "sh" using Groovy String interpolation, which is insecure.<br/>[2022-05-03T15:40:53.312Z] 		 Affected argument(s) used the following variable(s): [GITHUB_TOKEN]<br/>[2022-05-03T15:40:53.312Z] 		 See https://jenkins.io/redirect/groovy-string-interpolation for details.<br/>[2022-05-03T15:40:53.649Z] + build-chain-action -token=**** -df=https://raw.githubusercontent.com/kiegroup/kogito-pipelines/main/.ci/pull-request-config.yaml -folder=bc build pr -url=https://github.com/kiegroup/kogito-apps/pull/1328 -sp=kiegroup/kogito-apps --skipParallelCheckout -cct '(^mvn .*)||$1 -s /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-apps.tests.kogito-apps@tmp/config3832915277033306178tmp -Dmaven.wagon.http.ssl.insecure=true -Dmaven.test.failure.ignore=true'<br/>[2022-05-03T15:40:53.905Z] [INFO]  Executing pull request flow for https://github.com/kiegroup/kogito-apps/pull/1328 in bc<br/>[2022-05-03T15:40:54.161Z] [INFO]  https://raw.githubusercontent.com/kiegroup/kogito-pipelines/main/.ci/pull-request-config.yaml exists, using it<br/>[2022-05-03T15:40:54.161Z] ::group::[PRE] Executing pre section for https://raw.githubusercontent.com/kiegroup/kogito-pipelines/main/.ci/pull-request-config.yaml<br/>[2022-05-03T15:40:54.161Z] [INFO]  Execute command 'export BUILD_MVN_OPTS=" -nsu -ntp -fae -e -Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false dependency:tree -Dmaven.wagon.httpconnectionManager.ttlSeconds=120 -Dmaven.wagon.http.retryHandler.count=3"' in dir '/home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-apps.tests.kogito-apps'<br/>[2022-05-03T15:40:54.161Z] [INFO]  Treating export command since it's not possible to run it from the runner itself<br/>[2022-05-03T15:40:54.161Z] [INFO]  The variable BUILD_MVN_OPTS has been stored with ' -nsu -ntp -fae -e -Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false dependency:tree -Dmaven.wagon.httpconnectionManager.ttlSeconds=120 -Dmaven.wagon.http.retryHandler.count=3' value<br/>[2022-05-03T15:40:54.161Z] ::notice title= [PRE] [Execution OK]::export BUILD_MVN_OPTS=" -nsu -ntp -fae -e -Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false dependency:tree -Dmaven.wagon.httpconnectionManager.ttlSeconds=120 -Dmaven.wagon.http.retryHandler.count=3"<br/>[2022-05-03T15:40:54.161Z] [INFO]  Execute command 'echo "BUILD_MVN_OPTS= -nsu -ntp -fae -e -Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false dependency:tree -Dmaven.wagon.httpconnectionManager.ttlSeconds=120 -Dmaven.wagon.http.retryHandler.count=3"' in dir '/home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-apps.tests.kogito-apps'<br/>[2022-05-03T15:40:54.161Z] [command]/usr/bin/echo BUILD_MVN_OPTS= -nsu -ntp -fae -e -Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false dependency:tree -Dmaven.wagon.httpconnectionManager.ttlSeconds=120 -Dmaven.wagon.http.retryHandler.count=3<br/>[2022-05-03T15:40:54.161Z] BUILD_MVN_OPTS= -nsu -ntp -fae -e -Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false dependency:tree -Dmaven.wagon.httpconnectionManager.ttlSeconds=120 -Dmaven.wagon.http.retryHandler.count=3<br/>[2022-05-03T15:40:54.161Z] ::notice title= [PRE] [Execution OK]::echo "BUILD_MVN_OPTS= -nsu -ntp -fae -e -Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false dependency:tree -Dmaven.wagon.httpconnectionManager.ttlSeconds=120 -Dmaven.wagon.http.retryHandler.count=3"<br/>[2022-05-03T15:40:54.161Z] ::endgroup::<br/>[2022-05-03T15:40:54.418Z] ::group::[Pull Request Flow] Execution Plan...<br/>[2022-05-03T15:40:54.418Z] [INFO]  ----------------------------------------------<br/>[2022-05-03T15:40:54.418Z] [INFO]  [4] projects will be executed<br/>[2022-05-03T15:40:54.418Z] <br/>[2022-05-03T15:40:54.418Z] [INFO]  [kiegroup/drools]<br/>[2022-05-03T15:40:54.418Z] [INFO]  Level Type: [upstream].<br/>[2022-05-03T15:40:54.418Z] [INFO]  mvn clean install -Dquickly ${{ env.BUILD_MVN_OPTS }} ${{ env.BUILD_MVN_OPTS_UPSTREAM }} ${{ env.DROOLS_BUILD_MVN_OPTS_UPSTREAM }}<br/>[2022-05-03T15:40:54.418Z] [INFO]  [ [32m'docker system prune -f'[39m ]<br/>[2022-05-03T15:40:54.418Z] <br/>[2022-05-03T15:40:54.418Z] [INFO]  [kiegroup/kogito-runtimes]<br/>[2022-05-03T15:40:54.418Z] [INFO]  Level Type: [upstream].<br/>[2022-05-03T15:40:54.418Z] [INFO]  mvn clean install -Dquickly ${{ env.BUILD_MVN_OPTS }} ${{ env.BUILD_MVN_OPTS_UPSTREAM }} ${{ env.KOGITO_RUNTIMES_BUILD_MVN_OPTS_UPSTREAM }}<br/>[2022-05-03T15:40:54.418Z] [INFO]  [ [32m'docker system prune -f'[39m ]<br/>[2022-05-03T15:40:54.418Z] <br/>[2022-05-03T15:40:54.418Z] [INFO]  [kiegroup/optaplanner]<br/>[2022-05-03T15:40:54.418Z] [INFO]  Level Type: [upstream].<br/>[2022-05-03T15:40:54.418Z] [INFO]  mvn clean install -Dquickly ${{ env.BUILD_MVN_OPTS }} ${{ env.BUILD_MVN_OPTS_UPSTREAM }} ${{ env.OPTAPLANNER_BUILD_MVN_OPTS_UPSTREAM }}<br/>[2022-05-03T15:40:54.418Z] [INFO]  [ [32m'docker system prune -f'[39m ]<br/>[2022-05-03T15:40:54.418Z] <br/>[2022-05-03T15:40:54.418Z] [INFO]  [kiegroup/kogito-apps]<br/>[2022-05-03T15:40:54.418Z] [INFO]  Level Type: [current].<br/>[2022-05-03T15:40:54.418Z] [INFO]  [<br/>[2022-05-03T15:40:54.418Z]   [32m'mvn -f kogito-apps/pom.xml clean install -Dvalidate-formatting ${{ env.BUILD_MVN_OPTS }} ${{ env.BUILD_MVN_OPTS_CURRENT }} ${{ env.KOGITO_APPS_BUILD_MVN_OPTS }}'[39m<br/>[2022-05-03T15:40:54.418Z] ]<br/>[2022-05-03T15:40:54.418Z] [INFO]  [ [32m'docker system prune -f'[39m ]<br/>[2022-05-03T15:40:54.418Z] <br/>[2022-05-03T15:40:54.418Z] [INFO]  ----------------------------------------------<br/>[2022-05-03T15:40:54.418Z] ::endgroup::<br/>[2022-05-03T15:40:54.418Z] ::group::[Pull Request Flow] Checking out kiegroup/kogito-apps and its dependencies<br/>[2022-05-03T15:40:54.418Z] [INFO]  Tree for project kiegroup/kogito-apps. Dependencies: <br/>[2022-05-03T15:40:54.418Z] kiegroup/drools,<br/>[2022-05-03T15:40:54.418Z] kiegroup/kogito-runtimes,<br/>[2022-05-03T15:40:54.418Z] kiegroup/optaplanner,<br/>[2022-05-03T15:40:54.418Z] kiegroup/kogito-apps<br/>[2022-05-03T15:40:54.418Z] [INFO]  [kiegroup/drools] Checking out project<br/>[2022-05-03T15:40:54.418Z] [WARN]  project github.com/radtriste/drools:fix_skipui_profile does not exist. It's not necessarily an error.<br/>[2022-05-03T15:40:54.674Z] [WARN]  project github.com/kiegroup/drools:fix_skipui_profile does not exist. It's not necessarily an error.<br/>[2022-05-03T15:40:54.674Z] [INFO]  [kiegroup/drools] Checking out 'https://github.com/kiegroup/drools:main' into 'bc/kiegroup_drools'<br/>[2022-05-03T15:41:12.711Z] [INFO]  [kiegroup/drools] Checked out.<br/>[2022-05-03T15:41:12.711Z] [INFO]  [kiegroup/drools] Cloning folder bc/kiegroup_drools into drools<br/>[2022-05-03T15:41:12.711Z] [INFO]  [kiegroup/drools] Cloned folder bc/kiegroup_drools into bc/kiegroup_drools/drools<br/>[2022-05-03T15:41:12.711Z] [INFO]  [kiegroup/kogito-runtimes] Checking out project<br/>[2022-05-03T15:41:12.968Z] [INFO]  [kiegroup/kogito-runtimes] Merging https://github.com/kiegroup/kogito-runtimes:main into https://github.com/radtriste/kogito-runtimes:fix_skipui_profile<br/>[2022-05-03T15:41:27.824Z] [INFO]  [kiegroup/kogito-runtimes] Checked out.<br/>[2022-05-03T15:41:27.824Z] [INFO]  [kiegroup/kogito-runtimes] Cloning folder bc/kiegroup_kogito_runtimes into kogito-runtimes<br/>[2022-05-03T15:41:28.102Z] [INFO]  [kiegroup/kogito-runtimes] Cloned folder bc/kiegroup_kogito_runtimes into bc/kiegroup_kogito_runtimes/kogito-runtimes<br/>[2022-05-03T15:41:28.102Z] [INFO]  [kiegroup/optaplanner] Checking out project<br/>[2022-05-03T15:41:28.102Z] [WARN]  radtriste/optaplanner not found. Trying to get it by forked project list.<br/>[2022-05-03T15:41:28.106Z] [ERROR]  You have exceeded a secondary rate limit. Please wait a few minutes before you try again.<br/>[Pipeline] }<br/>[Pipeline] // withCredentials<br/>[Pipeline] }<br/>[2022-05-03T15:41:28.172Z] Deleting 1 temporary files<br/>[Pipeline] // configFileProvider<br/>[Pipeline] }<br/>[Pipeline] // script<br/>Post stage<br/>[Pipeline] junit<br/>[2022-05-03T15:41:28.268Z] Recording test results<br/>[2022-05-03T15:41:28.923Z] No test report files were found. Configuration error?<br/>Error when executing always post condition:<br/>Also:   hudson.remoting.Channel$CallSiteStackTrace: Remote call to rhos-01-kie-psi-rhel7-xlarge-268<br/>		at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1797)<br/>		at hudson.remoting.UserRequest$ExceptionResponse.retrieve(UserRequest.java:356)<br/>		at hudson.remoting.Channel.call(Channel.java:1001)<br/>		at hudson.FilePath.act(FilePath.java:1166)<br/>		at hudson.FilePath.act(FilePath.java:1155)<br/>		at hudson.tasks.junit.JUnitParser.parseResult(JUnitParser.java:107)<br/>		at hudson.tasks.junit.JUnitResultArchiver.parse(JUnitResultArchiver.java:153)<br/>		at hudson.tasks.junit.JUnitResultArchiver.parseAndSummarize(JUnitResultArchiver.java:247)<br/>		at hudson.tasks.junit.pipeline.JUnitResultsStepExecution.run(JUnitResultsStepExecution.java:63)<br/>		at hudson.tasks.junit.pipeline.JUnitResultsStepExecution.run(JUnitResultsStepExecution.java:29)<br/>		at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)<br/>		at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)<br/>hudson.AbortException: No test report files were found. Configuration error?<br/>	at hudson.tasks.junit.JUnitParser$ParseResultCallable.invoke(JUnitParser.java:154)<br/>	at hudson.FilePath$FileCallableWrapper.call(FilePath.java:3338)<br/>	at hudson.remoting.UserRequest.perform(UserRequest.java:211)<br/>	at hudson.remoting.UserRequest.perform(UserRequest.java:54)<br/>	at hudson.remoting.Request$2.run(Request.java:376)<br/>	at hudson.remoting.InterceptingExecutorService.lambda$wrap$0(InterceptingExecutorService.java:78)<br/>	at java.util.concurrent.FutureTask.run(FutureTask.java:266)<br/>	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)<br/>	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)<br/>	at java.lang.Thread.run(Thread.java:750)<br/><br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] sh<br/>[2022-05-03T15:41:29.246Z] + rm -rf console.log<br/>[Pipeline] sh<br/>
</details>

**Comment by radtriste** [comment]
jenkins rerun kogito-apps tests

**Comment by kie-ci1** [comment]
**(tests) - kogito-examples job** `#162` was: **UNSTABLE**
Possible explanation: This should be test failures


**Test results:**
- PASSED: 235
- FAILED: 1

Those are the test failures: 
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-apps.tests.downstream.kogito-examples/162/testReport/org.acme.it/QueryAnswerServiceIT/queryAnswerProcessCycle/">org.acme.it.QueryAnswerServiceIT.queryAnswerProcessCycle</a></summary>
java.lang.AssertionError: <br/>1 expectation failed.<br/>Expected status code <201> but was <400>.<br/><br/>	at org.acme.it.QueryAnswerServiceIT.queryAnswerProcessCycle(QueryAnswerServiceIT.java:87)<br/>
</details>

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-apps.tests.downstream.kogito-examples/162/display/redirect

**Comment by radtriste** [comment]
examples test failure is unrelated

**Pull request merged**
