### PR TITLE
#817 - removing oracle database dependency

### PR DESCRIPTION
**Pull request by porcelli**
This PR is related to https://github.com/apache/incubator-kie-issues/issues/817

Related PR:

- https://github.com/apache/incubator-kie-kogito-runtimes/pull/3369

### CODE REVIEW

**Review by pefernan — APPROVED** [review]

**Comment by fjtirado** [comment]
@porcelli I see that rather than removing the Oracle driver, we are completely removing Oracle db support. 
To be honest, I would have been more conservative, because there is not actually source code depending on oracle stuff to support oracle (since we are using JPA). 
So, It would have been posible to leave references to Oracle and just remove the driver from the repo.

**Comment by porcelli** [comment]
@fjtirado i just wrote this to ML:

I might be interpreting the Category X dependency way too strictly; but it’s my current understanding that we cannot have such dependency in our codebase at all.

The direction that we agreed is to avoid endless discussion and just remove for now; once we past the critical phase of our first release- we can try to explore and discuss different angles to tackle the Category X dependency; it’s just not worth spend time right now on it.

**Comment by fjtirado** [comment]
@porcelli 
We spent quite amount of time on avoiding code duplication for Oracle and Postgresql and we will have to spent again when in future community ask for oracle support (as they already did in the past, the oracle support, a lot of copy paste from postgres that was later refactor, was added by community folks on their spare time) . I do not really see the problem on just removing the driver and test and keep the source code that does not depend on the driver, so people can include the addon and the driver in their projects.

**Comment by porcelli** [comment]
note: community may ask for support and we might not be able to cover the request for legal reasons....

my perspective is to not have unused code left behind just because... that's the value of version control (we can always revert if different interpretation of category X is provided)

**Comment by fjtirado** [comment]
Already implemented

**Pull request closed without merging**
