### PR TITLE
[main] Bump Optaplanner version to 8.38.0.Final

### PR DESCRIPTION
**Pull request by kie-ci3**
Please review and merge

### CODE REVIEW

**Review by radtriste — APPROVED** [review]

**Comment by kie-ci3** [comment]
**(tests) - kogito-apps job** `#996` was: **UNSTABLE**
Possible explanation: This should be test failures


<details>
<summary><b>Reproducer</b></summary>


export BUILD_MVN_OPTS_CURRENT=-Dvalidate-formatting -Prun-code-coverage
build-chain build cross_pr -f 'https://raw.githubusercontent.com/kiegroup/kogito-pipelines/main/.ci/pull-request-config.yaml' -o 'bc' -p kiegroup/kogito-apps -u https://github.com/kiegroup/kogito-apps/pull/1739 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-apps.tests.kogito-apps/996/display/redirect

**Test results:**
- PASSED: 1666
- FAILED: 1

Those are the test failures: 
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-apps.tests.kogito-apps/996/testReport/org.kie.kogito.index.infinispan/ProcessDataIndexInfinispanKafkaIT/testProcessInstanceEvents/">org.kie.kogito.index.infinispan.ProcessDataIndexInfinispanKafkaIT.testProcessInstanceEvents</a></summary>
java.lang.RuntimeException: java.lang.IllegalStateException: Unable to determine the status of the running process. See the above logs for details<br/>Caused by: java.lang.IllegalStateException: Unable to determine the status of the running process. See the above logs for details<br/>
</details>

**Comment by radtriste** [comment]
jenkins rerun kogito-apps tests

**Review by cristianonicolai — APPROVED** [review]

**Comment by cristianonicolai** [comment]
jenkins run quarkus-lts

**Comment by cristianonicolai** [comment]
Jenkins run native

**Comment by kie-ci3** [comment]
**(native) - kogito-apps job** `#16` was: **UNSTABLE**
Possible explanation: This should be test failures


<details>
<summary><b>Reproducer</b></summary>


export BUILD_MVN_OPTS_CURRENT=-Dnative -Dquarkus.native.container-build=true 
build-chain build cross_pr -f 'https://raw.githubusercontent.com/kiegroup/kogito-pipelines/main/.ci/pull-request-config.yaml' -o 'bc' -p kiegroup/kogito-apps -u https://github.com/kiegroup/kogito-apps/pull/1739 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest.native/job/kogito-apps.native.kogito-apps/16/display/redirect

**Test results:**
- PASSED: 1184
- FAILED: 6

Those are the test failures: 
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest.native/job/kogito-apps.native.kogito-apps/16/testReport/org.kie.kogito.it.jobs/ProcessTimerIT/Build_projects___testDeleteTimerCycle/">Build projects / org.kie.kogito.it.jobs.ProcessTimerIT.testDeleteTimerCycle</a></summary>
org.awaitility.core.ConditionTimeoutException: <br/>Assertion condition defined as a lambda expression in org.kie.kogito.it.jobs.BaseProcessTimerIT 1 expectation failed.<br/>JSON path data.Jobs.size() doesn't match.<br/>Expected: is <1><br/>  Actual: <0><br/> within 10 seconds.<br/>Caused by: java.util.concurrent.TimeoutException<br/>
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest.native/job/kogito-apps.native.kogito-apps/16/testReport/org.kie.kogito.it.jobs/ProcessTimerIT/Build_projects___testBoundaryTimersOnTask/">Build projects / org.kie.kogito.it.jobs.ProcessTimerIT.testBoundaryTimersOnTask</a></summary>
java.lang.AssertionError: <br/>1 expectation failed.<br/>JSON path data.Jobs.size() doesn't match.<br/>Expected: is <1><br/>  Actual: <0><br/><br/>
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest.native/job/kogito-apps.native.kogito-apps/16/testReport/org.kie.kogito.it.jobs/ProcessTimerIT/Build_projects___testTimerCycle/">Build projects / org.kie.kogito.it.jobs.ProcessTimerIT.testTimerCycle</a></summary>
java.lang.AssertionError: <br/>1 expectation failed.<br/>JSON path data.Jobs.size() doesn't match.<br/>Expected: is <1><br/>  Actual: <0><br/><br/>
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest.native/job/kogito-apps.native.kogito-apps/16/testReport/org.kie.kogito.it.jobs/ProcessTimerIT/Build_projects___testTimers/">Build projects / org.kie.kogito.it.jobs.ProcessTimerIT.testTimers</a></summary>
java.lang.AssertionError: <br/>1 expectation failed.<br/>JSON path data.Jobs.size() doesn't match.<br/>Expected: is <1><br/>  Actual: <0><br/><br/>
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest.native/job/kogito-apps.native.kogito-apps/16/testReport/org.kie.kogito.it.jobs/ProcessTimerIT/Build_projects___testDeleteBoundaryTimersOnTask/">Build projects / org.kie.kogito.it.jobs.ProcessTimerIT.testDeleteBoundaryTimersOnTask</a></summary>
java.lang.AssertionError: <br/>1 expectation failed.<br/>JSON path data.Jobs.size() doesn't match.<br/>Expected: is <1><br/>  Actual: <0><br/><br/>
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest.native/job/kogito-apps.native.kogito-apps/16/testReport/org.kie.kogito.it.jobs/ProcessTimerIT/Build_projects___testCancelTimer/">Build projects / org.kie.kogito.it.jobs.ProcessTimerIT.testCancelTimer</a></summary>
java.lang.AssertionError: <br/>1 expectation failed.<br/>JSON path data.Jobs.size() doesn't match.<br/>Expected: is <1><br/>  Actual: <0><br/><br/>
</details>

**Comment by radtriste** [comment]
> **(native) - kogito-apps job** `#16` was: **UNSTABLE** Possible explanation: This should be test failures
> 
> Reproducer
> Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest.native/job/kogito-apps.native.kogito-apps/16/display/redirect
> 
> **Test results:**
> 
> * PASSED: 1184
> * FAILED: 6
> 
> Those are the test failures:
> 
> [Build projects / org.kie.kogito.it.jobs.ProcessTimerIT.testDeleteTimerCycle](https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest.native/job/kogito-apps.native.kogito-apps/16/testReport/org.kie.kogito.it.jobs/ProcessTimerIT/Build_projects___testDeleteTimerCycle/)
> [Build projects / org.kie.kogito.it.jobs.ProcessTimerIT.testBoundaryTimersOnTask](https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest.native/job/kogito-apps.native.kogito-apps/16/testReport/org.kie.kogito.it.jobs/ProcessTimerIT/Build_projects___testBoundaryTimersOnTask/)
> [Build projects / org.kie.kogito.it.jobs.ProcessTimerIT.testTimerCycle](https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest.native/job/kogito-apps.native.kogito-apps/16/testReport/org.kie.kogito.it.jobs/ProcessTimerIT/Build_projects___testTimerCycle/)
> [Build projects / org.kie.kogito.it.jobs.ProcessTimerIT.testTimers](https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest.native/job/kogito-apps.native.kogito-apps/16/testReport/org.kie.kogito.it.jobs/ProcessTimerIT/Build_projects___testTimers/)
> [Build projects / org.kie.kogito.it.jobs.ProcessTimerIT.testDeleteBoundaryTimersOnTask](https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest.native/job/kogito-apps.native.kogito-apps/16/testReport/org.kie.kogito.it.jobs/ProcessTimerIT/Build_projects___testDeleteBoundaryTimersOnTask/)
> [Build projects / org.kie.kogito.it.jobs.ProcessTimerIT.testCancelTimer](https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest.native/job/kogito-apps.native.kogito-apps/16/testReport/org.kie.kogito.it.jobs/ProcessTimerIT/Build_projects___testCancelTimer/)

Known issues and not related to the change

**Pull request merged**
