### PR TITLE
FAI-668: Explainability: Native build is broken

### PR DESCRIPTION
**Pull request by manstis**
See https://issues.redhat.com/browse/FAI-668

The _real fix_ was made by @mariofusco however I also need to fix the reflection file for `explainability` (for different reasons).

Many thanks for submitting your Pull Request :heart:! 

Please make sure that your PR meets the following requirements:

- [x] You have read the [contributors guide](https://github.com/kiegroup/kogito-runtimes#contributing-to-kogito)
- [x] Pull Request title is properly formatted: `KOGITO-XYZ Subject`
- [x] Pull Request title contains the target branch if not targeting main: `[0.9.x] KOGITO-XYZ Subject`
- [x] Pull Request contains link to the JIRA issue
- [x] Pull Request contains link to any dependent or related Pull Request
- [x] Pull Request contains description of the issue
- [x] Pull Request does not include fixes for issues other than the main ticket

<details>
<summary>
How to replicate CI configuration locally?
</summary>

Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use latest version of the code for each repository.
 
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you need to change multiple repositories and send multiple dependent pull requests related with a change you can easily reproduce the same build by executing it on Github hosted environment or locally in your development environment. See [local execution](https://github.com/kiegroup/github-action-build-chain#local-execution) details to get more information about it.
</details>

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>Pull Request</b>  
  Please add comment: <b>Jenkins retest this</b>
 
* <b>Quarkus LTS checks</b>  
  Please add comment: <b>Jenkins run LTS</b>

* <b>Native checks</b>  
  Please add comment: <b>Jenkins run native</b>

</details>

### CODE REVIEW

**Comment by manstis** [comment]
Jenkins run native

**Comment by manstis** [comment]
Jenkins run native

**Comment by manstis** [comment]
Jenkins run native

**Comment by manstis** [comment]
Jenkins run native

**Comment by manstis** [comment]
Jenkins retest this

**Comment by manstis** [comment]
All builds fail due to know `-SNAPSHOT` dependency problems.. 

I'll try again tomorrow.

**Comment by manstis** [comment]
Jenkins run native

**Comment by manstis** [comment]
Jenkins retest this

**Comment by manstis** [comment]
Jenkins retest this

**Comment by manstis** [comment]
Jenkins run native

**Comment by manstis** [comment]
Jenkins run native

**Comment by manstis** [comment]
Jenkins run native

**Comment by manstis** [comment]
Jenkins run native

**Comment by manstis** [comment]
Jenkins run native

**Comment by manstis** [comment]
Jenkins run native

**Comment by manstis** [comment]
Jenkins run native

**Comment by manstis** [comment]
Jenkins run native

**Comment by manstis** [comment]
Jenkins run native

**Comment by manstis** [comment]
@r00ta @danielezonca given a successful native build is like finding gold at the end of a rainbow can this be merged "as is"?

It fixes some known issues with Trusty's native builds and improves logging (to help determine future failures).

I can't see it being harmful even if the likelihood of getting a green native build is slim.

See my email to BSIG with the latest failures (to many native builds).

**Comment by manstis** [comment]
Jenkins run native

**Comment by manstis** [comment]
Jenkins retest this

**Comment by manstis** [comment]
Jenkins run native

**Comment by manstis** [comment]
Jenkins run native

**Comment by manstis** [comment]
Jenkins run native

**Comment by manstis** [comment]
Jenkins run native

**Comment by manstis** [comment]
Jenkins run native

**Comment by manstis** [comment]
Jenkins run native

**Comment by manstis** [comment]
Jenkins run native

**Comment by ricardozanini** [comment]
Watching

**Comment by manstis** [comment]
Jenkins run native

**Comment by manstis** [comment]
Weird...
```
[2021-12-03T17:53:20.389Z] Error: Error parsing reflection configuration in /project/reflection-config.json:
[2021-12-03T17:53:20.389Z] Could not resolve org.kie.kogito.explainability.api.CounterfactualDomainFixed for reflection configuration. Reason: java.lang.ClassNotFoundException: org.kie.kogito.explainability.api.CounterfactualDomainFixed. To allow unresolvable reflection configuration, use option --allow-incomplete-classpath
[2021-12-03T17:53:20.389Z] Verify that the configuration matches the schema described in the -H:PrintFlags=+ output for option ReflectionConfigurationFiles.
[2021-12-03T17:53:20.389Z] com.oracle.svm.core.util.UserError$UserException: Error parsing reflection configuration in /project/reflection-config.json:
[2021-12-03T17:53:20.389Z] Could not resolve org.kie.kogito.explainability.api.CounterfactualDomainFixed for reflection configuration. Reason: java.lang.ClassNotFoundException: org.kie.kogito.explainability.api.CounterfactualDomainFixed. To allow unresolvable reflection configuration, use option --allow-incomplete-classpath
```
The text `org.kie.kogito.explainability.api.CounterfactualDomainFixed` does not exist anywhere in `kogito-apps`.

**Comment by manstis** [comment]
Closing and re-submitting due to [this](https://github.com/kiegroup/kogito-apps/pull/1110#issuecomment-986684639).

**Pull request closed without merging**
