### PR TITLE
[KOGITO-6840] Remove duplicated reflection mapping 

### PR DESCRIPTION
**Pull request by gitgabrio**
@evacchi @tiagodolphine  @manstis 

This PR removes duplicated reflection mapping, i.e. reflection config that is present both in kogito-runtimes `KogitoAssetProcessor` and in kogito-apps `reflection-config.json`

It needs https://github.com/kiegroup/kogito-runtimes/pull/2031 to be merged before

Many thanks for submitting your Pull Request :heart:! 

Please make sure that your PR meets the following requirements:

- [ ] You have read the [contributors guide](https://github.com/kiegroup/kogito-runtimes#contributing-to-kogito)
- [ ] Pull Request title is properly formatted: `KOGITO-XYZ Subject`
- [ ] Pull Request title contains the target branch if not targeting main: `[0.9.x] KOGITO-XYZ Subject`
- [ ] Pull Request contains link to the JIRA issue
- [ ] Pull Request contains link to any dependent or related Pull Request
- [ ] Pull Request contains description of the issue
- [ ] Pull Request does not include fixes for issues other than the main ticket

<details>
<summary>
How to replicate CI configuration locally?
</summary>

Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use latest version of the code for each repository.
 
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you need to change multiple repositories and send multiple dependent pull requests related with a change you can easily reproduce the same build by executing it on Github hosted environment or locally in your development environment. See [local execution](https://github.com/kiegroup/github-action-build-chain#local-execution) details to get more information about it.
</details>

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>Pull Request</b>  
  Please add comment: <b>Jenkins retest this</b>
 
* <b>Quarkus LTS checks</b>  
  Please add comment: <b>Jenkins run LTS</b>

* <b>Native checks</b>  
  Please add comment: <b>Jenkins run native</b>

</details>

### CODE REVIEW

**Review by tiagodolphine — APPROVED** [review]
LGTM, thanks.

**Comment by domhanak** [comment]
@manstis @tiagodolphine is this still relevant or can we close this?

**Comment by gitgabrio** [comment]
@domhanak If the build is green I think it can be merged @danielezonca wdyt ?

**Comment by danielezonca** [comment]
@gitgabrio 
Given that this configuration is for native compilation I would probably trigger a native compilation build before merging to be on the safe side.
Wdyt?

**Comment by gitgabrio** [comment]
Jenkins run native

**Comment by gitgabrio** [comment]
@danielezonca @domhanak I think it could be merged now

**Comment by domhanak** [comment]
@gitgabrio Thanks! @paulovmr this is also ready

**Pull request merged**
